
var Module = (() => {
  var _scriptDir = import.meta.url;
  
  return (
async function(moduleArg = {}) {

var h=moduleArg,aa,ba;h.ready=new Promise((a,b)=>{aa=a;ba=b});h.Ic=!0;h.Jc=!0;
"object"!==typeof WebAssembly&&"undefined"!==typeof WXWebAssembly&&(WXWebAssembly.RuntimeError=WXWebAssembly.RuntimeError||function(){class a extends Error{constructor(b){super(b);this instanceof a||(b=Object.setPrototypeOf,"function"===typeof b?b.call(Object,this,a.prototype):this.__proto__=a.prototype,"function"===typeof Error.captureStackTrace&&Error.captureStackTrace(this,a))}}Object.defineProperty(a.prototype,"name",{configurable:!0,writable:!0,value:"RuntimeError"});return a}(),function(){if("undefined"!==
typeof globalThis)return globalThis;var a=function(){return this}(),b=function(){try{var c=new Function}catch(d){return!1}return"function"===typeof c}();if(!a&&b)try{a=(new Function("return this"))()}catch(c){}if(!a){if("undefined"===typeof __webpack_public_path__&&"undefined"!==typeof global)return global;if("undefined"!==typeof window)return window;if("undefined"!==typeof self)return self}return a}().WebAssembly=WXWebAssembly);
var ca=Object.assign({},h),da="./this.program",ea=(a,b)=>{throw b;},fa="object"==typeof window,ha="function"==typeof importScripts,ia="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,p="",ja,ka,la;
if(ia){const {createRequire:a}=await import("module");var require=a(import.meta.url),fs=require("fs"),ma=require("path");ha?p=ma.dirname(p)+"/":p=require("url").fileURLToPath(new URL("./",import.meta.url));ja=(b,c)=>{b=na(b)?new URL(b):ma.normalize(b);return fs.readFileSync(b,c?void 0:"utf8")};la=b=>{b=ja(b,!0);b.buffer||(b=new Uint8Array(b));return b};ka=(b,c,d,e=!0)=>{b=na(b)?new URL(b):ma.normalize(b);fs.readFile(b,e?void 0:"utf8",(f,g)=>{f?d(f):c(e?g.buffer:g)})};
!h.thisProgram&&1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);ea=(b,c)=>{process.exitCode=b;throw c;};h.inspect=()=>"[Emscripten Module object]"}else if(fa||ha)ha?p=self.location.href:"undefined"!=typeof document&&document.currentScript&&(p=document.currentScript.src),_scriptDir&&(p=_scriptDir),0!==p.indexOf("blob:")?p=p.substr(0,p.replace(/[?#].*/,"").lastIndexOf("/")+1):p="",ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},
ha&&(la=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ka=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var oa=h.print||console.log.bind(console),pa=h.printErr||console.error.bind(console);Object.assign(h,ca);ca=null;h.thisProgram&&(da=h.thisProgram);h.quit&&(ea=h.quit);var qa;
h.wasmBinary&&(qa=h.wasmBinary);"object"!=typeof WebAssembly&&w("no native wasm support detected");var ra,sa=!1,x,y,z,ta,A,B,ua,va;function wa(){var a=ra.buffer;h.HEAP8=x=new Int8Array(a);h.HEAP16=z=new Int16Array(a);h.HEAPU8=y=new Uint8Array(a);h.HEAPU16=ta=new Uint16Array(a);h.HEAP32=A=new Int32Array(a);h.HEAPU32=B=new Uint32Array(a);h.HEAPF32=ua=new Float32Array(a);h.HEAPF64=va=new Float64Array(a)}var xa=[],ya=[],za=[],Aa=[];function Ba(){var a=h.preRun.shift();xa.unshift(a)}
var Ca=0,Da=null,Ea=null;function Fa(){Ca++;h.monitorRunDependencies&&h.monitorRunDependencies(Ca)}function Ga(){Ca--;h.monitorRunDependencies&&h.monitorRunDependencies(Ca);if(0==Ca&&(null!==Da&&(clearInterval(Da),Da=null),Ea)){var a=Ea;Ea=null;a()}}function w(a){if(h.onAbort)h.onAbort(a);a="Aborted("+a+")";pa(a);sa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}
var Ha=a=>a.startsWith("data:application/octet-stream;base64,"),na=a=>a.startsWith("file://"),Ia;if(h.locateFile){if(Ia="bootloader.wasm?version=1.0.0",!Ha(Ia)){var Ja=Ia;Ia=h.locateFile?h.locateFile(Ja,p):p+Ja}}else Ia=(new URL("bootloader.wasm?version=1.0.0",import.meta.url)).href;function Ka(a){if(a==Ia&&qa)return new Uint8Array(qa);if(la)return la(a);throw"both async and sync fetching of the wasm failed";}
function La(a){if(!qa&&(fa||ha)){if("function"==typeof fetch&&!na(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Ka(a));if(ka)return new Promise((b,c)=>{ka(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Ka(a))}function Ma(a,b,c){return La(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{pa(`failed to asynchronously prepare wasm: ${d}`);w(d)})}
function Na(a,b){var c=Ia;return qa||"function"!=typeof WebAssembly.instantiateStreaming||Ha(c)||na(c)||ia||"function"!=typeof fetch?Ma(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){pa(`wasm streaming compile failed: ${e}`);pa("falling back to ArrayBuffer instantiation");return Ma(c,a,b)}))}var C,D;function Oa(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Pa=a=>{for(;0<a.length;)a.shift()(h)},Qa=h.noExitRuntime||!1,Ra=[],Sa=0,Ta=0;
function Ua(a){this.Gb=a;this.pb=a-24;this.vc=function(b){B[this.pb+4>>2]=b};this.nb=function(){return B[this.pb+4>>2]};this.uc=function(b){B[this.pb+8>>2]=b};this.ac=function(b){x[this.pb+12>>0]=b?1:0};this.rc=function(){return 0!=x[this.pb+12>>0]};this.bc=function(b){x[this.pb+13>>0]=b?1:0};this.hc=function(){return 0!=x[this.pb+13>>0]};this.Wb=function(b,c){this.Db(0);this.vc(b);this.uc(c)};this.Db=function(b){B[this.pb+16>>2]=b};this.qc=function(){return B[this.pb+16>>2]};this.sc=function(){if(Va(this.nb()))return B[this.Gb>>
2];var b=this.qc();return 0!==b?b:this.Gb}}
var Za=a=>{var b=Ta;if(!b)return Xa(0),0;var c=new Ua(b);c.Db(b);var d=c.nb();if(!d)return Xa(0),b;for(var e in a){var f=a[e];if(0===f||f===d)break;if(Ya(f,d,c.pb+16))return Xa(f),b}Xa(d);return b},$a=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},E=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=$a(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?
"/":"")+a},ab=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},bb=a=>{if("/"===a)return"/";a=E(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},cb=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(ia)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;
return c=>(c.set(b(c.byteLength)),c)}catch(c){}w("initRandomDevice")},db=a=>(db=cb())(a);function eb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:fb;if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=$a(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}
var gb="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,F=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&gb)return gb.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
hb=[],ib=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},jb=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&
63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e};function kb(a,b){var c=Array(ib(a)+1);a=jb(a,c,0,c.length);b&&(c.length=a);return c}var lb=[];function mb(a,b){lb[a]={input:[],output:[],wb:b};nb(a,ob)}
var ob={open(a){var b=lb[a.node.rdev];if(!b)throw new H(43);a.tty=b;a.seekable=!1},close(a){a.tty.wb.fsync(a.tty)},fsync(a){a.tty.wb.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.wb.Ub)throw new H(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.wb.Ub(a.tty)}catch(l){throw new H(29);}if(void 0===g&&0===e)throw new H(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.wb.Nb)throw new H(60);try{for(var e=0;e<d;e++)a.tty.wb.Nb(a.tty,b[c+
e])}catch(f){throw new H(29);}d&&(a.node.timestamp=Date.now());return e}},pb={Ub(){a:{if(!hb.length){var a=null;if(ia){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c?a=b.slice(0,c).toString("utf-8"):a=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}hb=kb(a,!0)}a=
hb.shift()}return a},Nb(a,b){null===b||10===b?(oa(F(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(oa(F(a.output,0)),a.output=[])},kc(){return{Ec:25856,Gc:5,Dc:191,Fc:35387,Cc:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},lc(){return 0},mc(){return[24,80]}},qb={Nb(a,b){null===b||10===b?(pa(F(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(pa(F(a.output,0)),a.output=[])}};
function rb(a,b){var c=a.jb?a.jb.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.jb,a.jb=new Uint8Array(b),0<a.lb&&a.jb.set(c.subarray(0,a.lb),0))}
var J={sb:null,vb(){return J.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new H(63);J.sb||(J.sb={dir:{node:{rb:J.ib.rb,ob:J.ib.ob,lookup:J.ib.lookup,Ib:J.ib.Ib,rename:J.ib.rename,unlink:J.ib.unlink,rmdir:J.ib.rmdir,readdir:J.ib.readdir,symlink:J.ib.symlink},stream:{zb:J.kb.zb}},file:{node:{rb:J.ib.rb,ob:J.ib.ob},stream:{zb:J.kb.zb,read:J.kb.read,write:J.kb.write,Hb:J.kb.Hb,Mb:J.kb.Mb,Zb:J.kb.Zb}},link:{node:{rb:J.ib.rb,ob:J.ib.ob,readlink:J.ib.readlink},
stream:{}},Rb:{node:{rb:J.ib.rb,ob:J.ib.ob},stream:sb}});c=tb(a,b,c,d);L(c.mode)?(c.ib=J.sb.dir.node,c.kb=J.sb.dir.stream,c.jb={}):32768===(c.mode&61440)?(c.ib=J.sb.file.node,c.kb=J.sb.file.stream,c.lb=0,c.jb=null):40960===(c.mode&61440)?(c.ib=J.sb.link.node,c.kb=J.sb.link.stream):8192===(c.mode&61440)&&(c.ib=J.sb.Rb.node,c.kb=J.sb.Rb.stream);c.timestamp=Date.now();a&&(a.jb[b]=c,a.timestamp=c.timestamp);return c},Hc(a){return a.jb?a.jb.subarray?a.jb.subarray(0,a.lb):new Uint8Array(a.jb):new Uint8Array(0)},
ib:{rb(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;L(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.lb:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.fc=4096;b.blocks=Math.ceil(b.size/b.fc);return b},ob(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.lb!=b))if(0==
b)a.jb=null,a.lb=0;else{var c=a.jb;a.jb=new Uint8Array(b);c&&a.jb.set(c.subarray(0,Math.min(b,a.lb)));a.lb=b}},lookup(){throw ub[44];},Ib(a,b,c,d){return J.createNode(a,b,c,d)},rename(a,b,c){if(L(a.mode)){try{var d=vb(b,c)}catch(f){}if(d)for(var e in d.jb)throw new H(55);}delete a.parent.jb[a.name];a.parent.timestamp=Date.now();a.name=c;b.jb[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink(a,b){delete a.jb[b];a.timestamp=Date.now()},rmdir(a,b){var c=vb(a,b),d;for(d in c.jb)throw new H(55);delete a.jb[b];
a.timestamp=Date.now()},readdir(a){var b=[".",".."],c;for(c in a.jb)a.jb.hasOwnProperty(c)&&b.push(c);return b},symlink(a,b,c){a=J.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new H(28);return a.link}},kb:{read(a,b,c,d,e){var f=a.node.jb;if(e>=a.node.lb)return 0;a=Math.min(a.node.lb-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===x.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=
Date.now();if(b.subarray&&(!a.jb||a.jb.subarray)){if(f)return a.jb=b.subarray(c,c+d),a.lb=d;if(0===a.lb&&0===e)return a.jb=b.slice(c,c+d),a.lb=d;if(e+d<=a.lb)return a.jb.set(b.subarray(c,c+d),e),d}rb(a,e+d);if(a.jb.subarray&&b.subarray)a.jb.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.jb[e+f]=b[c+f];a.lb=Math.max(a.lb,e+d);return d},zb(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.lb);if(0>b)throw new H(28);return b},Hb(a,b,c){rb(a.node,b+c);a.node.lb=Math.max(a.node.lb,
b+c)},Mb(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new H(43);a=a.node.jb;if(e&2||a.buffer!==x.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;w();b=void 0;if(!b)throw new H(48);x.set(a,b)}else c=!1,b=a.byteOffset;return{pb:b,qb:c}},Zb(a,b,c,d){J.kb.write(a,b,0,d,c,!1);return 0}}},wb=(a,b,c)=>{var d=`al ${a}`;ka(a,e=>{e||w(`Loading data file "${a}" failed (no arrayBuffer).`);b(new Uint8Array(e));d&&Ga(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;
});d&&Fa(d)},xb=h.preloadPlugins||[],yb=(a,b,c,d)=>{"undefined"!=typeof Browser&&Browser.Wb();var e=!1;xb.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},Ab=(a,b,c,d,e,f,g,l,m,n)=>{function q(k){function u(r){n&&n();l||zb(a,b,r,d,e,m);f&&f();Ga(v)}yb(k,t,u,()=>{g&&g();Ga(v)})||u(k)}var t=b?eb(E(a+"/"+b)):a,v=`cp ${t}`;Fa(v);"string"==typeof c?wb(c,k=>q(k),g):q(c)},Bb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Cb=null,Db={},Eb=[],Fb=1,Gb=null,fb="/",Hb=!0,H=null,ub={};
function M(a,b={}){a=eb(a);if(!a)return{path:"",node:null};b=Object.assign({Sb:!0,Ob:0},b);if(8<b.Ob)throw new H(32);a=a.split("/").filter(g=>!!g);for(var c=Cb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=vb(c,a[e]);d=E(d+"/"+a[e]);c.Eb&&(!f||f&&b.Sb)&&(c=c.Eb.root);if(!f||b.Cb)for(f=0;40960===(c.mode&61440);)if(c=Ib(d),d=eb(ab(d),c),c=M(d,{Ob:b.Ob+1}).node,40<f++)throw new H(32);}return{path:d,node:c}}
function Jb(a){for(var b;;){if(a===a.parent)return a=a.vb.Yb,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Kb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Gb.length}function Lb(a){var b=Kb(a.parent.id,a.name);if(Gb[b]===a)Gb[b]=a.Fb;else for(b=Gb[b];b;){if(b.Fb===a){b.Fb=a.Fb;break}b=b.Fb}}
function vb(a,b){var c;if(c=(c=Mb(a,"x"))?c:a.ib.lookup?0:2)throw new H(c,a);for(c=Gb[Kb(a.id,b)];c;c=c.Fb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ib.lookup(a,b)}function tb(a,b,c,d){a=new Nb(a,b,c,d);b=Kb(a.parent.id,a.name);a.Fb=Gb[b];return Gb[b]=a}function L(a){return 16384===(a&61440)}function Ob(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function Mb(a,b){if(Hb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Pb(a,b){try{return vb(a,b),20}catch(c){}return Mb(a,"wx")}function Qb(a,b,c){try{var d=vb(a,b)}catch(e){return e.mb}if(a=Mb(a,"wx"))return a;if(c){if(!L(d.mode))return 54;if(d===d.parent||Jb(d)===fb)return 10}else if(L(d.mode))return 31;return 0}function Rb(){for(var a=0;4096>=a;a++)if(!Eb[a])return a;throw new H(33);}
function N(a){a=Eb[a];if(!a)throw new H(8);return a}function Sb(a,b=-1){Tb||(Tb=function(){this.nb={}},Tb.prototype={},Object.defineProperties(Tb.prototype,{object:{get(){return this.node},set(c){this.node=c}},flags:{get(){return this.nb.flags},set(c){this.nb.flags=c}},position:{get(){return this.nb.position},set(c){this.nb.position=c}}}));a=Object.assign(new Tb,a);-1==b&&(b=Rb());a.fd=b;return Eb[b]=a}var sb={open(a){a.kb=Db[a.node.rdev].kb;a.kb.open&&a.kb.open(a)},zb(){throw new H(70);}};
function nb(a,b){Db[a]={kb:b}}function Ub(a,b){var c="/"===b,d=!b;if(c&&Cb)throw new H(10);if(!c&&!d){var e=M(b,{Sb:!1});b=e.path;e=e.node;if(e.Eb)throw new H(10);if(!L(e.mode))throw new H(54);}b={type:a,Lc:{},Yb:b,tc:[]};a=a.vb(b);a.vb=b;b.root=a;c?Cb=a:e&&(e.Eb=b,e.vb&&e.vb.tc.push(b))}function Vb(a,b,c){var d=M(a,{parent:!0}).node;a=bb(a);if(!a||"."===a||".."===a)throw new H(28);var e=Pb(d,a);if(e)throw new H(e);if(!d.ib.Ib)throw new H(63);return d.ib.Ib(d,a,b,c)}
function O(a,b){return Vb(a,(void 0!==b?b:511)&1023|16384,0)}function Wb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Vb(a,b|8192,c)}function Xb(a,b){if(!eb(a))throw new H(44);var c=M(b,{parent:!0}).node;if(!c)throw new H(44);b=bb(b);var d=Pb(c,b);if(d)throw new H(d);if(!c.ib.symlink)throw new H(63);c.ib.symlink(c,b,a)}function Yb(a){var b=M(a,{parent:!0}).node;a=bb(a);var c=vb(b,a),d=Qb(b,a,!0);if(d)throw new H(d);if(!b.ib.rmdir)throw new H(63);if(c.Eb)throw new H(10);b.ib.rmdir(b,a);Lb(c)}
function Zb(a){var b=M(a,{parent:!0}).node;if(!b)throw new H(44);a=bb(a);var c=vb(b,a),d=Qb(b,a,!1);if(d)throw new H(d);if(!b.ib.unlink)throw new H(63);if(c.Eb)throw new H(10);b.ib.unlink(b,a);Lb(c)}function Ib(a){a=M(a).node;if(!a)throw new H(44);if(!a.ib.readlink)throw new H(28);return eb(Jb(a.parent),a.ib.readlink(a))}function $b(a,b){a="string"==typeof a?M(a,{Cb:!0}).node:a;if(!a.ib.ob)throw new H(63);a.ib.ob(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function ac(a,b,c){if(""===a)throw new H(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=E(a);try{e=M(a,{Cb:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new H(20);}else e=Vb(a,c,0),d=!0;if(!e)throw new H(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&!L(e.mode))throw new H(54);if(!d&&(c=
e?40960===(e.mode&61440)?32:L(e.mode)&&("r"!==Ob(b)||b&512)?31:Mb(e,Ob(b)):44))throw new H(c);if(b&512&&!d){c=e;c="string"==typeof c?M(c,{Cb:!0}).node:c;if(!c.ib.ob)throw new H(63);if(L(c.mode))throw new H(31);if(32768!==(c.mode&61440))throw new H(28);if(d=Mb(c,"w"))throw new H(d);c.ib.ob(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Sb({node:e,path:Jb(e),flags:b,seekable:!0,position:0,kb:e.kb,Bc:[],error:!1});e.kb.open&&e.kb.open(e);!h.logReadFiles||b&1||(bc||(bc={}),a in bc||(bc[a]=1));return e}
function cc(a){if(null===a.fd)throw new H(8);a.yb&&(a.yb=null);try{a.kb.close&&a.kb.close(a)}catch(b){throw b;}finally{Eb[a.fd]=null}a.fd=null}function dc(a,b,c){if(null===a.fd)throw new H(8);if(!a.seekable||!a.kb.zb)throw new H(70);if(0!=c&&1!=c&&2!=c)throw new H(28);a.position=a.kb.zb(a,b,c);a.Bc=[];return a.position}
function ec(a,b,c,d,e,f){if(0>d||0>e)throw new H(28);if(null===a.fd)throw new H(8);if(0===(a.flags&2097155))throw new H(8);if(L(a.node.mode))throw new H(31);if(!a.kb.write)throw new H(28);a.seekable&&a.flags&1024&&dc(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new H(70);b=a.kb.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function fc(){H||(H=function(a,b){this.name="ErrnoError";this.node=b;this.wc=function(c){this.mb=c};this.wc(a);this.message="FS error"},H.prototype=Error(),H.prototype.constructor=H,[44].forEach(a=>{ub[a]=new H(a);ub[a].stack="<generic error, no stack>"}))}var gc;function hc(a,b){a="string"==typeof a?a:Jb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=E(a+"/"+c);try{O(d)}catch(e){}a=d}}return d}
function ic(a,b,c,d){a=E(("string"==typeof a?a:Jb(a))+"/"+b);c=Bb(c,d);return Vb(a,(void 0!==c?c:438)&4095|32768,0)}function zb(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:Jb(a),g=b?E(a+"/"+b):a);a=Bb(d,e);g=Vb(g,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}$b(g,a|146);b=ac(g,577);ec(b,c,0,c.length,0,f);cc(b);$b(g,a)}return g}
function P(a,b,c,d){a=E(("string"==typeof a?a:Jb(a))+"/"+b);b=Bb(!!c,!!d);P.Xb||(P.Xb=64);var e=P.Xb++<<8|0;nb(e,{open(f){f.seekable=!1},close(){d&&d.buffer&&d.buffer.length&&d(10)},read(f,g,l,m){for(var n=0,q=0;q<m;q++){try{var t=c()}catch(v){throw new H(29);}if(void 0===t&&0===n)throw new H(6);if(null===t||void 0===t)break;n++;g[l+q]=t}n&&(f.node.timestamp=Date.now());return n},write(f,g,l,m){for(var n=0;n<m;n++)try{d(g[l+n])}catch(q){throw new H(29);}m&&(f.node.timestamp=Date.now());return n}});
return Wb(a,b,e)}function jc(a){if(!(a.nc||a.oc||a.link||a.jb)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ja)try{a.jb=kb(ja(a.url),!0),a.lb=a.jb.length}catch(b){throw new H(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function kc(a,b,c,d,e){function f(){this.Lb=!1;this.nb=[]}f.prototype.get=function(q){if(!(q>this.length-1||0>q)){var t=q%this.chunkSize;return this.Vb(q/this.chunkSize|0)[t]}};f.prototype.Db=function(q){this.Vb=q};f.prototype.Qb=function(){var q=new XMLHttpRequest;q.open("HEAD",c,!1);q.send(null);if(!(200<=q.status&&300>q.status||304===q.status))throw Error("Couldn't load "+c+". Status: "+q.status);var t=Number(q.getResponseHeader("Content-length")),v,k=(v=q.getResponseHeader("Accept-Ranges"))&&
"bytes"===v;q=(v=q.getResponseHeader("Content-Encoding"))&&"gzip"===v;var u=1048576;k||(u=t);var r=this;r.Db(G=>{var I=G*u,K=(G+1)*u-1;K=Math.min(K,t-1);if("undefined"==typeof r.nb[G]){var Wa=r.nb;if(I>K)throw Error("invalid range ("+I+", "+K+") or no bytes requested!");if(K>t-1)throw Error("only "+t+" bytes available! programmer error!");var R=new XMLHttpRequest;R.open("GET",c,!1);t!==u&&R.setRequestHeader("Range","bytes="+I+"-"+K);R.responseType="arraybuffer";R.overrideMimeType&&R.overrideMimeType("text/plain; charset=x-user-defined");
R.send(null);if(!(200<=R.status&&300>R.status||304===R.status))throw Error("Couldn't load "+c+". Status: "+R.status);I=void 0!==R.response?new Uint8Array(R.response||[]):kb(R.responseText||"",!0);Wa[G]=I}if("undefined"==typeof r.nb[G])throw Error("doXHR failed!");return r.nb[G]});if(q||!t)u=t=1,u=t=this.Vb(0).length,oa("LazyFiles on gzip forces download of the whole file when length is accessed");this.dc=t;this.cc=u;this.Lb=!0};if("undefined"!=typeof XMLHttpRequest){if(!ha)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";
var g=new f;Object.defineProperties(g,{length:{get:function(){this.Lb||this.Qb();return this.dc}},chunkSize:{get:function(){this.Lb||this.Qb();return this.cc}}});var l=void 0}else l=c,g=void 0;var m=ic(a,b,d,e);g?m.jb=g:l&&(m.jb=null,m.url=l);Object.defineProperties(m,{lb:{get:function(){return this.jb.length}}});var n={};Object.keys(m.kb).forEach(q=>{var t=m.kb[q];n[q]=function(){jc(m);return t.apply(null,arguments)}});n.read=(q,t,v,k,u)=>{jc(m);q=q.node.jb;if(u>=q.length)t=0;else{k=Math.min(q.length-
u,k);if(q.slice)for(var r=0;r<k;r++)t[v+r]=q[u+r];else for(r=0;r<k;r++)t[v+r]=q.get(u+r);t=k}return t};n.Mb=()=>{jc(m);w();throw new H(48);};m.kb=n;return m}var Q={},Tb,bc;function lc(a,b){if("/"===b.charAt(0))return b;a=-100===a?fb:N(a).path;if(0==b.length)throw new H(44);return E(a+"/"+b)}var mc=void 0;function nc(){var a=A[+mc>>2];mc+=4;return a}
var oc,S=a=>{for(var b="";y[a];)b+=oc[y[a++]];return b},pc={},qc={},rc={},T,sc=a=>{throw new T(a);},tc,vc=(a,b)=>{function c(l){l=b(l);if(l.length!==d.length)throw new tc("Mismatched type converter count");for(var m=0;m<d.length;++m)uc(d[m],l[m])}var d=[];d.forEach(function(l){rc[l]=a});var e=Array(a.length),f=[],g=0;a.forEach((l,m)=>{qc.hasOwnProperty(l)?e[m]=qc[l]:(f.push(l),pc.hasOwnProperty(l)||(pc[l]=[]),pc[l].push(()=>{e[m]=qc[l];++g;g===f.length&&c(e)}))});0===f.length&&c(e)};
function wc(a,b,c={}){var d=b.name;if(!a)throw new T(`type "${d}" must have a positive integer typeid pointer`);if(qc.hasOwnProperty(a)){if(c.ic)return;throw new T(`Cannot register type '${d}' twice`);}qc[a]=b;delete rc[a];pc.hasOwnProperty(a)&&(b=pc[a],delete pc[a],b.forEach(e=>e()))}function uc(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");wc(a,b,c)}function xc(){this.qb=[void 0];this.Tb=[]}
var U=new xc,yc=a=>{a>=U.nb&&0===--U.get(a).$b&&U.Db(a)},zc=a=>{if(!a)throw new T("Cannot use deleted val. handle = "+a);return U.get(a).value},Ac=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:return U.Hb({$b:1,value:a})}};function Bc(a){return this.fromWireType(A[a>>2])}
var Cc=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(ua[c>>2])};case 8:return function(c){return this.fromWireType(va[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Dc=a=>{if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a},Ec=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Fc(a,b){a=Dc(a);return{[a]:function(){return b.apply(this,arguments)}}[a]}
function Gc(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=Fc(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
var Hc=(a,b)=>{if(void 0===h[a].tb){var c=h[a];h[a]=function(){if(!h[a].tb.hasOwnProperty(arguments.length))throw new T(`Function '${b}' called with an invalid number of arguments (${arguments.length}) - expects one of (${h[a].tb})!`);return h[a].tb[arguments.length].apply(this,arguments)};h[a].tb=[];h[a].tb[c.ec]=c}},Ic=(a,b,c)=>{if(h.hasOwnProperty(a)){if(void 0===c||void 0!==h[a].tb&&void 0!==h[a].tb[c])throw new T(`Cannot register public name '${a}' twice`);Hc(a,a);if(h.hasOwnProperty(c))throw new T(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
h[a].tb[c]=b}else h[a]=b,void 0!==c&&(h[a].Kc=c)},Jc=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(B[b+4*d>>2]);return c},Kc=[],Lc,V=a=>{var b=Kc[a];b||(a>=Kc.length&&(Kc.length=a+1),Kc[a]=b=Lc.get(a));return b},Mc=(a,b)=>{var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=h["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=V(b).apply(null,c);return d}},Nc=(a,b)=>{a=S(a);var c=a.includes("j")?Mc(a,b):V(b);if("function"!=typeof c)throw new T(`unknown function pointer with signature ${a}: ${b}`);
return c},Oc,Rc=a=>{a=Pc(a);var b=S(a);Qc(a);return b},Sc=(a,b)=>{function c(f){e[f]||qc[f]||(rc[f]?rc[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Oc(`${a}: `+d.map(Rc).join([", "]));},Tc=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?(")"==a[a.length-1]||w("Parentheses for argument names should match."),a.substr(0,b)):a},Uc=(a,b,c)=>{switch(b){case 1:return c?d=>x[d>>0]:d=>y[d>>0];case 2:return c?d=>z[d>>1]:d=>ta[d>>1];case 4:return c?d=>A[d>>2]:d=>B[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);
}};function Vc(a){return this.fromWireType(B[a>>2])}
var Wc="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Xc=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&ta[c];)++c;c<<=1;if(32<c-a&&Wc)return Wc.decode(y.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=z[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},Yc=(a,b,c)=>{void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)z[b>>1]=a.charCodeAt(e),b+=2;z[b>>1]=0;return b-d},Zc=a=>2*a.length,$c=(a,b)=>{for(var c=0,d="";!(c>=b/
4);){var e=A[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},ad=(a,b,c)=>{void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var g=a.charCodeAt(++e);f=65536+((f&1023)<<10)|g&1023}A[b>>2]=f;b+=4;if(b+4>c)break}A[b>>2]=0;return b-d},bd=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},cd={},
dd=a=>{var b=cd[a];return void 0===b?S(a):b},ed=[],fd=()=>"object"==typeof globalThis?globalThis:Function("return this")(),gd=a=>{var b=ed.length;ed.push(a);return b},hd=(a,b)=>{var c=qc[a];if(void 0===c)throw a=b+" has unknown type "+Rc(a),new T(a);return c},jd=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=hd(B[b+4*d>>2],"parameter "+d);return c},kd=a=>{for(var b="",c=0;c<a;++c)b+=(0!==c?", ":"")+"arg"+c;var d="return function emval_allocator_"+a+"(constructor, argTypes, args) {\n  var HEAPU32 = getMemory();\n";
for(c=0;c<a;++c)d+="var argType"+c+" = requireRegisteredType(HEAPU32[((argTypes)>>2)], 'parameter "+c+"');\nvar arg"+c+" = argType"+c+".readValueFromPointer(args);\nargs += argType"+c+"['argPackAdvance'];\nargTypes += 4;\n";return(new Function("requireRegisteredType","Module","valueToHandle","getMemory",d+("var obj = new constructor("+b+");\nreturn valueToHandle(obj);\n}\n")))(hd,h,Ac,()=>B)},ld={},md={},od=()=>{if(!nd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",
LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in md)void 0===md[b]?delete a[b]:a[b]=md[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);nd=c}return nd},nd,pd=a=>0===a%4&&(0!==a%100||0===a%400),qd=[31,29,31,30,31,30,31,31,30,31,30,31],rd=[31,28,31,30,31,30,31,31,30,31,30,31],sd=(a,b,c,d)=>{function e(k,u,r){for(k="number"==typeof k?k.toString():k||"";k.length<u;)k=r[0]+k;return k}function f(k,u){return e(k,
u,"0")}function g(k,u){function r(I){return 0>I?-1:0<I?1:0}var G;0===(G=r(k.getFullYear()-u.getFullYear()))&&0===(G=r(k.getMonth()-u.getMonth()))&&(G=r(k.getDate()-u.getDate()));return G}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-
1,11,30)}}function m(k){var u=k.Ab;for(k=new Date((new Date(k.Bb+1900,0,1)).getTime());0<u;){var r=k.getMonth(),G=(pd(k.getFullYear())?qd:rd)[r];if(u>G-k.getDate())u-=G-k.getDate()+1,k.setDate(1),11>r?k.setMonth(r+1):(k.setMonth(0),k.setFullYear(k.getFullYear()+1));else{k.setDate(k.getDate()+u);break}}r=new Date(k.getFullYear()+1,0,4);u=l(new Date(k.getFullYear(),0,4));r=l(r);return 0>=g(u,k)?0>=g(r,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var n=B[d+40>>2];d={zc:A[d>>2],yc:A[d+4>>2],
Jb:A[d+8>>2],Pb:A[d+12>>2],Kb:A[d+16>>2],Bb:A[d+20>>2],ub:A[d+24>>2],Ab:A[d+28>>2],Mc:A[d+32>>2],xc:A[d+36>>2],Ac:n?n?F(y,n):"":""};c=c?F(y,c):"";n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W",
"%Oy":"%y"};for(var q in n)c=c.replace(new RegExp(q,"g"),n[q]);var t="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),v="January February March April May June July August September October November December".split(" ");n={"%a":k=>t[k.ub].substring(0,3),"%A":k=>t[k.ub],"%b":k=>v[k.Kb].substring(0,3),"%B":k=>v[k.Kb],"%C":k=>f((k.Bb+1900)/100|0,2),"%d":k=>f(k.Pb,2),"%e":k=>e(k.Pb,2," "),"%g":k=>m(k).toString().substring(2),"%G":k=>m(k),"%H":k=>f(k.Jb,2),"%I":k=>{k=k.Jb;0==k?k=12:
12<k&&(k-=12);return f(k,2)},"%j":k=>{for(var u=0,r=0;r<=k.Kb-1;u+=(pd(k.Bb+1900)?qd:rd)[r++]);return f(k.Pb+u,3)},"%m":k=>f(k.Kb+1,2),"%M":k=>f(k.yc,2),"%n":()=>"\n","%p":k=>0<=k.Jb&&12>k.Jb?"AM":"PM","%S":k=>f(k.zc,2),"%t":()=>"\t","%u":k=>k.ub||7,"%U":k=>f(Math.floor((k.Ab+7-k.ub)/7),2),"%V":k=>{var u=Math.floor((k.Ab+7-(k.ub+6)%7)/7);2>=(k.ub+371-k.Ab-2)%7&&u++;if(u)53==u&&(r=(k.ub+371-k.Ab)%7,4==r||3==r&&pd(k.Bb)||(u=1));else{u=52;var r=(k.ub+7-k.Ab-1)%7;(4==r||5==r&&pd(k.Bb%400-1))&&u++}return f(u,
2)},"%w":k=>k.ub,"%W":k=>f(Math.floor((k.Ab+7-(k.ub+6)%7)/7),2),"%y":k=>(k.Bb+1900).toString().substring(2),"%Y":k=>k.Bb+1900,"%z":k=>{k=k.xc;var u=0<=k;k=Math.abs(k)/60;return(u?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":k=>k.Ac,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");for(q in n)c.includes(q)&&(c=c.replace(new RegExp(q,"g"),n[q](d)));c=c.replace(/\0\0/g,"%");q=kb(c,!1);if(q.length>b)return 0;x.set(q,a);return q.length-1};
function Nb(a,b,c,d){a||(a=this);this.parent=a;this.vb=a.vb;this.Eb=null;this.id=Fb++;this.name=b;this.mode=c;this.ib={};this.kb={};this.rdev=d}Object.defineProperties(Nb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},oc:{get:function(){return L(this.mode)}},nc:{get:function(){return 8192===(this.mode&61440)}}});fc();Gb=Array(4096);
Ub(J,"/");O("/tmp");O("/home");O("/home/web_user");(function(){O("/dev");nb(259,{read:()=>0,write:(d,e,f,g)=>g});Wb("/dev/null",259);mb(1280,pb);mb(1536,qb);Wb("/dev/tty",1280);Wb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=db(a).byteLength);return a[--b]};P("/dev","random",c);P("/dev","urandom",c);O("/dev/shm");O("/dev/shm/tmp")})();
(function(){O("/proc");var a=O("/proc/self");O("/proc/self/fd");Ub({vb(){var b=tb(a,"fd",16895,73);b.ib={lookup(c,d){var e=N(+d);c={parent:null,vb:{Yb:"fake"},ib:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();h.FS_createPath=hc;h.FS_createDataFile=zb;h.FS_createPreloadedFile=Ab;h.FS_unlink=Zb;h.FS_createLazyFile=kc;h.FS_createDevice=P;for(var td=Array(256),ud=0;256>ud;++ud)td[ud]=String.fromCharCode(ud);oc=td;
T=h.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};tc=h.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};Object.assign(xc.prototype,{get(a){return this.qb[a]},has(a){return void 0!==this.qb[a]},Hb(a){var b=this.Tb.pop()||this.qb.length;this.qb[b]=a;return b},Db(a){this.qb[a]=void 0;this.Tb.push(a)}});U.qb.push({value:void 0},{value:null},{value:!0},{value:!1});U.nb=U.qb.length;
h.count_emval_handles=()=>{for(var a=0,b=U.nb;b<U.qb.length;++b)void 0!==U.qb[b]&&++a;return a};Oc=h.UnboundTypeError=((a,b)=>{var c=Fc(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
var de={o:a=>{a=new Ua(a);a.rc()||(a.ac(!0),Sa--);a.bc(!1);Ra.push(a);vd(a.Gb);return a.sc()},t:()=>{W(0,0);var a=Ra.pop();wd(a.Gb);Ta=0},b:()=>Za([]),h:a=>Za([a]),R:(a,b)=>Za([a,b]),v:(a,b,c)=>Za([a,b,c]),K:()=>{var a=Ra.pop();a||w("no exception to throw");var b=a.Gb;a.hc()||(Ra.push(a),a.bc(!0),a.ac(!1),Sa++);Ta=b;throw Ta;},a:(a,b,c)=>{(new Ua(a)).Wb(b,c);Ta=a;Sa++;throw Ta;},ba:()=>Sa,e:a=>{Ta||(Ta=a);throw Ta;},na:function(a){try{a=a?F(y,a):"";var b=M(a,{Cb:!0});if(null===b.node)throw new H(44);
if(!L(b.node.mode))throw new H(54);var c=Mb(b.node,"x");if(c)throw new H(c);fb=b.path;return 0}catch(d){if("undefined"==typeof Q||"ErrnoError"!==d.name)throw d;return-d.mb}},ma:function(a){try{var b=N(a);return Sb(b).fd}catch(c){if("undefined"==typeof Q||"ErrnoError"!==c.name)throw c;return-c.mb}},O:function(a,b,c){mc=c;try{var d=N(a);switch(b){case 0:var e=nc();if(0>e)return-28;for(;Eb[e];)e++;return Sb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=nc(),d.flags|=e,0;case 5:return e=
nc(),z[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return A[xd()>>2]=28,-1;default:return-28}}catch(f){if("undefined"==typeof Q||"ErrnoError"!==f.name)throw f;return-f.mb}},ka:function(a,b){try{if(0===b)return-28;var c=fb,d=ib(c)+1;if(b<d)return-68;jb(c,y,a,b);return d}catch(e){if("undefined"==typeof Q||"ErrnoError"!==e.name)throw e;return-e.mb}},ga:function(a,b,c){try{var d=N(a);if(!d.yb){var e=M(d.path,{Cb:!0}).node;if(!e.ib.readdir)throw new H(54);var f=e.ib.readdir(e);d.yb=
f}a=0;for(var g=dc(d,0,1),l=Math.floor(g/280);l<d.yb.length&&a+280<=c;){var m=d.yb[l];if("."===m){var n=d.node.id;var q=4}else if(".."===m)n=M(d.path,{parent:!0}).node.id,q=4;else{var t=vb(d.node,m);n=t.id;q=8192===(t.mode&61440)?2:L(t.mode)?4:40960===(t.mode&61440)?10:8}D=[n>>>0,(C=n,1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];A[b+a>>2]=D[0];A[b+a+4>>2]=D[1];D=[280*(l+1)>>>0,(C=280*(l+1),1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-
+(~~C>>>0))/4294967296)>>>0:0)];A[b+a+8>>2]=D[0];A[b+a+12>>2]=D[1];z[b+a+16>>1]=280;x[b+a+18>>0]=q;jb(m,y,b+a+19,256);a+=280;l+=1}dc(d,280*l,0);return a}catch(v){if("undefined"==typeof Q||"ErrnoError"!==v.name)throw v;return-v.mb}},pa:function(a,b,c){mc=c;try{var d=N(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.wb.kc){b=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=nc();A[e>>2]=25856;A[e+4>>2]=5;A[e+8>>2]=191;A[e+12>>2]=35387;
for(var f=0;32>f;f++)x[e+f+17>>0]=b[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.wb.lc)for(e=nc(),b=[],f=0;32>f;f++)b.push(x[e+f+17>>0]);return 0;case 21519:if(!d.tty)return-59;e=nc();return A[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:e=nc();if(!d.kb.jc)throw new H(59);return d.kb.jc(d,b,e);case 21523:if(!d.tty)return-59;d.tty.wb.mc&&(f=[24,80],e=nc(),z[e>>1]=f[0],z[e+2>>1]=f[1]);return 0;case 21524:return d.tty?
0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if("undefined"==typeof Q||"ErrnoError"!==g.name)throw g;return-g.mb}},ha:function(a,b,c){try{return b=b?F(y,b):"",b=lc(a,b),b=E(b),"/"===b[b.length-1]&&(b=b.substr(0,b.length-1)),O(b,c),0}catch(d){if("undefined"==typeof Q||"ErrnoError"!==d.name)throw d;return-d.mb}},M:function(a,b,c,d){mc=d;try{b=b?F(y,b):"";b=lc(a,b);var e=d?nc():0;return ac(b,c,e).fd}catch(f){if("undefined"==typeof Q||"ErrnoError"!==f.name)throw f;return-f.mb}},fa:function(a,
b,c,d){try{b=b?F(y,b):"";b=lc(a,b);if(0>=d)return-28;var e=Ib(b),f=Math.min(d,ib(e)),g=x[c+f];jb(e,y,c,d+1);x[c+f]=g;return f}catch(l){if("undefined"==typeof Q||"ErrnoError"!==l.name)throw l;return-l.mb}},L:function(a){try{return a=a?F(y,a):"",Yb(a),0}catch(b){if("undefined"==typeof Q||"ErrnoError"!==b.name)throw b;return-b.mb}},da:function(a,b){try{a=a?F(y,a):"";a:{try{var c=M(a,{Cb:!0}).node;if(!c)throw new H(44);if(!c.ib.rb)throw new H(63);var d=c.ib.rb(c)}catch(m){if(m&&m.node&&E(a)!==E(Jb(m.node))){var e=
-54;break a}throw m;}A[b>>2]=d.dev;A[b+4>>2]=d.mode;B[b+8>>2]=d.nlink;A[b+12>>2]=d.uid;A[b+16>>2]=d.gid;A[b+20>>2]=d.rdev;D=[d.size>>>0,(C=d.size,1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];A[b+24>>2]=D[0];A[b+28>>2]=D[1];A[b+32>>2]=4096;A[b+36>>2]=d.blocks;var f=d.atime.getTime(),g=d.mtime.getTime(),l=d.ctime.getTime();D=[Math.floor(f/1E3)>>>0,(C=Math.floor(f/1E3),1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>
0:0)];A[b+40>>2]=D[0];A[b+44>>2]=D[1];B[b+48>>2]=f%1E3*1E3;D=[Math.floor(g/1E3)>>>0,(C=Math.floor(g/1E3),1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];A[b+56>>2]=D[0];A[b+60>>2]=D[1];B[b+64>>2]=g%1E3*1E3;D=[Math.floor(l/1E3)>>>0,(C=Math.floor(l/1E3),1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];A[b+72>>2]=D[0];A[b+76>>2]=D[1];B[b+80>>2]=l%1E3*1E3;D=[d.ino>>>0,(C=d.ino,1<=+Math.abs(C)?0<C?+Math.floor(C/
4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];A[b+88>>2]=D[0];A[b+92>>2]=D[1];e=0}return e}catch(m){if("undefined"==typeof Q||"ErrnoError"!==m.name)throw m;return-m.mb}},ea:function(a,b,c){try{return b=b?F(y,b):"",b=lc(a,b),0===c?Zb(b):512===c?Yb(b):w("Invalid flags passed to unlinkat"),0}catch(d){if("undefined"==typeof Q||"ErrnoError"!==d.name)throw d;return-d.mb}},X:()=>{},ra:(a,b,c,d)=>{b=S(b);uc(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,f){return f?
c:d},argPackAdvance:8,readValueFromPointer:function(e){return this.fromWireType(y[e])},xb:null})},qa:(a,b)=>{b=S(b);uc(a,{name:b,fromWireType:c=>{var d=zc(c);yc(c);return d},toWireType:(c,d)=>Ac(d),argPackAdvance:8,readValueFromPointer:Bc,xb:null})},Q:(a,b,c)=>{b=S(b);uc(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,argPackAdvance:8,readValueFromPointer:Cc(b,c),xb:null})},q:(a,b,c,d,e,f,g)=>{var l=Jc(b,c);a=S(a);a=Tc(a);e=Nc(d,e);Ic(a,function(){Sc(`Cannot call ${a} due to unbound types`,l)},b-
1);vc(l,function(m){var n=[m[0],null].concat(m.slice(1)),q=m=a,t=e,v=n.length;if(2>v)throw new T("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var k=null!==n[1]&&!1,u=!1,r=1;r<n.length;++r)if(null!==n[r]&&void 0===n[r].xb){u=!0;break}var G="void"!==n[0].name,I="",K="";for(r=0;r<v-2;++r)I+=(0!==r?", ":"")+"arg"+r,K+=(0!==r?", ":"")+"arg"+r+"Wired";q=`\n        return function ${Dc(q)}(${I}) {\n        if (arguments.length !== ${v-2}) {\n          throwBindingError('function ${q} called with ' + arguments.length + ' arguments, expected ${v-
2}');\n        }`;u&&(q+="var destructors = [];\n");var Wa=u?"destructors":"null";I="throwBindingError invoker fn runDestructors retType classParam".split(" ");t=[sc,t,f,Ec,n[0],n[1]];k&&(q+="var thisWired = classParam.toWireType("+Wa+", this);\n");for(r=0;r<v-2;++r)q+="var arg"+r+"Wired = argType"+r+".toWireType("+Wa+", arg"+r+"); // "+n[r+2].name+"\n",I.push("argType"+r),t.push(n[r+2]);k&&(K="thisWired"+(0<K.length?", ":"")+K);q+=(G||g?"var rv = ":"")+"invoker(fn"+(0<K.length?", ":"")+K+");\n";
if(u)q+="runDestructors(destructors);\n";else for(r=k?1:2;r<n.length;++r)v=1===r?"thisWired":"arg"+(r-2)+"Wired",null!==n[r].xb&&(q+=v+"_dtor("+v+"); // "+n[r].name+"\n",I.push(v+"_dtor"),t.push(n[r].xb));G&&(q+="var ret = retType.fromWireType(rv);\nreturn ret;\n");I.push(q+"}\n");n=Gc(I).apply(null,t);r=b-1;if(!h.hasOwnProperty(m))throw new tc("Replacing nonexistant public symbol");void 0!==h[m].tb&&void 0!==r?h[m].tb[r]=n:(h[m]=n,h[m].ec=r);return[]})},w:(a,b,c,d,e)=>{b=S(b);-1===e&&(e=4294967295);
e=l=>l;if(0===d){var f=32-8*c;e=l=>l<<f>>>f}var g=b.includes("unsigned")?function(l,m){return m>>>0}:function(l,m){return m};uc(a,{name:b,fromWireType:e,toWireType:g,argPackAdvance:8,readValueFromPointer:Uc(b,c,0!==d),xb:null})},s:(a,b,c)=>{function d(f){return new e(x.buffer,B[f+4>>2],B[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=S(c);uc(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{ic:!0})},P:(a,b)=>{b=S(b);
var c="std::string"===b;uc(a,{name:b,fromWireType:function(d){var e=B[d>>2],f=d+4;if(c)for(var g=f,l=0;l<=e;++l){var m=f+l;if(l==e||0==y[m]){g=g?F(y,g,m-g):"";if(void 0===n)var n=g;else n+=String.fromCharCode(0),n+=g;g=m+1}}else{n=Array(e);for(l=0;l<e;++l)n[l]=String.fromCharCode(y[f+l]);n=n.join("")}Qc(d);return n},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"==typeof e;if(!(f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array))throw new T("Cannot pass non-string to std::string");
var g=c&&f?ib(e):e.length;var l=yd(4+g+1),m=l+4;B[l>>2]=g;if(c&&f)jb(e,y,m,g+1);else if(f)for(f=0;f<g;++f){var n=e.charCodeAt(f);if(255<n)throw Qc(m),new T("String has UTF-16 code units that do not fit in 8 bits");y[m+f]=n}else for(f=0;f<g;++f)y[m+f]=e[f];null!==d&&d.push(Qc,l);return l},argPackAdvance:8,readValueFromPointer:Vc,xb(d){Qc(d)}})},G:(a,b,c)=>{c=S(c);if(2===b){var d=Xc;var e=Yc;var f=Zc;var g=()=>ta;var l=1}else 4===b&&(d=$c,e=ad,f=bd,g=()=>B,l=2);uc(a,{name:c,fromWireType:m=>{for(var n=
B[m>>2],q=g(),t,v=m+4,k=0;k<=n;++k){var u=m+4+k*b;if(k==n||0==q[u>>l])v=d(v,u-v),void 0===t?t=v:(t+=String.fromCharCode(0),t+=v),v=u+b}Qc(m);return t},toWireType:(m,n)=>{if("string"!=typeof n)throw new T(`Cannot pass non-string to C++ string type ${c}`);var q=f(n),t=yd(4+q+b);B[t>>2]=q>>l;e(n,t+4,q+b);null!==m&&m.push(Qc,t);return t},argPackAdvance:8,readValueFromPointer:Bc,xb(m){Qc(m)}})},sa:(a,b)=>{b=S(b);uc(a,{pc:!0,name:b,argPackAdvance:0,fromWireType:()=>{},toWireType:()=>{}})},Aa:(a,b,c,d,e)=>
{a=ed[a];b=zc(b);c=dd(c);var f=[];a=a(b,c,f,e);f.length&&(B[d>>2]=Ac(f));return a},xa:yc,Da:a=>{if(0===a)return Ac(fd());a=dd(a);return Ac(fd()[a])},Ba:(a,b)=>{b=jd(a,b);var c=b.shift();a--;for(var d=["retType"],e=[c],f="",g=0;g<a;++g)f+=(0!==g?", ":"")+"arg"+g,d.push("argType"+g),e.push(b[g]);g=c.name+"_$"+b.map(n=>n.name).join("_")+"$";var l="return function "+Dc("methodCaller_"+g)+"(handle, name, destructors, args) {\n",m=0;for(g=0;g<a;++g)l+="    var arg"+g+" = argType"+g+".readValueFromPointer(args"+
(m?"+"+m:"")+");\n",m+=b[g].argPackAdvance;l+="    var rv = handle[name]("+f+");\n";for(g=0;g<a;++g)b[g].deleteObject&&(l+="    argType"+g+".deleteObject(arg"+g+");\n");c.pc||(l+="    return retType.toWireType(destructors, rv);\n");d.push(l+"};\n");a=Gc(d).apply(null,e);return gd(a)},ua:a=>{4<a&&(U.get(a).$b+=1)},Ca:(a,b,c,d)=>{a=zc(a);var e=ld[b];e||(e=kd(b),ld[b]=e);return e(a,c,d)},A:a=>Ac(dd(a)),B:()=>Ac({}),ya:a=>{var b=zc(a);Ec(b);yc(a)},va:(a,b,c)=>{a=zc(a);b=zc(b);c=zc(c);a[b]=c},wa:(a,b)=>
{a=hd(a,"_emval_take_value");a=a.readValueFromPointer(b);return Ac(a)},F:()=>{w("")},la:(a,b,c)=>y.copyWithin(a,b,b+c),ca:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-ra.buffer.byteLength+65535)/65536;try{ra.grow(e);wa();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},ia:(a,b)=>{var c=0;od().forEach((d,e)=>{var f=b+c;e=B[a+4*e>>2]=f;for(f=
0;f<d.length;++f)x[e++>>0]=d.charCodeAt(f);x[e>>0]=0;c+=d.length+1});return 0},ja:(a,b)=>{var c=od();B[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);B[b>>2]=d;return 0},ta:a=>{if(!Qa){zd();Pa(za);gc=!1;Ad(0);for(var b=0;b<Eb.length;b++){var c=Eb[b];c&&cc(c)}}if(!Qa){if(h.onExit)h.onExit(a);sa=!0}ea(a,new Oa(a))},E:function(a){try{var b=N(a);cc(b);return 0}catch(c){if("undefined"==typeof Q||"ErrnoError"!==c.name)throw c;return c.mb}},oa:function(a,b,c,d){try{a:{var e=N(a);a=b;for(var f,g=b=0;g<
c;g++){var l=B[a>>2],m=B[a+4>>2];a+=8;var n=e,q=l,t=m,v=f,k=x;if(0>t||0>v)throw new H(28);if(null===n.fd)throw new H(8);if(1===(n.flags&2097155))throw new H(8);if(L(n.node.mode))throw new H(31);if(!n.kb.read)throw new H(28);var u="undefined"!=typeof v;if(!u)v=n.position;else if(!n.seekable)throw new H(70);var r=n.kb.read(n,k,q,t,v);u||(n.position+=r);var G=r;if(0>G){var I=-1;break a}b+=G;if(G<m)break;"undefined"!==typeof f&&(f+=G)}I=b}B[d>>2]=I;return 0}catch(K){if("undefined"==typeof Q||"ErrnoError"!==
K.name)throw K;return K.mb}},W:function(a,b,c,d,e){b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;try{if(isNaN(b))return 61;var f=N(a);dc(f,b,d);D=[f.position>>>0,(C=f.position,1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];A[e>>2]=D[0];A[e+4>>2]=D[1];f.yb&&0===b&&0===d&&(f.yb=null);return 0}catch(g){if("undefined"==typeof Q||"ErrnoError"!==g.name)throw g;return g.mb}},N:function(a,b,c,d){try{a:{var e=N(a);a=b;for(var f,g=b=0;g<c;g++){var l=
B[a>>2],m=B[a+4>>2];a+=8;var n=ec(e,x,l,m,f);if(0>n){var q=-1;break a}b+=n;"undefined"!==typeof f&&(f+=n)}q=b}B[d>>2]=q;return 0}catch(t){if("undefined"==typeof Q||"ErrnoError"!==t.name)throw t;return t.mb}},I:Bd,za:Cd,J:Dd,p:Ed,d:Fd,c:Gd,f:Hd,l:Id,n:Jd,r:Kd,H:Ld,D:Md,U:Nd,Z:Od,$:Pd,_:Qd,Y:Rd,T:Sd,j:Td,k:Ud,g:Vd,i:Wd,m:Xd,z:Yd,S:Zd,u:$d,y:ae,C:be,V:ce,x:a=>a,aa:(a,b,c,d)=>sd(a,b,c,d)},X=function(){function a(c){X=c.exports;ra=X.Ea;wa();Lc=X.Ha;ya.unshift(X.Fa);Ga("wasm-instantiate");return X}var b=
{a:de};Fa("wasm-instantiate");if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){pa(`Module.instantiateWasm callback failed with error: ${c}`),ba(c)}Na(b,function(c){a(c.instance)}).catch(ba);return{}}(),yd=a=>(yd=X.Ga)(a),Qc=a=>(Qc=X.Ia)(a),xd=()=>(xd=X.Ja)(),Pc=a=>(Pc=X.Ka)(a);h.__embind_initialize_bindings=()=>(h.__embind_initialize_bindings=X.La)();
var zd=()=>(zd=X.Ma)(),Ad=h._fflush=a=>(Ad=h._fflush=X.Na)(a),W=(a,b)=>(W=X.Oa)(a,b),Xa=a=>(Xa=X.Pa)(a),Y=()=>(Y=X.Qa)(),Z=a=>(Z=X.Ra)(a),wd=a=>(wd=X.Sa)(a),vd=a=>(vd=X.Ta)(a),Ya=(a,b,c)=>(Ya=X.Ua)(a,b,c),Va=a=>(Va=X.Va)(a),ee=h.dynCall_iiji=(a,b,c,d,e)=>(ee=h.dynCall_iiji=X.Wa)(a,b,c,d,e),fe=h.dynCall_ji=(a,b)=>(fe=h.dynCall_ji=X.Xa)(a,b),ge=h.dynCall_iij=(a,b,c,d)=>(ge=h.dynCall_iij=X.Ya)(a,b,c,d),he=h.dynCall_jii=(a,b,c)=>(he=h.dynCall_jii=X.Za)(a,b,c);
h.dynCall_iiiji=(a,b,c,d,e,f)=>(h.dynCall_iiiji=X._a)(a,b,c,d,e,f);h.dynCall_iiiijj=(a,b,c,d,e,f,g,l)=>(h.dynCall_iiiijj=X.$a)(a,b,c,d,e,f,g,l);h.dynCall_viiiiiiijj=(a,b,c,d,e,f,g,l,m,n,q,t)=>(h.dynCall_viiiiiiijj=X.ab)(a,b,c,d,e,f,g,l,m,n,q,t);h.dynCall_jiii=(a,b,c,d)=>(h.dynCall_jiii=X.bb)(a,b,c,d);h.dynCall_jiji=(a,b,c,d,e)=>(h.dynCall_jiji=X.cb)(a,b,c,d,e);
var ie=h.dynCall_viijii=(a,b,c,d,e,f,g)=>(ie=h.dynCall_viijii=X.db)(a,b,c,d,e,f,g),je=h.dynCall_iiiiij=(a,b,c,d,e,f,g)=>(je=h.dynCall_iiiiij=X.eb)(a,b,c,d,e,f,g),ke=h.dynCall_jiiii=(a,b,c,d,e)=>(ke=h.dynCall_jiiii=X.fb)(a,b,c,d,e);h.dynCall_iiiiijj=(a,b,c,d,e,f,g,l,m)=>(h.dynCall_iiiiijj=X.gb)(a,b,c,d,e,f,g,l,m);h.dynCall_iiiiiijj=(a,b,c,d,e,f,g,l,m,n)=>(h.dynCall_iiiiiijj=X.hb)(a,b,c,d,e,f,g,l,m,n);h.___start_em_js=624536;h.___stop_em_js=624795;
function Gd(a,b,c){var d=Y();try{return V(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;W(1,0)}}function Fd(a,b){var c=Y();try{return V(a)(b)}catch(d){Z(c);if(d!==d+0)throw d;W(1,0)}}function Jd(a,b,c,d,e,f){var g=Y();try{return V(a)(b,c,d,e,f)}catch(l){Z(g);if(l!==l+0)throw l;W(1,0)}}function Ud(a,b){var c=Y();try{V(a)(b)}catch(d){Z(c);if(d!==d+0)throw d;W(1,0)}}function Td(a){var b=Y();try{V(a)()}catch(c){Z(b);if(c!==c+0)throw c;W(1,0)}}
function Hd(a,b,c,d){var e=Y();try{return V(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}function Vd(a,b,c){var d=Y();try{V(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;W(1,0)}}function Wd(a,b,c,d){var e=Y();try{V(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}function Xd(a,b,c,d,e){var f=Y();try{V(a)(b,c,d,e)}catch(g){Z(f);if(g!==g+0)throw g;W(1,0)}}function Id(a,b,c,d,e){var f=Y();try{return V(a)(b,c,d,e)}catch(g){Z(f);if(g!==g+0)throw g;W(1,0)}}
function Cd(a,b,c,d,e,f){var g=Y();try{return V(a)(b,c,d,e,f)}catch(l){Z(g);if(l!==l+0)throw l;W(1,0)}}function Ld(a,b,c,d,e,f,g,l){var m=Y();try{return V(a)(b,c,d,e,f,g,l)}catch(n){Z(m);if(n!==n+0)throw n;W(1,0)}}function Ed(a){var b=Y();try{return V(a)()}catch(c){Z(b);if(c!==c+0)throw c;W(1,0)}}function Kd(a,b,c,d,e,f,g){var l=Y();try{return V(a)(b,c,d,e,f,g)}catch(m){Z(l);if(m!==m+0)throw m;W(1,0)}}
function Yd(a,b,c,d,e,f){var g=Y();try{V(a)(b,c,d,e,f)}catch(l){Z(g);if(l!==l+0)throw l;W(1,0)}}function Zd(a,b,c,d,e,f,g){var l=Y();try{V(a)(b,c,d,e,f,g)}catch(m){Z(l);if(m!==m+0)throw m;W(1,0)}}function Dd(a,b,c,d){var e=Y();try{return V(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}function Bd(a,b,c,d){var e=Y();try{return V(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}function $d(a,b,c,d,e,f,g,l){var m=Y();try{V(a)(b,c,d,e,f,g,l)}catch(n){Z(m);if(n!==n+0)throw n;W(1,0)}}
function Md(a,b,c,d,e,f,g,l,m,n,q,t){var v=Y();try{return V(a)(b,c,d,e,f,g,l,m,n,q,t)}catch(k){Z(v);if(k!==k+0)throw k;W(1,0)}}function ae(a,b,c,d,e,f,g,l,m,n,q){var t=Y();try{V(a)(b,c,d,e,f,g,l,m,n,q)}catch(v){Z(t);if(v!==v+0)throw v;W(1,0)}}function be(a,b,c,d,e,f,g,l,m,n,q,t,v,k,u,r){var G=Y();try{V(a)(b,c,d,e,f,g,l,m,n,q,t,v,k,u,r)}catch(I){Z(G);if(I!==I+0)throw I;W(1,0)}}function Pd(a,b,c,d,e){var f=Y();try{return ee(a,b,c,d,e)}catch(g){Z(f);if(g!==g+0)throw g;W(1,0)}}
function Qd(a,b){var c=Y();try{return fe(a,b)}catch(d){Z(c);if(d!==d+0)throw d;W(1,0)}}function Od(a,b,c,d){var e=Y();try{return ge(a,b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}function Rd(a,b,c){var d=Y();try{return he(a,b,c)}catch(e){Z(d);if(e!==e+0)throw e;W(1,0)}}function ce(a,b,c,d,e,f,g){var l=Y();try{ie(a,b,c,d,e,f,g)}catch(m){Z(l);if(m!==m+0)throw m;W(1,0)}}function Nd(a,b,c,d,e,f,g){var l=Y();try{return je(a,b,c,d,e,f,g)}catch(m){Z(l);if(m!==m+0)throw m;W(1,0)}}
function Sd(a,b,c,d,e){var f=Y();try{return ke(a,b,c,d,e)}catch(g){Z(f);if(g!==g+0)throw g;W(1,0)}}h.addRunDependency=Fa;h.removeRunDependency=Ga;h.FS_createPath=hc;h.FS_createLazyFile=kc;h.FS_createDevice=P;h.FS_createPreloadedFile=Ab;h.FS_createDataFile=zb;h.FS_unlink=Zb;var le;Ea=function me(){le||ne();le||(Ea=me)};
function ne(){function a(){if(!le&&(le=!0,h.calledRun=!0,!sa)){h.noFSInit||gc||(gc=!0,fc(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?P("/dev","stdin",h.stdin):Xb("/dev/tty","/dev/stdin"),h.stdout?P("/dev","stdout",null,h.stdout):Xb("/dev/tty","/dev/stdout"),h.stderr?P("/dev","stderr",null,h.stderr):Xb("/dev/tty1","/dev/stderr"),ac("/dev/stdin",0),ac("/dev/stdout",1),ac("/dev/stderr",1));Hb=!1;Pa(ya);aa(h);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(h.postRun)for("function"==
typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var b=h.postRun.shift();Aa.unshift(b)}Pa(Aa)}}if(!(0<Ca)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ba();Pa(xa);0<Ca||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);a()},1)):a())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();ne();


  return moduleArg.ready
}

);
})();
export default Module;