
var Module = (() => {
  var _scriptDir = import.meta.url;
  
  return (
async function(moduleArg = {}) {

var h=moduleArg,aa,ba;h.ready=new Promise((a,b)=>{aa=a;ba=b});h.Rc=!0;h.Sc=!0;
"object"!==typeof WebAssembly&&"undefined"!==typeof WXWebAssembly&&(WXWebAssembly.RuntimeError=WXWebAssembly.RuntimeError||function(){class a extends Error{constructor(b){super(b);this instanceof a||(b=Object.setPrototypeOf,"function"===typeof b?b.call(Object,this,a.prototype):this.__proto__=a.prototype,"function"===typeof Error.captureStackTrace&&Error.captureStackTrace(this,a))}}Object.defineProperty(a.prototype,"name",{configurable:!0,writable:!0,value:"RuntimeError"});return a}(),function(){if("undefined"!==
typeof globalThis)return globalThis;var a=function(){return this}(),b=function(){try{var c=new Function}catch(d){return!1}return"function"===typeof c}();if(!a&&b)try{a=(new Function("return this"))()}catch(c){}if(!a){if("undefined"===typeof __webpack_public_path__&&"undefined"!==typeof global)return global;if("undefined"!==typeof window)return window;if("undefined"!==typeof self)return self}return a}().WebAssembly=WXWebAssembly);
var ca=Object.assign({},h),da="./this.program",ea="object"==typeof window,fa="function"==typeof importScripts,ha="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,p="",ia,ja,ka;
if(ha){const {createRequire:a}=await import("module");var require=a(import.meta.url),fs=require("fs"),la=require("path");fa?p=la.dirname(p)+"/":p=require("url").fileURLToPath(new URL("./",import.meta.url));ia=(b,c)=>{b=ma(b)?new URL(b):la.normalize(b);return fs.readFileSync(b,c?void 0:"utf8")};ka=b=>{b=ia(b,!0);b.buffer||(b=new Uint8Array(b));return b};ja=(b,c,d,e=!0)=>{b=ma(b)?new URL(b):la.normalize(b);fs.readFile(b,e?void 0:"utf8",(f,g)=>{f?d(f):c(e?g.buffer:g)})};
!h.thisProgram&&1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);h.inspect=()=>"[Emscripten Module object]"}else if(ea||fa)fa?p=self.location.href:"undefined"!=typeof document&&document.currentScript&&(p=document.currentScript.src),_scriptDir&&(p=_scriptDir),0!==p.indexOf("blob:")?p=p.substr(0,p.replace(/[?#].*/,"").lastIndexOf("/")+1):p="",ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},fa&&(ka=a=>{var b=new XMLHttpRequest;
b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ja=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var na=h.print||console.log.bind(console),oa=h.printErr||console.error.bind(console);Object.assign(h,ca);ca=null;h.thisProgram&&(da=h.thisProgram);var pa;h.wasmBinary&&(pa=h.wasmBinary);"object"!=typeof WebAssembly&&r("no native wasm support detected");
var qa,ra=!1,w,y,sa,ta,z,A,ua,va;function wa(){var a=qa.buffer;h.HEAP8=w=new Int8Array(a);h.HEAP16=sa=new Int16Array(a);h.HEAPU8=y=new Uint8Array(a);h.HEAPU16=ta=new Uint16Array(a);h.HEAP32=z=new Int32Array(a);h.HEAPU32=A=new Uint32Array(a);h.HEAPF32=ua=new Float32Array(a);h.HEAPF64=va=new Float64Array(a)}var xa=[],ya=[],za=[];function Aa(){var a=h.preRun.shift();xa.unshift(a)}var Ba=0,Ca=null,Da=null;function Ea(){Ba++;h.monitorRunDependencies&&h.monitorRunDependencies(Ba)}
function Fa(){Ba--;h.monitorRunDependencies&&h.monitorRunDependencies(Ba);if(0==Ba&&(null!==Ca&&(clearInterval(Ca),Ca=null),Da)){var a=Da;Da=null;a()}}function r(a){if(h.onAbort)h.onAbort(a);a="Aborted("+a+")";oa(a);ra=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}var Ga=a=>a.startsWith("data:application/octet-stream;base64,"),ma=a=>a.startsWith("file://"),Ha;
if(h.locateFile){if(Ha="cfb2ooxml.wasm?version=1.0.0",!Ga(Ha)){var Ia=Ha;Ha=h.locateFile?h.locateFile(Ia,p):p+Ia}}else Ha=(new URL("cfb2ooxml.wasm?version=1.0.0",import.meta.url)).href;function Ja(a){if(a==Ha&&pa)return new Uint8Array(pa);if(ka)return ka(a);throw"both async and sync fetching of the wasm failed";}
function Ka(a){if(!pa&&(ea||fa)){if("function"==typeof fetch&&!ma(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Ja(a));if(ja)return new Promise((b,c)=>{ja(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Ja(a))}function La(a,b,c){return Ka(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{oa(`failed to asynchronously prepare wasm: ${d}`);r(d)})}
function Ma(a,b){var c=Ha;return pa||"function"!=typeof WebAssembly.instantiateStreaming||Ga(c)||ma(c)||ha||"function"!=typeof fetch?La(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){oa(`wasm streaming compile failed: ${e}`);oa("falling back to ArrayBuffer instantiation");return La(c,a,b)}))}
var B,C,Na={760224:(a,b)=>{var c=a?D(y,a):"",d=null;"undefined"!==typeof OffscreenCanvas?d=new OffscreenCanvas(1,1):d="undefined"!==typeof document?document.createElement("canvas"):null;a=0;if(d){d=d.getContext("2d");d.font=b+"px "+c;for(c=0;10>c;c++)a=Math.max(a,d.measureText(c.toString()).width);a=a/b*1E3}return a}},Oa=a=>{for(;0<a.length;)a.shift()(h)},Pa=[],Qa=0,Ra=0;
function Sa(a){this.Pb=a;this.yb=a-24;this.Jc=function(b){A[this.yb+4>>2]=b};this.wb=function(){return A[this.yb+4>>2]};this.Ic=function(b){A[this.yb+8>>2]=b};this.kc=function(b){w[this.yb+12>>0]=b?1:0};this.Fc=function(){return 0!=w[this.yb+12>>0]};this.lc=function(b){w[this.yb+13>>0]=b?1:0};this.qc=function(){return 0!=w[this.yb+13>>0]};this.ec=function(b,c){this.Ob(0);this.Jc(b);this.Ic(c)};this.Ob=function(b){A[this.yb+16>>2]=b};this.Ac=function(){return A[this.yb+16>>2]};this.Hc=function(){if(Ta(this.wb()))return A[this.Pb>>
2];var b=this.Ac();return 0!==b?b:this.Pb}}
var Xa=a=>{var b=Ra;if(!b)return Ua(0),0;var c=new Sa(b);c.Ob(b);var d=c.wb();if(!d)return Ua(0),b;for(var e in a){var f=a[e];if(0===f||f===d)break;if(Va(f,d,c.yb+16))return Ua(f),b}Ua(d);return b},Ya=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},E=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Ya(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?
"/":"")+a},Za=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},$a=a=>{if("/"===a)return"/";a=E(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},ab=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(ha)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;
return c=>(c.set(b(c.byteLength)),c)}catch(c){}r("initRandomDevice")},bb=a=>(bb=ab())(a);function cb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ya(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}
var db="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,D=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&db)return db.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
eb=[],fb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},gb=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&
63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e};function hb(a,b){var c=Array(fb(a)+1);a=gb(a,c,0,c.length);b&&(c.length=a);return c}var ib=[];function jb(a,b){ib[a]={input:[],output:[],Fb:b};kb(a,lb)}
var lb={open(a){var b=ib[a.node.rdev];if(!b)throw new F(43);a.tty=b;a.seekable=!1},close(a){a.tty.Fb.fsync(a.tty)},fsync(a){a.tty.Fb.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Fb.cc)throw new F(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.Fb.cc(a.tty)}catch(l){throw new F(29);}if(void 0===g&&0===e)throw new F(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Fb.Wb)throw new F(60);try{for(var e=0;e<d;e++)a.tty.Fb.Wb(a.tty,b[c+
e])}catch(f){throw new F(29);}d&&(a.node.timestamp=Date.now());return e}},mb={cc(){a:{if(!eb.length){var a=null;if(ha){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c?a=b.slice(0,c).toString("utf-8"):a=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}eb=hb(a,!0)}a=
eb.shift()}return a},Wb(a,b){null===b||10===b?(na(D(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(na(D(a.output,0)),a.output=[])},tc(){return{Mc:25856,Oc:5,Lc:191,Nc:35387,Kc:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},uc(){return 0},vc(){return[24,80]}},nb={Wb(a,b){null===b||10===b?(oa(D(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(oa(D(a.output,0)),a.output=[])}};
function ob(a,b){var c=a.sb?a.sb.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.sb,a.sb=new Uint8Array(b),0<a.ub&&a.sb.set(c.subarray(0,a.ub),0))}
var I={Bb:null,Eb(){return I.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new F(63);I.Bb||(I.Bb={dir:{node:{Ab:I.rb.Ab,xb:I.rb.xb,lookup:I.rb.lookup,Rb:I.rb.Rb,rename:I.rb.rename,unlink:I.rb.unlink,rmdir:I.rb.rmdir,readdir:I.rb.readdir,symlink:I.rb.symlink},stream:{Jb:I.tb.Jb}},file:{node:{Ab:I.rb.Ab,xb:I.rb.xb},stream:{Jb:I.tb.Jb,read:I.tb.read,write:I.tb.write,Qb:I.tb.Qb,Vb:I.tb.Vb,ic:I.tb.ic}},link:{node:{Ab:I.rb.Ab,xb:I.rb.xb,readlink:I.rb.readlink},
stream:{}},$b:{node:{Ab:I.rb.Ab,xb:I.rb.xb},stream:pb}});c=qb(a,b,c,d);J(c.mode)?(c.rb=I.Bb.dir.node,c.tb=I.Bb.dir.stream,c.sb={}):32768===(c.mode&61440)?(c.rb=I.Bb.file.node,c.tb=I.Bb.file.stream,c.ub=0,c.sb=null):40960===(c.mode&61440)?(c.rb=I.Bb.link.node,c.tb=I.Bb.link.stream):8192===(c.mode&61440)&&(c.rb=I.Bb.$b.node,c.tb=I.Bb.$b.stream);c.timestamp=Date.now();a&&(a.sb[b]=c,a.timestamp=c.timestamp);return c},Pc(a){return a.sb?a.sb.subarray?a.sb.subarray(0,a.ub):new Uint8Array(a.sb):new Uint8Array(0)},
rb:{Ab(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;J(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.ub:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.pc=4096;b.blocks=Math.ceil(b.size/b.pc);return b},xb(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.ub!=b))if(0==
b)a.sb=null,a.ub=0;else{var c=a.sb;a.sb=new Uint8Array(b);c&&a.sb.set(c.subarray(0,Math.min(b,a.ub)));a.ub=b}},lookup(){throw rb[44];},Rb(a,b,c,d){return I.createNode(a,b,c,d)},rename(a,b,c){if(J(a.mode)){try{var d=sb(b,c)}catch(f){}if(d)for(var e in d.sb)throw new F(55);}delete a.parent.sb[a.name];a.parent.timestamp=Date.now();a.name=c;b.sb[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink(a,b){delete a.sb[b];a.timestamp=Date.now()},rmdir(a,b){var c=sb(a,b),d;for(d in c.sb)throw new F(55);delete a.sb[b];
a.timestamp=Date.now()},readdir(a){var b=[".",".."],c;for(c in a.sb)a.sb.hasOwnProperty(c)&&b.push(c);return b},symlink(a,b,c){a=I.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new F(28);return a.link}},tb:{read(a,b,c,d,e){var f=a.node.sb;if(e>=a.node.ub)return 0;a=Math.min(a.node.ub-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===w.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=
Date.now();if(b.subarray&&(!a.sb||a.sb.subarray)){if(f)return a.sb=b.subarray(c,c+d),a.ub=d;if(0===a.ub&&0===e)return a.sb=b.slice(c,c+d),a.ub=d;if(e+d<=a.ub)return a.sb.set(b.subarray(c,c+d),e),d}ob(a,e+d);if(a.sb.subarray&&b.subarray)a.sb.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.sb[e+f]=b[c+f];a.ub=Math.max(a.ub,e+d);return d},Jb(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ub);if(0>b)throw new F(28);return b},Qb(a,b,c){ob(a.node,b+c);a.node.ub=Math.max(a.node.ub,
b+c)},Vb(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new F(43);a=a.node.sb;if(e&2||a.buffer!==w.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;r();b=void 0;if(!b)throw new F(48);w.set(a,b)}else c=!1,b=a.byteOffset;return{yb:b,zb:c}},ic(a,b,c,d){I.tb.write(a,b,0,d,c,!1);return 0}}},tb=(a,b,c)=>{var d=`al ${a}`;ja(a,e=>{e||r(`Loading data file "${a}" failed (no arrayBuffer).`);b(new Uint8Array(e));d&&Fa(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;
});d&&Ea(d)},ub=h.preloadPlugins||[],vb=(a,b,c,d)=>{"undefined"!=typeof Browser&&Browser.ec();var e=!1;ub.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},xb=(a,b,c,d,e,f,g,l,n,m)=>{function q(k){function v(t){m&&m();l||wb(a,b,t,d,e,n);f&&f();Fa(x)}vb(k,u,v,()=>{g&&g();Fa(x)})||v(k)}var u=b?cb(E(a+"/"+b)):a,x=`cp ${u}`;Ea(x);"string"==typeof c?tb(c,k=>q(k),g):q(c)},yb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},zb=null,Ab={},Bb=[],Cb=1,Db=null,Eb=!0,F=null,rb={};
function K(a,b={}){a=cb(a);if(!a)return{path:"",node:null};b=Object.assign({ac:!0,Xb:0},b);if(8<b.Xb)throw new F(32);a=a.split("/").filter(g=>!!g);for(var c=zb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=sb(c,a[e]);d=E(d+"/"+a[e]);c.Mb&&(!f||f&&b.ac)&&(c=c.Mb.root);if(!f||b.Hb)for(f=0;40960===(c.mode&61440);)if(c=Fb(d),d=cb(Za(d),c),c=K(d,{Xb:b.Xb+1}).node,40<f++)throw new F(32);}return{path:d,node:c}}
function Gb(a){for(var b;;){if(a===a.parent)return a=a.Eb.hc,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Hb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Db.length}function Ib(a){var b=Hb(a.parent.id,a.name);if(Db[b]===a)Db[b]=a.Nb;else for(b=Db[b];b;){if(b.Nb===a){b.Nb=a.Nb;break}b=b.Nb}}
function sb(a,b){var c;if(c=(c=Jb(a,"x"))?c:a.rb.lookup?0:2)throw new F(c,a);for(c=Db[Hb(a.id,b)];c;c=c.Nb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.rb.lookup(a,b)}function qb(a,b,c,d){a=new Kb(a,b,c,d);b=Hb(a.parent.id,a.name);a.Nb=Db[b];return Db[b]=a}function J(a){return 16384===(a&61440)}function Lb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function Jb(a,b){if(Eb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Mb(a,b){try{return sb(a,b),20}catch(c){}return Jb(a,"wx")}function Nb(a,b,c){try{var d=sb(a,b)}catch(e){return e.vb}if(a=Jb(a,"wx"))return a;if(c){if(!J(d.mode))return 54;if(d===d.parent||"/"===Gb(d))return 10}else if(J(d.mode))return 31;return 0}function Ob(){for(var a=0;4096>=a;a++)if(!Bb[a])return a;throw new F(33);}
function L(a){a=Bb[a];if(!a)throw new F(8);return a}function Pb(a,b=-1){Qb||(Qb=function(){this.wb={}},Qb.prototype={},Object.defineProperties(Qb.prototype,{object:{get(){return this.node},set(c){this.node=c}},flags:{get(){return this.wb.flags},set(c){this.wb.flags=c}},position:{get(){return this.wb.position},set(c){this.wb.position=c}}}));a=Object.assign(new Qb,a);-1==b&&(b=Ob());a.fd=b;return Bb[b]=a}var pb={open(a){a.tb=Ab[a.node.rdev].tb;a.tb.open&&a.tb.open(a)},Jb(){throw new F(70);}};
function kb(a,b){Ab[a]={tb:b}}function Rb(a,b){var c="/"===b,d=!b;if(c&&zb)throw new F(10);if(!c&&!d){var e=K(b,{ac:!1});b=e.path;e=e.node;if(e.Mb)throw new F(10);if(!J(e.mode))throw new F(54);}b={type:a,Uc:{},hc:b,yc:[]};a=a.Eb(b);a.Eb=b;b.root=a;c?zb=a:e&&(e.Mb=b,e.Eb&&e.Eb.yc.push(b))}function Sb(a,b,c){var d=K(a,{parent:!0}).node;a=$a(a);if(!a||"."===a||".."===a)throw new F(28);var e=Mb(d,a);if(e)throw new F(e);if(!d.rb.Rb)throw new F(63);return d.rb.Rb(d,a,b,c)}
function N(a,b){return Sb(a,(void 0!==b?b:511)&1023|16384,0)}function Tb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Sb(a,b|8192,c)}function Ub(a,b){if(!cb(a))throw new F(44);var c=K(b,{parent:!0}).node;if(!c)throw new F(44);b=$a(b);var d=Mb(c,b);if(d)throw new F(d);if(!c.rb.symlink)throw new F(63);c.rb.symlink(c,b,a)}function Vb(a){var b=K(a,{parent:!0}).node;a=$a(a);var c=sb(b,a),d=Nb(b,a,!0);if(d)throw new F(d);if(!b.rb.rmdir)throw new F(63);if(c.Mb)throw new F(10);b.rb.rmdir(b,a);Ib(c)}
function Wb(a){var b=K(a,{parent:!0}).node;if(!b)throw new F(44);a=$a(a);var c=sb(b,a),d=Nb(b,a,!1);if(d)throw new F(d);if(!b.rb.unlink)throw new F(63);if(c.Mb)throw new F(10);b.rb.unlink(b,a);Ib(c)}function Fb(a){a=K(a).node;if(!a)throw new F(44);if(!a.rb.readlink)throw new F(28);return cb(Gb(a.parent),a.rb.readlink(a))}function Xb(a,b){a=K(a,{Hb:!b}).node;if(!a)throw new F(44);if(!a.rb.Ab)throw new F(63);return a.rb.Ab(a)}function Yb(a){return Xb(a,!0)}
function Zb(a,b){a="string"==typeof a?K(a,{Hb:!0}).node:a;if(!a.rb.xb)throw new F(63);a.rb.xb(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function $b(a,b,c){if(""===a)throw new F(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=E(a);try{e=K(a,{Hb:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new F(20);}else e=Sb(a,c,0),d=!0;if(!e)throw new F(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&!J(e.mode))throw new F(54);if(!d&&(c=
e?40960===(e.mode&61440)?32:J(e.mode)&&("r"!==Lb(b)||b&512)?31:Jb(e,Lb(b)):44))throw new F(c);if(b&512&&!d){c=e;c="string"==typeof c?K(c,{Hb:!0}).node:c;if(!c.rb.xb)throw new F(63);if(J(c.mode))throw new F(31);if(32768!==(c.mode&61440))throw new F(28);if(d=Jb(c,"w"))throw new F(d);c.rb.xb(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Pb({node:e,path:Gb(e),flags:b,seekable:!0,position:0,tb:e.tb,Gc:[],error:!1});e.tb.open&&e.tb.open(e);!h.logReadFiles||b&1||(ac||(ac={}),a in ac||(ac[a]=1));return e}
function bc(a){if(null===a.fd)throw new F(8);a.Ib&&(a.Ib=null);try{a.tb.close&&a.tb.close(a)}catch(b){throw b;}finally{Bb[a.fd]=null}a.fd=null}function cc(a,b,c){if(null===a.fd)throw new F(8);if(!a.seekable||!a.tb.Jb)throw new F(70);if(0!=c&&1!=c&&2!=c)throw new F(28);a.position=a.tb.Jb(a,b,c);a.Gc=[];return a.position}
function dc(a,b,c,d,e,f){if(0>d||0>e)throw new F(28);if(null===a.fd)throw new F(8);if(0===(a.flags&2097155))throw new F(8);if(J(a.node.mode))throw new F(31);if(!a.tb.write)throw new F(28);a.seekable&&a.flags&1024&&cc(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new F(70);b=a.tb.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function ec(){F||(F=function(a,b){this.name="ErrnoError";this.node=b;this.zc=function(c){this.vb=c};this.zc(a);this.message="FS error"},F.prototype=Error(),F.prototype.constructor=F,[44].forEach(a=>{rb[a]=new F(a);rb[a].stack="<generic error, no stack>"}))}var fc;function gc(a,b){a="string"==typeof a?a:Gb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=E(a+"/"+c);try{N(d)}catch(e){}a=d}}return d}
function hc(a,b,c,d){a=E(("string"==typeof a?a:Gb(a))+"/"+b);c=yb(c,d);return Sb(a,(void 0!==c?c:438)&4095|32768,0)}function wb(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:Gb(a),g=b?E(a+"/"+b):a);a=yb(d,e);g=Sb(g,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Zb(g,a|146);b=$b(g,577);dc(b,c,0,c.length,0,f);bc(b);Zb(g,a)}return g}
function O(a,b,c,d){a=E(("string"==typeof a?a:Gb(a))+"/"+b);b=yb(!!c,!!d);O.fc||(O.fc=64);var e=O.fc++<<8|0;kb(e,{open(f){f.seekable=!1},close(){d&&d.buffer&&d.buffer.length&&d(10)},read(f,g,l,n){for(var m=0,q=0;q<n;q++){try{var u=c()}catch(x){throw new F(29);}if(void 0===u&&0===m)throw new F(6);if(null===u||void 0===u)break;m++;g[l+q]=u}m&&(f.node.timestamp=Date.now());return m},write(f,g,l,n){for(var m=0;m<n;m++)try{d(g[l+m])}catch(q){throw new F(29);}n&&(f.node.timestamp=Date.now());return m}});
return Tb(a,b,e)}function ic(a){if(!(a.wc||a.xc||a.link||a.sb)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ia)try{a.sb=hb(ia(a.url),!0),a.ub=a.sb.length}catch(b){throw new F(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function jc(a,b,c,d,e){function f(){this.Ub=!1;this.wb=[]}f.prototype.get=function(q){if(!(q>this.length-1||0>q)){var u=q%this.chunkSize;return this.dc(q/this.chunkSize|0)[u]}};f.prototype.Ob=function(q){this.dc=q};f.prototype.Zb=function(){var q=new XMLHttpRequest;q.open("HEAD",c,!1);q.send(null);if(!(200<=q.status&&300>q.status||304===q.status))throw Error("Couldn't load "+c+". Status: "+q.status);var u=Number(q.getResponseHeader("Content-length")),x,k=(x=q.getResponseHeader("Accept-Ranges"))&&
"bytes"===x;q=(x=q.getResponseHeader("Content-Encoding"))&&"gzip"===x;var v=1048576;k||(v=u);var t=this;t.Ob(G=>{var H=G*v,M=(G+1)*v-1;M=Math.min(M,u-1);if("undefined"==typeof t.wb[G]){var Wa=t.wb;if(H>M)throw Error("invalid range ("+H+", "+M+") or no bytes requested!");if(M>u-1)throw Error("only "+u+" bytes available! programmer error!");var R=new XMLHttpRequest;R.open("GET",c,!1);u!==v&&R.setRequestHeader("Range","bytes="+H+"-"+M);R.responseType="arraybuffer";R.overrideMimeType&&R.overrideMimeType("text/plain; charset=x-user-defined");
R.send(null);if(!(200<=R.status&&300>R.status||304===R.status))throw Error("Couldn't load "+c+". Status: "+R.status);H=void 0!==R.response?new Uint8Array(R.response||[]):hb(R.responseText||"",!0);Wa[G]=H}if("undefined"==typeof t.wb[G])throw Error("doXHR failed!");return t.wb[G]});if(q||!u)v=u=1,v=u=this.dc(0).length,na("LazyFiles on gzip forces download of the whole file when length is accessed");this.nc=u;this.mc=v;this.Ub=!0};if("undefined"!=typeof XMLHttpRequest){if(!fa)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";
var g=new f;Object.defineProperties(g,{length:{get:function(){this.Ub||this.Zb();return this.nc}},chunkSize:{get:function(){this.Ub||this.Zb();return this.mc}}});var l=void 0}else l=c,g=void 0;var n=hc(a,b,d,e);g?n.sb=g:l&&(n.sb=null,n.url=l);Object.defineProperties(n,{ub:{get:function(){return this.sb.length}}});var m={};Object.keys(n.tb).forEach(q=>{var u=n.tb[q];m[q]=function(){ic(n);return u.apply(null,arguments)}});m.read=(q,u,x,k,v)=>{ic(n);q=q.node.sb;if(v>=q.length)u=0;else{k=Math.min(q.length-
v,k);if(q.slice)for(var t=0;t<k;t++)u[x+t]=q[v+t];else for(t=0;t<k;t++)u[x+t]=q.get(v+t);u=k}return u};m.Vb=()=>{ic(n);r();throw new F(48);};n.tb=m;return n}var P={},Qb,ac;function kc(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?"/":L(a).path;if(0==b.length){if(!c)throw new F(44);return a}return E(a+"/"+b)}
function lc(a,b,c){try{var d=a(b)}catch(f){if(f&&f.node&&E(b)!==E(Gb(f.node)))return-54;throw f;}z[c>>2]=d.dev;z[c+4>>2]=d.mode;A[c+8>>2]=d.nlink;z[c+12>>2]=d.uid;z[c+16>>2]=d.gid;z[c+20>>2]=d.rdev;C=[d.size>>>0,(B=d.size,1<=+Math.abs(B)?0<B?+Math.floor(B/4294967296)>>>0:~~+Math.ceil((B-+(~~B>>>0))/4294967296)>>>0:0)];z[c+24>>2]=C[0];z[c+28>>2]=C[1];z[c+32>>2]=4096;z[c+36>>2]=d.blocks;a=d.atime.getTime();b=d.mtime.getTime();var e=d.ctime.getTime();C=[Math.floor(a/1E3)>>>0,(B=Math.floor(a/1E3),1<=
+Math.abs(B)?0<B?+Math.floor(B/4294967296)>>>0:~~+Math.ceil((B-+(~~B>>>0))/4294967296)>>>0:0)];z[c+40>>2]=C[0];z[c+44>>2]=C[1];A[c+48>>2]=a%1E3*1E3;C=[Math.floor(b/1E3)>>>0,(B=Math.floor(b/1E3),1<=+Math.abs(B)?0<B?+Math.floor(B/4294967296)>>>0:~~+Math.ceil((B-+(~~B>>>0))/4294967296)>>>0:0)];z[c+56>>2]=C[0];z[c+60>>2]=C[1];A[c+64>>2]=b%1E3*1E3;C=[Math.floor(e/1E3)>>>0,(B=Math.floor(e/1E3),1<=+Math.abs(B)?0<B?+Math.floor(B/4294967296)>>>0:~~+Math.ceil((B-+(~~B>>>0))/4294967296)>>>0:0)];z[c+72>>2]=C[0];
z[c+76>>2]=C[1];A[c+80>>2]=e%1E3*1E3;C=[d.ino>>>0,(B=d.ino,1<=+Math.abs(B)?0<B?+Math.floor(B/4294967296)>>>0:~~+Math.ceil((B-+(~~B>>>0))/4294967296)>>>0:0)];z[c+88>>2]=C[0];z[c+92>>2]=C[1];return 0}var mc=void 0;function nc(){var a=z[+mc>>2];mc+=4;return a}
var oc,Q=a=>{for(var b="";y[a];)b+=oc[y[a++]];return b},pc={},qc={},rc={},S,sc=a=>{throw new S(a);},tc,vc=(a,b)=>{function c(l){l=b(l);if(l.length!==d.length)throw new tc("Mismatched type converter count");for(var n=0;n<d.length;++n)uc(d[n],l[n])}var d=[];d.forEach(function(l){rc[l]=a});var e=Array(a.length),f=[],g=0;a.forEach((l,n)=>{qc.hasOwnProperty(l)?e[n]=qc[l]:(f.push(l),pc.hasOwnProperty(l)||(pc[l]=[]),pc[l].push(()=>{e[n]=qc[l];++g;g===f.length&&c(e)}))});0===f.length&&c(e)};
function wc(a,b,c={}){var d=b.name;if(!a)throw new S(`type "${d}" must have a positive integer typeid pointer`);if(qc.hasOwnProperty(a)){if(c.rc)return;throw new S(`Cannot register type '${d}' twice`);}qc[a]=b;delete rc[a];pc.hasOwnProperty(a)&&(b=pc[a],delete pc[a],b.forEach(e=>e()))}function uc(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");wc(a,b,c)}function xc(){this.zb=[void 0];this.bc=[]}
var T=new xc,yc=a=>{a>=T.wb&&0===--T.get(a).jc&&T.Ob(a)},U=a=>{if(!a)throw new S("Cannot use deleted val. handle = "+a);return T.get(a).value},zc=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:return T.Qb({jc:1,value:a})}};function Ac(a){return this.fromWireType(z[a>>2])}
var Bc=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(ua[c>>2])};case 8:return function(c){return this.fromWireType(va[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Cc=a=>{if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a},Dc=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Ec(a,b){a=Cc(a);return{[a]:function(){return b.apply(this,arguments)}}[a]}
function Fc(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=Ec(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
var Gc=(a,b)=>{if(void 0===h[a].Cb){var c=h[a];h[a]=function(){if(!h[a].Cb.hasOwnProperty(arguments.length))throw new S(`Function '${b}' called with an invalid number of arguments (${arguments.length}) - expects one of (${h[a].Cb})!`);return h[a].Cb[arguments.length].apply(this,arguments)};h[a].Cb=[];h[a].Cb[c.oc]=c}},Hc=(a,b,c)=>{if(h.hasOwnProperty(a)){if(void 0===c||void 0!==h[a].Cb&&void 0!==h[a].Cb[c])throw new S(`Cannot register public name '${a}' twice`);Gc(a,a);if(h.hasOwnProperty(c))throw new S(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
h[a].Cb[c]=b}else h[a]=b,void 0!==c&&(h[a].Tc=c)},Ic=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(A[b+4*d>>2]);return c},Jc=[],Kc,V=a=>{var b=Jc[a];b||(a>=Jc.length&&(Jc.length=a+1),Jc[a]=b=Kc.get(a));return b},Lc=(a,b)=>{var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=h["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=V(b).apply(null,c);return d}},Mc=(a,b)=>{a=Q(a);var c=a.includes("j")?Lc(a,b):V(b);if("function"!=typeof c)throw new S(`unknown function pointer with signature ${a}: ${b}`);
return c},Nc,Qc=a=>{a=Oc(a);var b=Q(a);Pc(a);return b},Rc=(a,b)=>{function c(f){e[f]||qc[f]||(rc[f]?rc[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Nc(`${a}: `+d.map(Qc).join([", "]));},Sc=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?(")"==a[a.length-1]||r("Parentheses for argument names should match."),a.substr(0,b)):a},Tc=(a,b,c)=>{switch(b){case 1:return c?d=>w[d>>0]:d=>y[d>>0];case 2:return c?d=>sa[d>>1]:d=>ta[d>>1];case 4:return c?d=>z[d>>2]:d=>A[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);
}};function Uc(a){return this.fromWireType(A[a>>2])}
var Vc="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Wc=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&ta[c];)++c;c<<=1;if(32<c-a&&Vc)return Vc.decode(y.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=sa[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},Xc=(a,b,c)=>{void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)sa[b>>1]=a.charCodeAt(e),b+=2;sa[b>>1]=0;return b-d},Yc=a=>2*a.length,Zc=(a,b)=>{for(var c=0,d="";!(c>=
b/4);){var e=z[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},$c=(a,b,c)=>{void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var g=a.charCodeAt(++e);f=65536+((f&1023)<<10)|g&1023}z[b>>2]=f;b+=4;if(b+4>c)break}z[b>>2]=0;return b-d},ad=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},bd=
(a,b)=>{var c=qc[a];if(void 0===c)throw a=b+" has unknown type "+Qc(a),new S(a);return c},cd={},dd=a=>{var b=cd[a];return void 0===b?Q(a):b},ed=()=>"object"==typeof globalThis?globalThis:Function("return this")(),fd=a=>{for(var b="",c=0;c<a;++c)b+=(0!==c?", ":"")+"arg"+c;var d="return function emval_allocator_"+a+"(constructor, argTypes, args) {\n  var HEAPU32 = getMemory();\n";for(c=0;c<a;++c)d+="var argType"+c+" = requireRegisteredType(HEAPU32[((argTypes)>>2)], 'parameter "+c+"');\nvar arg"+c+" = argType"+
c+".readValueFromPointer(args);\nargs += argType"+c+"['argPackAdvance'];\nargTypes += 4;\n";return(new Function("requireRegisteredType","Module","valueToHandle","getMemory",d+("var obj = new constructor("+b+");\nreturn valueToHandle(obj);\n}\n")))(bd,h,zc,()=>A)},gd={},hd=a=>0===a%4&&(0!==a%100||0===a%400),jd=[0,31,60,91,121,152,182,213,244,274,305,335],kd=[0,31,59,90,120,151,181,212,243,273,304,334],md=a=>{var b=fb(a)+1,c=ld(b);c&&gb(a,y,c,b);return c},nd=[],od={},qd=()=>{if(!pd){var a={USER:"web_user",
LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in od)void 0===od[b]?delete a[b]:a[b]=od[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);pd=c}return pd},pd,rd=[31,29,31,30,31,30,31,31,30,31,30,31],sd=[31,28,31,30,31,30,31,31,30,31,30,31],td=(a,b,c,d)=>{function e(k,v,t){for(k="number"==typeof k?k.toString():k||"";k.length<v;)k=t[0]+k;return k}function f(k,
v){return e(k,v,"0")}function g(k,v){function t(H){return 0>H?-1:0<H?1:0}var G;0===(G=t(k.getFullYear()-v.getFullYear()))&&0===(G=t(k.getMonth()-v.getMonth()))&&(G=t(k.getDate()-v.getDate()));return G}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-
1,11,30)}}function n(k){var v=k.Kb;for(k=new Date((new Date(k.Lb+1900,0,1)).getTime());0<v;){var t=k.getMonth(),G=(hd(k.getFullYear())?rd:sd)[t];if(v>G-k.getDate())v-=G-k.getDate()+1,k.setDate(1),11>t?k.setMonth(t+1):(k.setMonth(0),k.setFullYear(k.getFullYear()+1));else{k.setDate(k.getDate()+v);break}}t=new Date(k.getFullYear()+1,0,4);v=l(new Date(k.getFullYear(),0,4));t=l(t);return 0>=g(v,k)?0>=g(t,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var m=A[d+40>>2];d={Dc:z[d>>2],Cc:z[d+4>>2],
Sb:z[d+8>>2],Yb:z[d+12>>2],Tb:z[d+16>>2],Lb:z[d+20>>2],Db:z[d+24>>2],Kb:z[d+28>>2],Vc:z[d+32>>2],Bc:z[d+36>>2],Ec:m?m?D(y,m):"":""};c=c?D(y,c):"";m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W",
"%Oy":"%y"};for(var q in m)c=c.replace(new RegExp(q,"g"),m[q]);var u="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),x="January February March April May June July August September October November December".split(" ");m={"%a":k=>u[k.Db].substring(0,3),"%A":k=>u[k.Db],"%b":k=>x[k.Tb].substring(0,3),"%B":k=>x[k.Tb],"%C":k=>f((k.Lb+1900)/100|0,2),"%d":k=>f(k.Yb,2),"%e":k=>e(k.Yb,2," "),"%g":k=>n(k).toString().substring(2),"%G":k=>n(k),"%H":k=>f(k.Sb,2),"%I":k=>{k=k.Sb;0==k?k=12:
12<k&&(k-=12);return f(k,2)},"%j":k=>{for(var v=0,t=0;t<=k.Tb-1;v+=(hd(k.Lb+1900)?rd:sd)[t++]);return f(k.Yb+v,3)},"%m":k=>f(k.Tb+1,2),"%M":k=>f(k.Cc,2),"%n":()=>"\n","%p":k=>0<=k.Sb&&12>k.Sb?"AM":"PM","%S":k=>f(k.Dc,2),"%t":()=>"\t","%u":k=>k.Db||7,"%U":k=>f(Math.floor((k.Kb+7-k.Db)/7),2),"%V":k=>{var v=Math.floor((k.Kb+7-(k.Db+6)%7)/7);2>=(k.Db+371-k.Kb-2)%7&&v++;if(v)53==v&&(t=(k.Db+371-k.Kb)%7,4==t||3==t&&hd(k.Lb)||(v=1));else{v=52;var t=(k.Db+7-k.Kb-1)%7;(4==t||5==t&&hd(k.Lb%400-1))&&v++}return f(v,
2)},"%w":k=>k.Db,"%W":k=>f(Math.floor((k.Kb+7-(k.Db+6)%7)/7),2),"%y":k=>(k.Lb+1900).toString().substring(2),"%Y":k=>k.Lb+1900,"%z":k=>{k=k.Bc;var v=0<=k;k=Math.abs(k)/60;return(v?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":k=>k.Ec,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");for(q in m)c.includes(q)&&(c=c.replace(new RegExp(q,"g"),m[q](d)));c=c.replace(/\0\0/g,"%");q=hb(c,!1);if(q.length>b)return 0;w.set(q,a);return q.length-1};
function Kb(a,b,c,d){a||(a=this);this.parent=a;this.Eb=a.Eb;this.Mb=null;this.id=Cb++;this.name=b;this.mode=c;this.rb={};this.tb={};this.rdev=d}Object.defineProperties(Kb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},xc:{get:function(){return J(this.mode)}},wc:{get:function(){return 8192===(this.mode&61440)}}});ec();Db=Array(4096);
Rb(I,"/");N("/tmp");N("/home");N("/home/web_user");(function(){N("/dev");kb(259,{read:()=>0,write:(d,e,f,g)=>g});Tb("/dev/null",259);jb(1280,mb);jb(1536,nb);Tb("/dev/tty",1280);Tb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=bb(a).byteLength);return a[--b]};O("/dev","random",c);O("/dev","urandom",c);N("/dev/shm");N("/dev/shm/tmp")})();
(function(){N("/proc");var a=N("/proc/self");N("/proc/self/fd");Rb({Eb(){var b=qb(a,"fd",16895,73);b.rb={lookup(c,d){var e=L(+d);c={parent:null,Eb:{hc:"fake"},rb:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();h.FS_createPath=gc;h.FS_createDataFile=wb;h.FS_createPreloadedFile=xb;h.FS_unlink=Wb;h.FS_createLazyFile=jc;h.FS_createDevice=O;for(var ud=Array(256),vd=0;256>vd;++vd)ud[vd]=String.fromCharCode(vd);oc=ud;
S=h.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};tc=h.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};Object.assign(xc.prototype,{get(a){return this.zb[a]},has(a){return void 0!==this.zb[a]},Qb(a){var b=this.bc.pop()||this.zb.length;this.zb[b]=a;return b},Ob(a){this.zb[a]=void 0;this.bc.push(a)}});T.zb.push({value:void 0},{value:null},{value:!0},{value:!1});T.wb=T.zb.length;
h.count_emval_handles=()=>{for(var a=0,b=T.wb;b<T.zb.length;++b)void 0!==T.zb[b]&&++a;return a};Nc=h.UnboundTypeError=((a,b)=>{var c=Ec(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
var Zd={m:a=>{a=new Sa(a);a.Fc()||(a.kc(!0),Qa--);a.lc(!1);Pa.push(a);wd(a.Pb);return a.Hc()},o:()=>{W(0,0);var a=Pa.pop();xd(a.Pb);Ra=0},a:()=>Xa([]),g:a=>Xa([a]),B:()=>{var a=Pa.pop();a||r("no exception to throw");var b=a.Pb;a.qc()||(Pa.push(a),a.lc(!0),a.kc(!1),Qa++);Ra=b;throw Ra;},b:(a,b,c)=>{(new Sa(a)).ec(b,c);Ra=a;Qa++;throw Ra;},ba:()=>Qa,e:a=>{Ra||(Ra=a);throw Ra;},wa:function(a,b){try{return a=a?D(y,a):"",Zb(a,b),0}catch(c){if("undefined"==typeof P||"ErrnoError"!==c.name)throw c;return-c.vb}},
xa:function(a,b,c){try{b=b?D(y,b):"";b=kc(a,b);if(c&-8)return-28;var d=K(b,{Hb:!0}).node;if(!d)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&Jb(d,a)?-2:0}catch(e){if("undefined"==typeof P||"ErrnoError"!==e.name)throw e;return-e.vb}},K:function(a,b,c){mc=c;try{var d=L(a);switch(b){case 0:var e=nc();if(0>e)return-28;for(;Bb[e];)e++;return Pb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=nc(),d.flags|=e,0;case 5:return e=nc(),sa[e+0>>1]=2,0;case 6:case 7:return 0;
case 16:case 8:return-28;case 9:return z[yd()>>2]=28,-1;default:return-28}}catch(f){if("undefined"==typeof P||"ErrnoError"!==f.name)throw f;return-f.vb}},qa:function(a,b){try{var c=L(a);return lc(Xb,c.path,b)}catch(d){if("undefined"==typeof P||"ErrnoError"!==d.name)throw d;return-d.vb}},ma:function(a,b){try{if(0===b)return-28;var c=fb("/")+1;if(b<c)return-68;gb("/",y,a,b);return c}catch(d){if("undefined"==typeof P||"ErrnoError"!==d.name)throw d;return-d.vb}},ia:function(a,b,c){try{var d=L(a);if(!d.Ib){var e=
K(d.path,{Hb:!0}).node;if(!e.rb.readdir)throw new F(54);var f=e.rb.readdir(e);d.Ib=f}a=0;for(var g=cc(d,0,1),l=Math.floor(g/280);l<d.Ib.length&&a+280<=c;){var n=d.Ib[l];if("."===n){var m=d.node.id;var q=4}else if(".."===n)m=K(d.path,{parent:!0}).node.id,q=4;else{var u=sb(d.node,n);m=u.id;q=8192===(u.mode&61440)?2:J(u.mode)?4:40960===(u.mode&61440)?10:8}C=[m>>>0,(B=m,1<=+Math.abs(B)?0<B?+Math.floor(B/4294967296)>>>0:~~+Math.ceil((B-+(~~B>>>0))/4294967296)>>>0:0)];z[b+a>>2]=C[0];z[b+a+4>>2]=C[1];C=
[280*(l+1)>>>0,(B=280*(l+1),1<=+Math.abs(B)?0<B?+Math.floor(B/4294967296)>>>0:~~+Math.ceil((B-+(~~B>>>0))/4294967296)>>>0:0)];z[b+a+8>>2]=C[0];z[b+a+12>>2]=C[1];sa[b+a+16>>1]=280;w[b+a+18>>0]=q;gb(n,y,b+a+19,256);a+=280;l+=1}cc(d,280*l,0);return a}catch(x){if("undefined"==typeof P||"ErrnoError"!==x.name)throw x;return-x.vb}},sa:function(a,b,c){mc=c;try{var d=L(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.Fb.tc){b=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=nc();z[e>>2]=25856;z[e+4>>2]=5;z[e+8>>2]=191;z[e+12>>2]=35387;for(var f=0;32>f;f++)w[e+f+17>>0]=b[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Fb.uc)for(e=nc(),b=[],f=0;32>f;f++)b.push(w[e+f+17>>0]);return 0;case 21519:if(!d.tty)return-59;e=nc();return z[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:e=nc();if(!d.tb.sc)throw new F(59);return d.tb.sc(d,b,e);case 21523:if(!d.tty)return-59;
d.tty.Fb.vc&&(f=[24,80],e=nc(),sa[e>>1]=f[0],sa[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if("undefined"==typeof P||"ErrnoError"!==g.name)throw g;return-g.vb}},na:function(a,b){try{return a=a?D(y,a):"",lc(Yb,a,b)}catch(c){if("undefined"==typeof P||"ErrnoError"!==c.name)throw c;return-c.vb}},ja:function(a,b,c){try{return b=b?D(y,b):"",b=kc(a,b),b=E(b),"/"===b[b.length-1]&&(b=b.substr(0,b.length-1)),N(b,c),0}catch(d){if("undefined"==
typeof P||"ErrnoError"!==d.name)throw d;return-d.vb}},oa:function(a,b,c,d){try{b=b?D(y,b):"";var e=d&256;b=kc(a,b,d&4096);return lc(e?Yb:Xb,b,c)}catch(f){if("undefined"==typeof P||"ErrnoError"!==f.name)throw f;return-f.vb}},L:function(a,b,c,d){mc=d;try{b=b?D(y,b):"";b=kc(a,b);var e=d?nc():0;return $b(b,c,e).fd}catch(f){if("undefined"==typeof P||"ErrnoError"!==f.name)throw f;return-f.vb}},I:function(a){try{return a=a?D(y,a):"",Vb(a),0}catch(b){if("undefined"==typeof P||"ErrnoError"!==b.name)throw b;
return-b.vb}},pa:function(a,b){try{return a=a?D(y,a):"",lc(Xb,a,b)}catch(c){if("undefined"==typeof P||"ErrnoError"!==c.name)throw c;return-c.vb}},ha:function(a,b,c){try{return b=b?D(y,b):"",b=kc(a,b),0===c?Wb(b):512===c?Vb(b):r("Invalid flags passed to unlinkat"),0}catch(d){if("undefined"==typeof P||"ErrnoError"!==d.name)throw d;return-d.vb}},ea:function(a,b,c){try{b=b?D(y,b):"";b=kc(a,b,!0);if(c){var d=A[c>>2]+4294967296*z[c+4>>2],e=z[c+8>>2];f=1E3*d+e/1E6;c+=16;d=A[c>>2]+4294967296*z[c+4>>2];e=
z[c+8>>2];g=1E3*d+e/1E6}else var f=Date.now(),g=f;a=f;var l=K(b,{Hb:!0}).node;l.rb.xb(l,{timestamp:Math.max(a,g)});return 0}catch(n){if("undefined"==typeof P||"ErrnoError"!==n.name)throw n;return-n.vb}},Y:()=>{},za:(a,b,c,d)=>{b=Q(b);uc(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,f){return f?c:d},argPackAdvance:8,readValueFromPointer:function(e){return this.fromWireType(y[e])},Gb:null})},ya:(a,b)=>{b=Q(b);uc(a,{name:b,fromWireType:c=>{var d=U(c);yc(c);return d},toWireType:(c,
d)=>zc(d),argPackAdvance:8,readValueFromPointer:Ac,Gb:null})},O:(a,b,c)=>{b=Q(b);uc(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,argPackAdvance:8,readValueFromPointer:Bc(b,c),Gb:null})},z:(a,b,c,d,e,f,g)=>{var l=Ic(b,c);a=Q(a);a=Sc(a);e=Mc(d,e);Hc(a,function(){Rc(`Cannot call ${a} due to unbound types`,l)},b-1);vc(l,function(n){var m=[n[0],null].concat(n.slice(1)),q=n=a,u=e,x=m.length;if(2>x)throw new S("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var k=
null!==m[1]&&!1,v=!1,t=1;t<m.length;++t)if(null!==m[t]&&void 0===m[t].Gb){v=!0;break}var G="void"!==m[0].name,H="",M="";for(t=0;t<x-2;++t)H+=(0!==t?", ":"")+"arg"+t,M+=(0!==t?", ":"")+"arg"+t+"Wired";q=`\n        return function ${Cc(q)}(${H}) {\n        if (arguments.length !== ${x-2}) {\n          throwBindingError('function ${q} called with ' + arguments.length + ' arguments, expected ${x-2}');\n        }`;v&&(q+="var destructors = [];\n");var Wa=v?"destructors":"null";H="throwBindingError invoker fn runDestructors retType classParam".split(" ");
u=[sc,u,f,Dc,m[0],m[1]];k&&(q+="var thisWired = classParam.toWireType("+Wa+", this);\n");for(t=0;t<x-2;++t)q+="var arg"+t+"Wired = argType"+t+".toWireType("+Wa+", arg"+t+"); // "+m[t+2].name+"\n",H.push("argType"+t),u.push(m[t+2]);k&&(M="thisWired"+(0<M.length?", ":"")+M);q+=(G||g?"var rv = ":"")+"invoker(fn"+(0<M.length?", ":"")+M+");\n";if(v)q+="runDestructors(destructors);\n";else for(t=k?1:2;t<m.length;++t)x=1===t?"thisWired":"arg"+(t-2)+"Wired",null!==m[t].Gb&&(q+=x+"_dtor("+x+"); // "+m[t].name+
"\n",H.push(x+"_dtor"),u.push(m[t].Gb));G&&(q+="var ret = retType.fromWireType(rv);\nreturn ret;\n");H.push(q+"}\n");m=Fc(H).apply(null,u);t=b-1;if(!h.hasOwnProperty(n))throw new tc("Replacing nonexistant public symbol");void 0!==h[n].Cb&&void 0!==t?h[n].Cb[t]=m:(h[n]=m,h[n].oc=t);return[]})},r:(a,b,c,d,e)=>{b=Q(b);-1===e&&(e=4294967295);e=l=>l;if(0===d){var f=32-8*c;e=l=>l<<f>>>f}var g=b.includes("unsigned")?function(l,n){return n>>>0}:function(l,n){return n};uc(a,{name:b,fromWireType:e,toWireType:g,
argPackAdvance:8,readValueFromPointer:Tc(b,c,0!==d),Gb:null})},p:(a,b,c)=>{function d(f){return new e(w.buffer,A[f+4>>2],A[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=Q(c);uc(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{rc:!0})},N:(a,b)=>{b=Q(b);var c="std::string"===b;uc(a,{name:b,fromWireType:function(d){var e=A[d>>2],f=d+4;if(c)for(var g=f,l=0;l<=e;++l){var n=f+l;if(l==e||0==y[n]){g=g?D(y,g,n-g):"";if(void 0===
m)var m=g;else m+=String.fromCharCode(0),m+=g;g=n+1}}else{m=Array(e);for(l=0;l<e;++l)m[l]=String.fromCharCode(y[f+l]);m=m.join("")}Pc(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"==typeof e;if(!(f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array))throw new S("Cannot pass non-string to std::string");var g=c&&f?fb(e):e.length;var l=ld(4+g+1),n=l+4;A[l>>2]=g;if(c&&f)gb(e,y,n,g+1);else if(f)for(f=0;f<g;++f){var m=e.charCodeAt(f);
if(255<m)throw Pc(n),new S("String has UTF-16 code units that do not fit in 8 bits");y[n+f]=m}else for(f=0;f<g;++f)y[n+f]=e[f];null!==d&&d.push(Pc,l);return l},argPackAdvance:8,readValueFromPointer:Uc,Gb(d){Pc(d)}})},C:(a,b,c)=>{c=Q(c);if(2===b){var d=Wc;var e=Xc;var f=Yc;var g=()=>ta;var l=1}else 4===b&&(d=Zc,e=$c,f=ad,g=()=>A,l=2);uc(a,{name:c,fromWireType:n=>{for(var m=A[n>>2],q=g(),u,x=n+4,k=0;k<=m;++k){var v=n+4+k*b;if(k==m||0==q[v>>l])x=d(x,v-x),void 0===u?u=x:(u+=String.fromCharCode(0),u+=
x),x=v+b}Pc(n);return u},toWireType:(n,m)=>{if("string"!=typeof m)throw new S(`Cannot pass non-string to C++ string type ${c}`);var q=f(m),u=ld(4+q+b);A[u>>2]=q>>l;e(m,u+4,q+b);null!==n&&n.push(Pc,u);return u},argPackAdvance:8,readValueFromPointer:Ac,Gb(n){Pc(n)}})},Aa:(a,b)=>{b=Q(b);uc(a,{Qc:!0,name:b,argPackAdvance:0,fromWireType:()=>{},toWireType:()=>{}})},ta:()=>!0,ca:()=>{throw Infinity;},Ga:(a,b,c)=>{a=U(a);b=bd(b,"emval::as");var d=[],e=zc(d);A[c>>2]=e;return b.toWireType(d,a)},Q:yc,Da:a=>
{if(0===a)return zc(ed());a=dd(a);return zc(ed()[a])},Ha:(a,b)=>{a=U(a);b=U(b);return zc(a[b])},ga:a=>{4<a&&(T.get(a).jc+=1)},va:(a,b)=>{a=U(a);b=U(b);return a instanceof b},Ia:(a,b,c,d)=>{a=U(a);var e=gd[b];e||(e=fd(b),gd[b]=e);return e(a,c,d)},E:a=>zc(dd(a)),Ja:()=>zc({}),Fa:a=>{var b=U(a);Dc(b);yc(a)},Ca:(a,b,c)=>{a=U(a);b=U(b);c=U(c);a[b]=c},Ea:(a,b)=>{a=bd(a,"_emval_take_value");a=a.readValueFromPointer(b);return zc(a)},U:function(a,b,c){a=new Date(1E3*(b+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*
b:NaN));z[c>>2]=a.getUTCSeconds();z[c+4>>2]=a.getUTCMinutes();z[c+8>>2]=a.getUTCHours();z[c+12>>2]=a.getUTCDate();z[c+16>>2]=a.getUTCMonth();z[c+20>>2]=a.getUTCFullYear()-1900;z[c+24>>2]=a.getUTCDay();z[c+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0},V:function(a,b,c){a=new Date(1E3*(b+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*b:NaN));z[c>>2]=a.getSeconds();z[c+4>>2]=a.getMinutes();z[c+8>>2]=a.getHours();z[c+12>>2]=a.getDate();z[c+16>>2]=a.getMonth();z[c+20>>2]=a.getFullYear()-
1900;z[c+24>>2]=a.getDay();z[c+28>>2]=(hd(a.getFullYear())?jd:kd)[a.getMonth()]+a.getDate()-1|0;z[c+36>>2]=-(60*a.getTimezoneOffset());b=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();z[c+32>>2]=(b!=d&&a.getTimezoneOffset()==Math.min(d,b))|0},W:function(a){var b=new Date(z[a+20>>2]+1900,z[a+16>>2],z[a+12>>2],z[a+8>>2],z[a+4>>2],z[a>>2],0),c=z[a+32>>2],d=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),f=(new Date(b.getFullYear(),
0,1)).getTimezoneOffset(),g=Math.min(f,e);0>c?z[a+32>>2]=Number(e!=f&&g==d):0<c!=(g==d)&&(e=Math.max(f,e),b.setTime(b.getTime()+6E4*((0<c?g:e)-d)));z[a+24>>2]=b.getDay();z[a+28>>2]=(hd(b.getFullYear())?jd:kd)[b.getMonth()]+b.getDate()-1|0;z[a>>2]=b.getSeconds();z[a+4>>2]=b.getMinutes();z[a+8>>2]=b.getHours();z[a+12>>2]=b.getDate();z[a+16>>2]=b.getMonth();z[a+20>>2]=b.getYear();a=b.getTime()/1E3;return Ua((B=a,1<=+Math.abs(B)?0<B?+Math.floor(B/4294967296)>>>0:~~+Math.ceil((B-+(~~B>>>0))/4294967296)>>>
0:0)),a>>>0},fa:(a,b,c)=>{function d(n){return(n=n.toTimeString().match(/\(([A-Za-z ]+)\)$/))?n[1]:"GMT"}var e=(new Date).getFullYear(),f=new Date(e,0,1),g=new Date(e,6,1);e=f.getTimezoneOffset();var l=g.getTimezoneOffset();A[a>>2]=60*Math.max(e,l);z[b>>2]=Number(e!=l);a=d(f);b=d(g);a=md(a);b=md(b);l<e?(A[c>>2]=a,A[c+4>>2]=b):(A[c>>2]=b,A[c+4>>2]=a)},y:()=>{r("")},Ka:(a,b,c)=>{nd.length=0;for(var d;d=y[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;nd.push(112==d?A[c>>2]:105==d?z[c>>2]:va[c>>3]);c+=
e?8:4}return Na[a].apply(null,nd)},M:()=>Date.now(),ua:(a,b,c)=>y.copyWithin(a,b,b+c),da:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-qa.buffer.byteLength+65535)/65536;try{qa.grow(e);wa();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},ka:(a,b)=>{var c=0;qd().forEach((d,e)=>{var f=b+c;e=A[a+4*e>>2]=f;for(f=0;f<d.length;++f)w[e++>>0]=d.charCodeAt(f);
w[e>>0]=0;c+=d.length+1});return 0},la:(a,b)=>{var c=qd();A[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);A[b>>2]=d;return 0},x:function(a){try{var b=L(a);bc(b);return 0}catch(c){if("undefined"==typeof P||"ErrnoError"!==c.name)throw c;return c.vb}},ra:function(a,b,c,d){try{a:{var e=L(a);a=b;for(var f,g=b=0;g<c;g++){var l=A[a>>2],n=A[a+4>>2];a+=8;var m=e,q=l,u=n,x=f,k=w;if(0>u||0>x)throw new F(28);if(null===m.fd)throw new F(8);if(1===(m.flags&2097155))throw new F(8);if(J(m.node.mode))throw new F(31);
if(!m.tb.read)throw new F(28);var v="undefined"!=typeof x;if(!v)x=m.position;else if(!m.seekable)throw new F(70);var t=m.tb.read(m,k,q,u,x);v||(m.position+=t);var G=t;if(0>G){var H=-1;break a}b+=G;if(G<n)break;"undefined"!==typeof f&&(f+=G)}H=b}A[d>>2]=H;return 0}catch(M){if("undefined"==typeof P||"ErrnoError"!==M.name)throw M;return M.vb}},X:function(a,b,c,d,e){b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;try{if(isNaN(b))return 61;var f=L(a);cc(f,b,d);C=[f.position>>>0,(B=f.position,1<=+Math.abs(B)?
0<B?+Math.floor(B/4294967296)>>>0:~~+Math.ceil((B-+(~~B>>>0))/4294967296)>>>0:0)];z[e>>2]=C[0];z[e+4>>2]=C[1];f.Ib&&0===b&&0===d&&(f.Ib=null);return 0}catch(g){if("undefined"==typeof P||"ErrnoError"!==g.name)throw g;return g.vb}},J:function(a,b,c,d){try{a:{var e=L(a);a=b;for(var f,g=b=0;g<c;g++){var l=A[a>>2],n=A[a+4>>2];a+=8;var m=dc(e,w,l,n,f);if(0>m){var q=-1;break a}b+=m;"undefined"!==typeof f&&(f+=m)}q=b}A[d>>2]=q;return 0}catch(u){if("undefined"==typeof P||"ErrnoError"!==u.name)throw u;return u.vb}},
$:(a,b)=>{bb(y.subarray(a,a+b));return 0},A:zd,F:Ad,n:Bd,c:Cd,d:Dd,k:Ed,j:Fd,H:Gd,t:Hd,s:Id,G:Jd,w:Kd,Z:Ld,T:Md,S:Nd,P:Od,h:Pd,i:Qd,f:Rd,_:Sd,l:Td,D:Ud,q:Vd,u:Wd,v:Xd,R:Yd,Ba:td,aa:(a,b,c,d)=>td(a,b,c,d)},X=function(){function a(c){X=c.exports;qa=X.La;wa();Kc=X.Oa;ya.unshift(X.Ma);Fa("wasm-instantiate");return X}var b={a:Zd};Ea("wasm-instantiate");if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){oa(`Module.instantiateWasm callback failed with error: ${c}`),ba(c)}Ma(b,function(c){a(c.instance)}).catch(ba);
return{}}(),ld=h._malloc=a=>(ld=h._malloc=X.Na)(a),Pc=h._free=a=>(Pc=h._free=X.Pa)(a),yd=()=>(yd=X.Qa)();h._fflush=a=>(h._fflush=X.Ra)(a);var Ua=a=>(Ua=X.Sa)(a),Oc=a=>(Oc=X.Ta)(a);h.__embind_initialize_bindings=()=>(h.__embind_initialize_bindings=X.Ua)();
var W=(a,b)=>(W=X.Va)(a,b),Y=()=>(Y=X.Wa)(),Z=a=>(Z=X.Xa)(a),xd=a=>(xd=X.Ya)(a),wd=a=>(wd=X.Za)(a),Va=(a,b,c)=>(Va=X._a)(a,b,c),Ta=a=>(Ta=X.$a)(a),$d=h.dynCall_iijiiii=(a,b,c,d,e,f,g,l)=>($d=h.dynCall_iijiiii=X.ab)(a,b,c,d,e,f,g,l),ae=h.dynCall_ji=(a,b)=>(ae=h.dynCall_ji=X.bb)(a,b);h.dynCall_vij=(a,b,c,d)=>(h.dynCall_vij=X.cb)(a,b,c,d);h.dynCall_iiij=(a,b,c,d,e)=>(h.dynCall_iiij=X.db)(a,b,c,d,e);h.dynCall_jij=(a,b,c,d)=>(h.dynCall_jij=X.eb)(a,b,c,d);
h.dynCall_jiij=(a,b,c,d,e)=>(h.dynCall_jiij=X.fb)(a,b,c,d,e);h.dynCall_jiijj=(a,b,c,d,e,f,g)=>(h.dynCall_jiijj=X.gb)(a,b,c,d,e,f,g);var be=h.dynCall_viijii=(a,b,c,d,e,f,g)=>(be=h.dynCall_viijii=X.hb)(a,b,c,d,e,f,g);h.dynCall_viiij=(a,b,c,d,e,f)=>(h.dynCall_viiij=X.ib)(a,b,c,d,e,f);h.dynCall_iiiijii=(a,b,c,d,e,f,g,l)=>(h.dynCall_iiiijii=X.jb)(a,b,c,d,e,f,g,l);h.dynCall_iijji=(a,b,c,d,e,f,g)=>(h.dynCall_iijji=X.kb)(a,b,c,d,e,f,g);h.dynCall_jiji=(a,b,c,d,e)=>(h.dynCall_jiji=X.lb)(a,b,c,d,e);
var ce=h.dynCall_j=a=>(ce=h.dynCall_j=X.mb)(a),de=h.dynCall_jiiii=(a,b,c,d,e)=>(de=h.dynCall_jiiii=X.nb)(a,b,c,d,e);h.dynCall_iiiiij=(a,b,c,d,e,f,g)=>(h.dynCall_iiiiij=X.ob)(a,b,c,d,e,f,g);h.dynCall_iiiiijj=(a,b,c,d,e,f,g,l,n)=>(h.dynCall_iiiiijj=X.pb)(a,b,c,d,e,f,g,l,n);h.dynCall_iiiiiijj=(a,b,c,d,e,f,g,l,n,m)=>(h.dynCall_iiiiiijj=X.qb)(a,b,c,d,e,f,g,l,n,m);function Cd(a,b){var c=Y();try{return V(a)(b)}catch(d){Z(c);if(d!==d+0)throw d;W(1,0)}}
function Dd(a,b,c){var d=Y();try{return V(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;W(1,0)}}function Qd(a,b){var c=Y();try{V(a)(b)}catch(d){Z(c);if(d!==d+0)throw d;W(1,0)}}function Fd(a,b,c,d,e){var f=Y();try{return V(a)(b,c,d,e)}catch(g){Z(f);if(g!==g+0)throw g;W(1,0)}}function zd(a,b,c,d){var e=Y();try{return V(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}function Ed(a,b,c,d){var e=Y();try{return V(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}
function Td(a,b,c,d){var e=Y();try{V(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}function Rd(a,b,c){var d=Y();try{V(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;W(1,0)}}function Pd(a){var b=Y();try{V(a)()}catch(c){Z(b);if(c!==c+0)throw c;W(1,0)}}function Ud(a,b,c,d,e){var f=Y();try{V(a)(b,c,d,e)}catch(g){Z(f);if(g!==g+0)throw g;W(1,0)}}function Id(a,b,c,d,e,f,g){var l=Y();try{return V(a)(b,c,d,e,f,g)}catch(n){Z(l);if(n!==n+0)throw n;W(1,0)}}
function Hd(a,b,c,d,e,f){var g=Y();try{return V(a)(b,c,d,e,f)}catch(l){Z(g);if(l!==l+0)throw l;W(1,0)}}function Gd(a,b,c,d,e,f){var g=Y();try{return V(a)(b,c,d,e,f)}catch(l){Z(g);if(l!==l+0)throw l;W(1,0)}}function Jd(a,b,c,d,e,f,g,l){var n=Y();try{return V(a)(b,c,d,e,f,g,l)}catch(m){Z(n);if(m!==m+0)throw m;W(1,0)}}function Ad(a,b,c,d){var e=Y();try{return V(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}function Bd(a){var b=Y();try{return V(a)()}catch(c){Z(b);if(c!==c+0)throw c;W(1,0)}}
function Vd(a,b,c,d,e,f,g,l){var n=Y();try{V(a)(b,c,d,e,f,g,l)}catch(m){Z(n);if(m!==m+0)throw m;W(1,0)}}function Kd(a,b,c,d,e,f,g,l,n,m,q,u){var x=Y();try{return V(a)(b,c,d,e,f,g,l,n,m,q,u)}catch(k){Z(x);if(k!==k+0)throw k;W(1,0)}}function Wd(a,b,c,d,e,f,g,l,n,m,q){var u=Y();try{V(a)(b,c,d,e,f,g,l,n,m,q)}catch(x){Z(u);if(x!==x+0)throw x;W(1,0)}}function Xd(a,b,c,d,e,f,g,l,n,m,q,u,x,k,v,t){var G=Y();try{V(a)(b,c,d,e,f,g,l,n,m,q,u,x,k,v,t)}catch(H){Z(G);if(H!==H+0)throw H;W(1,0)}}
function Sd(a,b,c,d){var e=Y();try{V(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}function Ld(a,b,c,d,e,f,g,l){var n=Y();try{return $d(a,b,c,d,e,f,g,l)}catch(m){Z(n);if(m!==m+0)throw m;W(1,0)}}function Md(a){var b=Y();try{return ce(a)}catch(c){Z(b);if(c!==c+0)throw c;W(1,0)}}function Nd(a,b){var c=Y();try{return ae(a,b)}catch(d){Z(c);if(d!==d+0)throw d;W(1,0)}}function Yd(a,b,c,d,e,f,g){var l=Y();try{be(a,b,c,d,e,f,g)}catch(n){Z(l);if(n!==n+0)throw n;W(1,0)}}
function Od(a,b,c,d,e){var f=Y();try{return de(a,b,c,d,e)}catch(g){Z(f);if(g!==g+0)throw g;W(1,0)}}h.addRunDependency=Ea;h.removeRunDependency=Fa;h.FS_createPath=gc;h.FS_createLazyFile=jc;h.FS_createDevice=O;h.FS_createPreloadedFile=xb;h.FS_createDataFile=wb;h.FS_unlink=Wb;var ee;Da=function fe(){ee||ge();ee||(Da=fe)};
function ge(){function a(){if(!ee&&(ee=!0,h.calledRun=!0,!ra)){h.noFSInit||fc||(fc=!0,ec(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?O("/dev","stdin",h.stdin):Ub("/dev/tty","/dev/stdin"),h.stdout?O("/dev","stdout",null,h.stdout):Ub("/dev/tty","/dev/stdout"),h.stderr?O("/dev","stderr",null,h.stderr):Ub("/dev/tty1","/dev/stderr"),$b("/dev/stdin",0),$b("/dev/stdout",1),$b("/dev/stderr",1));Eb=!1;Oa(ya);aa(h);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(h.postRun)for("function"==
typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var b=h.postRun.shift();za.unshift(b)}Oa(za)}}if(!(0<Ba)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Aa();Oa(xa);0<Ba||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);a()},1)):a())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();ge();


  return moduleArg.ready
}

);
})();
export default Module;