
var Module = (() => {
  var _scriptDir = import.meta.url;
  
  return (
async function(moduleArg = {}) {

var h=moduleArg,aa,ba;h.ready=new Promise((a,b)=>{aa=a;ba=b});h.Xc=!0;h.Yc=!0;
"object"!==typeof WebAssembly&&"undefined"!==typeof WXWebAssembly&&(WXWebAssembly.RuntimeError=WXWebAssembly.RuntimeError||function(){class a extends Error{constructor(b){super(b);this instanceof a||(b=Object.setPrototypeOf,"function"===typeof b?b.call(Object,this,a.prototype):this.__proto__=a.prototype,"function"===typeof Error.captureStackTrace&&Error.captureStackTrace(this,a))}}Object.defineProperty(a.prototype,"name",{configurable:!0,writable:!0,value:"RuntimeError"});return a}(),function(){if("undefined"!==
typeof globalThis)return globalThis;var a=function(){return this}(),b=function(){try{var c=new Function}catch(d){return!1}return"function"===typeof c}();if(!a&&b)try{a=(new Function("return this"))()}catch(c){}if(!a){if("undefined"===typeof __webpack_public_path__&&"undefined"!==typeof global)return global;if("undefined"!==typeof window)return window;if("undefined"!==typeof self)return self}return a}().WebAssembly=WXWebAssembly);
var ca=Object.assign({},h),da="./this.program",ea=(a,b)=>{throw b;},fa="object"==typeof window,ha="function"==typeof importScripts,ia="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,p="",ja,ka,la;
if(ia){const {createRequire:a}=await import("module");var require=a(import.meta.url),fs=require("fs"),ma=require("path");ha?p=ma.dirname(p)+"/":p=require("url").fileURLToPath(new URL("./",import.meta.url));ja=(b,c)=>{b=na(b)?new URL(b):ma.normalize(b);return fs.readFileSync(b,c?void 0:"utf8")};la=b=>{b=ja(b,!0);b.buffer||(b=new Uint8Array(b));return b};ka=(b,c,d,e=!0)=>{b=na(b)?new URL(b):ma.normalize(b);fs.readFile(b,e?void 0:"utf8",(f,g)=>{f?d(f):c(e?g.buffer:g)})};
!h.thisProgram&&1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);ea=(b,c)=>{process.exitCode=b;throw c;};h.inspect=()=>"[Emscripten Module object]"}else if(fa||ha)ha?p=self.location.href:"undefined"!=typeof document&&document.currentScript&&(p=document.currentScript.src),_scriptDir&&(p=_scriptDir),0!==p.indexOf("blob:")?p=p.substr(0,p.replace(/[?#].*/,"").lastIndexOf("/")+1):p="",ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},
ha&&(la=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ka=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var oa=h.print||console.log.bind(console),pa=h.printErr||console.error.bind(console);Object.assign(h,ca);ca=null;h.thisProgram&&(da=h.thisProgram);h.quit&&(ea=h.quit);var qa;
h.wasmBinary&&(qa=h.wasmBinary);"object"!=typeof WebAssembly&&u("no native wasm support detected");var ra,sa=!1,x,y,z,ta,A,B,ua,va;function wa(){var a=ra.buffer;h.HEAP8=x=new Int8Array(a);h.HEAP16=z=new Int16Array(a);h.HEAPU8=y=new Uint8Array(a);h.HEAPU16=ta=new Uint16Array(a);h.HEAP32=A=new Int32Array(a);h.HEAPU32=B=new Uint32Array(a);h.HEAPF32=ua=new Float32Array(a);h.HEAPF64=va=new Float64Array(a)}var xa=[],ya=[],za=[],Aa=[];function Ba(){var a=h.preRun.shift();xa.unshift(a)}
var Ca=0,Da=null,Ea=null;function Fa(){Ca++;h.monitorRunDependencies&&h.monitorRunDependencies(Ca)}function Ga(){Ca--;h.monitorRunDependencies&&h.monitorRunDependencies(Ca);if(0==Ca&&(null!==Da&&(clearInterval(Da),Da=null),Ea)){var a=Ea;Ea=null;a()}}function u(a){if(h.onAbort)h.onAbort(a);a="Aborted("+a+")";pa(a);sa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}
var Ha=a=>a.startsWith("data:application/octet-stream;base64,"),na=a=>a.startsWith("file://"),Ia;if(h.locateFile){if(Ia="ooxmlcrypt.wasm?version=1.0.0",!Ha(Ia)){var Ja=Ia;Ia=h.locateFile?h.locateFile(Ja,p):p+Ja}}else Ia=(new URL("ooxmlcrypt.wasm?version=1.0.0",import.meta.url)).href;function Ka(a){if(a==Ia&&qa)return new Uint8Array(qa);if(la)return la(a);throw"both async and sync fetching of the wasm failed";}
function La(a){if(!qa&&(fa||ha)){if("function"==typeof fetch&&!na(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Ka(a));if(ka)return new Promise((b,c)=>{ka(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Ka(a))}function Ma(a,b,c){return La(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{pa(`failed to asynchronously prepare wasm: ${d}`);u(d)})}
function Na(a,b){var c=Ia;return qa||"function"!=typeof WebAssembly.instantiateStreaming||Ha(c)||na(c)||ia||"function"!=typeof fetch?Ma(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){pa(`wasm streaming compile failed: ${e}`);pa("falling back to ArrayBuffer instantiation");return Ma(c,a,b)}))}var C,E;function Oa(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Pa=a=>{for(;0<a.length;)a.shift()(h)},Qa=h.noExitRuntime||!1,Ra=[],Sa=0,Ta=0;
function Ua(a){this.Mb=a;this.qb=a-24;this.Ic=function(b){B[this.qb+4>>2]=b};this.ob=function(){return B[this.qb+4>>2]};this.Gc=function(b){B[this.qb+8>>2]=b};this.pc=function(b){x[this.qb+12>>0]=b?1:0};this.Ec=function(){return 0!=x[this.qb+12>>0]};this.qc=function(b){x[this.qb+13>>0]=b?1:0};this.vc=function(){return 0!=x[this.qb+13>>0]};this.kc=function(b,c){this.Gb(0);this.Ic(b);this.Gc(c)};this.Gb=function(b){B[this.qb+16>>2]=b};this.Dc=function(){return B[this.qb+16>>2]};this.Fc=function(){if(Va(this.ob()))return B[this.Mb>>
2];var b=this.Dc();return 0!==b?b:this.Mb}}
var Za=a=>{var b=Ta;if(!b)return Wa(0),0;var c=new Ua(b);c.Gb(b);var d=c.ob();if(!d)return Wa(0),b;for(var e in a){var f=a[e];if(0===f||f===d)break;if(Ya(f,d,c.qb+16))return Wa(f),b}Wa(d);return b},$a=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(ia)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}u("initRandomDevice")},ab=a=>(ab=$a())(a),
bb=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},G=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=bb(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},cb=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},db=a=>{if("/"===
a)return"/";a=G(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)};function eb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=bb(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}
var fb="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,H=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&fb)return fb.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
gb=[],hb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},ib=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&
63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e};function jb(a,b){var c=Array(hb(a)+1);a=ib(a,c,0,c.length);b&&(c.length=a);return c}var kb=[];function lb(a,b){kb[a]={input:[],output:[],Ab:b};mb(a,nb)}
var nb={open(a){var b=kb[a.node.rdev];if(!b)throw new I(43);a.tty=b;a.seekable=!1},close(a){a.tty.Ab.fsync(a.tty)},fsync(a){a.tty.Ab.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Ab.ic)throw new I(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.Ab.ic(a.tty)}catch(l){throw new I(29);}if(void 0===g&&0===e)throw new I(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Ab.$b)throw new I(60);try{for(var e=0;e<d;e++)a.tty.Ab.$b(a.tty,b[c+
e])}catch(f){throw new I(29);}d&&(a.node.timestamp=Date.now());return e}},ob={ic(){a:{if(!gb.length){var a=null;if(ia){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c?a=b.slice(0,c).toString("utf-8"):a=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}gb=jb(a,!0)}a=
gb.shift()}return a},$b(a,b){null===b||10===b?(oa(H(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(oa(H(a.output,0)),a.output=[])},xc(){return{Sc:25856,Uc:5,Rc:191,Tc:35387,Qc:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},yc(){return 0},zc(){return[24,80]}},pb={$b(a,b){null===b||10===b?(pa(H(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(pa(H(a.output,0)),a.output=[])}};
function qb(a,b){var c=a.ib?a.ib.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.ib,a.ib=new Uint8Array(b),0<a.lb&&a.ib.set(c.subarray(0,a.lb),0))}
var J={ub:null,tb(){return J.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new I(63);J.ub||(J.ub={dir:{node:{sb:J.hb.sb,pb:J.hb.pb,lookup:J.hb.lookup,Sb:J.hb.Sb,rename:J.hb.rename,unlink:J.hb.unlink,rmdir:J.hb.rmdir,readdir:J.hb.readdir,symlink:J.hb.symlink},stream:{Db:J.jb.Db}},file:{node:{sb:J.hb.sb,pb:J.hb.pb},stream:{Db:J.jb.Db,read:J.jb.read,write:J.jb.write,Pb:J.jb.Pb,Zb:J.jb.Zb,nc:J.jb.nc}},link:{node:{sb:J.hb.sb,pb:J.hb.pb,readlink:J.hb.readlink},
stream:{}},ec:{node:{sb:J.hb.sb,pb:J.hb.pb},stream:rb}});c=sb(a,b,c,d);K(c.mode)?(c.hb=J.ub.dir.node,c.jb=J.ub.dir.stream,c.ib={}):32768===(c.mode&61440)?(c.hb=J.ub.file.node,c.jb=J.ub.file.stream,c.lb=0,c.ib=null):40960===(c.mode&61440)?(c.hb=J.ub.link.node,c.jb=J.ub.link.stream):8192===(c.mode&61440)&&(c.hb=J.ub.ec.node,c.jb=J.ub.ec.stream);c.timestamp=Date.now();a&&(a.ib[b]=c,a.timestamp=c.timestamp);return c},Vc(a){return a.ib?a.ib.subarray?a.ib.subarray(0,a.lb):new Uint8Array(a.ib):new Uint8Array(0)},
hb:{sb(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;K(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.lb:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.uc=4096;b.blocks=Math.ceil(b.size/b.uc);return b},pb(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.lb!=b))if(0==
b)a.ib=null,a.lb=0;else{var c=a.ib;a.ib=new Uint8Array(b);c&&a.ib.set(c.subarray(0,Math.min(b,a.lb)));a.lb=b}},lookup(){throw tb[44];},Sb(a,b,c,d){return J.createNode(a,b,c,d)},rename(a,b,c){if(K(a.mode)){try{var d=ub(b,c)}catch(f){}if(d)for(var e in d.ib)throw new I(55);}delete a.parent.ib[a.name];a.parent.timestamp=Date.now();a.name=c;b.ib[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink(a,b){delete a.ib[b];a.timestamp=Date.now()},rmdir(a,b){var c=ub(a,b),d;for(d in c.ib)throw new I(55);delete a.ib[b];
a.timestamp=Date.now()},readdir(a){var b=[".",".."],c;for(c in a.ib)a.ib.hasOwnProperty(c)&&b.push(c);return b},symlink(a,b,c){a=J.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new I(28);return a.link}},jb:{read(a,b,c,d,e){var f=a.node.ib;if(e>=a.node.lb)return 0;a=Math.min(a.node.lb-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===x.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=
Date.now();if(b.subarray&&(!a.ib||a.ib.subarray)){if(f)return a.ib=b.subarray(c,c+d),a.lb=d;if(0===a.lb&&0===e)return a.ib=b.slice(c,c+d),a.lb=d;if(e+d<=a.lb)return a.ib.set(b.subarray(c,c+d),e),d}qb(a,e+d);if(a.ib.subarray&&b.subarray)a.ib.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.ib[e+f]=b[c+f];a.lb=Math.max(a.lb,e+d);return d},Db(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.lb);if(0>b)throw new I(28);return b},Pb(a,b,c){qb(a.node,b+c);a.node.lb=Math.max(a.node.lb,
b+c)},Zb(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new I(43);a=a.node.ib;if(e&2||a.buffer!==x.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;u();b=void 0;if(!b)throw new I(48);x.set(a,b)}else c=!1,b=a.byteOffset;return{qb:b,rb:c}},nc(a,b,c,d){J.jb.write(a,b,0,d,c,!1);return 0}}},vb=(a,b,c)=>{var d=`al ${a}`;ka(a,e=>{e||u(`Loading data file "${a}" failed (no arrayBuffer).`);b(new Uint8Array(e));d&&Ga(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;
});d&&Fa(d)},wb=h.preloadPlugins||[],xb=(a,b,c,d)=>{"undefined"!=typeof Browser&&Browser.kc();var e=!1;wb.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},zb=(a,b,c,d,e,f,g,l,m,n)=>{function q(k){function v(r){n&&n();l||yb(a,b,r,d,e,m);f&&f();Ga(w)}xb(k,t,v,()=>{g&&g();Ga(w)})||v(k)}var t=b?eb(G(a+"/"+b)):a,w=`cp ${t}`;Fa(w);"string"==typeof c?vb(c,k=>q(k),g):q(c)},Ab=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Bb=null,Cb={},Db=[],Eb=1,Fb=null,Gb=!0,I=null,tb={};
function M(a,b={}){a=eb(a);if(!a)return{path:"",node:null};b=Object.assign({fc:!0,ac:0},b);if(8<b.ac)throw new I(32);a=a.split("/").filter(g=>!!g);for(var c=Bb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=ub(c,a[e]);d=G(d+"/"+a[e]);c.Hb&&(!f||f&&b.fc)&&(c=c.Hb.root);if(!f||b.Nb)for(f=0;40960===(c.mode&61440);)if(c=Hb(d),d=eb(cb(d),c),c=M(d,{ac:b.ac+1}).node,40<f++)throw new I(32);}return{path:d,node:c}}
function Ib(a){for(var b;;){if(a===a.parent)return a=a.tb.mc,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Jb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Fb.length}function Kb(a){var b=Jb(a.parent.id,a.name);if(Fb[b]===a)Fb[b]=a.Ib;else for(b=Fb[b];b;){if(b.Ib===a){b.Ib=a.Ib;break}b=b.Ib}}
function ub(a,b){var c;if(c=(c=Lb(a,"x"))?c:a.hb.lookup?0:2)throw new I(c,a);for(c=Fb[Jb(a.id,b)];c;c=c.Ib){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.hb.lookup(a,b)}function sb(a,b,c,d){a=new Mb(a,b,c,d);b=Jb(a.parent.id,a.name);a.Ib=Fb[b];return Fb[b]=a}function K(a){return 16384===(a&61440)}function Nb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function Lb(a,b){if(Gb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Ob(a,b){try{return ub(a,b),20}catch(c){}return Lb(a,"wx")}function Pb(a,b,c){try{var d=ub(a,b)}catch(e){return e.kb}if(a=Lb(a,"wx"))return a;if(c){if(!K(d.mode))return 54;if(d===d.parent||"/"===Ib(d))return 10}else if(K(d.mode))return 31;return 0}function Qb(){for(var a=0;4096>=a;a++)if(!Db[a])return a;throw new I(33);}
function Rb(a){a=Db[a];if(!a)throw new I(8);return a}function Sb(a,b=-1){Tb||(Tb=function(){this.ob={}},Tb.prototype={},Object.defineProperties(Tb.prototype,{object:{get(){return this.node},set(c){this.node=c}},flags:{get(){return this.ob.flags},set(c){this.ob.flags=c}},position:{get(){return this.ob.position},set(c){this.ob.position=c}}}));a=Object.assign(new Tb,a);-1==b&&(b=Qb());a.fd=b;return Db[b]=a}var rb={open(a){a.jb=Cb[a.node.rdev].jb;a.jb.open&&a.jb.open(a)},Db(){throw new I(70);}};
function mb(a,b){Cb[a]={jb:b}}function Ub(a,b){var c="/"===b,d=!b;if(c&&Bb)throw new I(10);if(!c&&!d){var e=M(b,{fc:!1});b=e.path;e=e.node;if(e.Hb)throw new I(10);if(!K(e.mode))throw new I(54);}b={type:a,$c:{},mc:b,Hc:[]};a=a.tb(b);a.tb=b;b.root=a;c?Bb=a:e&&(e.Hb=b,e.tb&&e.tb.Hc.push(b));return a}function Vb(a,b,c){var d=M(a,{parent:!0}).node;a=db(a);if(!a||"."===a||".."===a)throw new I(28);var e=Ob(d,a);if(e)throw new I(e);if(!d.hb.Sb)throw new I(63);return d.hb.Sb(d,a,b,c)}
function N(a,b){return Vb(a,(void 0!==b?b:511)&1023|16384,0)}function Wb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Vb(a,b|8192,c)}function Xb(a,b){if(!eb(a))throw new I(44);var c=M(b,{parent:!0}).node;if(!c)throw new I(44);b=db(b);var d=Ob(c,b);if(d)throw new I(d);if(!c.hb.symlink)throw new I(63);c.hb.symlink(c,b,a)}function Yb(a){var b=M(a,{parent:!0}).node;a=db(a);var c=ub(b,a),d=Pb(b,a,!0);if(d)throw new I(d);if(!b.hb.rmdir)throw new I(63);if(c.Hb)throw new I(10);b.hb.rmdir(b,a);Kb(c)}
function Zb(a){var b=M(a,{parent:!0}).node;if(!b)throw new I(44);a=db(a);var c=ub(b,a),d=Pb(b,a,!1);if(d)throw new I(d);if(!b.hb.unlink)throw new I(63);if(c.Hb)throw new I(10);b.hb.unlink(b,a);Kb(c)}function Hb(a){a=M(a).node;if(!a)throw new I(44);if(!a.hb.readlink)throw new I(28);return eb(Ib(a.parent),a.hb.readlink(a))}function $b(a,b){a="string"==typeof a?M(a,{Nb:!0}).node:a;if(!a.hb.pb)throw new I(63);a.hb.pb(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function ac(a,b,c){if(""===a)throw new I(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=G(a);try{e=M(a,{Nb:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new I(20);}else e=Vb(a,c,0),d=!0;if(!e)throw new I(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&!K(e.mode))throw new I(54);if(!d&&(c=
e?40960===(e.mode&61440)?32:K(e.mode)&&("r"!==Nb(b)||b&512)?31:Lb(e,Nb(b)):44))throw new I(c);if(b&512&&!d){c=e;c="string"==typeof c?M(c,{Nb:!0}).node:c;if(!c.hb.pb)throw new I(63);if(K(c.mode))throw new I(31);if(32768!==(c.mode&61440))throw new I(28);if(d=Lb(c,"w"))throw new I(d);c.hb.pb(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Sb({node:e,path:Ib(e),flags:b,seekable:!0,position:0,jb:e.jb,Oc:[],error:!1});e.jb.open&&e.jb.open(e);!h.logReadFiles||b&1||(bc||(bc={}),a in bc||(bc[a]=1));return e}
function cc(a){if(null===a.fd)throw new I(8);a.Cb&&(a.Cb=null);try{a.jb.close&&a.jb.close(a)}catch(b){throw b;}finally{Db[a.fd]=null}a.fd=null}function dc(a,b,c){if(null===a.fd)throw new I(8);if(!a.seekable||!a.jb.Db)throw new I(70);if(0!=c&&1!=c&&2!=c)throw new I(28);a.position=a.jb.Db(a,b,c);a.Oc=[];return a.position}
function ec(a,b,c,d,e,f){if(0>d||0>e)throw new I(28);if(null===a.fd)throw new I(8);if(0===(a.flags&2097155))throw new I(8);if(K(a.node.mode))throw new I(31);if(!a.jb.write)throw new I(28);a.seekable&&a.flags&1024&&dc(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new I(70);b=a.jb.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function fc(){I||(I=function(a,b){this.name="ErrnoError";this.node=b;this.Jc=function(c){this.kb=c};this.Jc(a);this.message="FS error"},I.prototype=Error(),I.prototype.constructor=I,[44].forEach(a=>{tb[a]=new I(a);tb[a].stack="<generic error, no stack>"}))}var gc;function hc(a,b){a="string"==typeof a?a:Ib(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=G(a+"/"+c);try{N(d)}catch(e){}a=d}}return d}
function ic(a,b,c,d){a=G(("string"==typeof a?a:Ib(a))+"/"+b);c=Ab(c,d);return Vb(a,(void 0!==c?c:438)&4095|32768,0)}function yb(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:Ib(a),g=b?G(a+"/"+b):a);a=Ab(d,e);g=Vb(g,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}$b(g,a|146);b=ac(g,577);ec(b,c,0,c.length,0,f);cc(b);$b(g,a)}return g}
function O(a,b,c,d){a=G(("string"==typeof a?a:Ib(a))+"/"+b);b=Ab(!!c,!!d);O.lc||(O.lc=64);var e=O.lc++<<8|0;mb(e,{open(f){f.seekable=!1},close(){d&&d.buffer&&d.buffer.length&&d(10)},read(f,g,l,m){for(var n=0,q=0;q<m;q++){try{var t=c()}catch(w){throw new I(29);}if(void 0===t&&0===n)throw new I(6);if(null===t||void 0===t)break;n++;g[l+q]=t}n&&(f.node.timestamp=Date.now());return n},write(f,g,l,m){for(var n=0;n<m;n++)try{d(g[l+n])}catch(q){throw new I(29);}m&&(f.node.timestamp=Date.now());return n}});
return Wb(a,b,e)}function jc(a){if(!(a.Ac||a.Bc||a.link||a.ib)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ja)try{a.ib=jb(ja(a.url),!0),a.lb=a.ib.length}catch(b){throw new I(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function kc(a,b,c,d,e){function f(){this.Yb=!1;this.ob=[]}f.prototype.get=function(q){if(!(q>this.length-1||0>q)){var t=q%this.chunkSize;return this.jc(q/this.chunkSize|0)[t]}};f.prototype.Gb=function(q){this.jc=q};f.prototype.dc=function(){var q=new XMLHttpRequest;q.open("HEAD",c,!1);q.send(null);if(!(200<=q.status&&300>q.status||304===q.status))throw Error("Couldn't load "+c+". Status: "+q.status);var t=Number(q.getResponseHeader("Content-length")),w,k=(w=q.getResponseHeader("Accept-Ranges"))&&
"bytes"===w;q=(w=q.getResponseHeader("Content-Encoding"))&&"gzip"===w;var v=1048576;k||(v=t);var r=this;r.Gb(D=>{var F=D*v,L=(D+1)*v-1;L=Math.min(L,t-1);if("undefined"==typeof r.ob[D]){var Xa=r.ob;if(F>L)throw Error("invalid range ("+F+", "+L+") or no bytes requested!");if(L>t-1)throw Error("only "+t+" bytes available! programmer error!");var S=new XMLHttpRequest;S.open("GET",c,!1);t!==v&&S.setRequestHeader("Range","bytes="+F+"-"+L);S.responseType="arraybuffer";S.overrideMimeType&&S.overrideMimeType("text/plain; charset=x-user-defined");
S.send(null);if(!(200<=S.status&&300>S.status||304===S.status))throw Error("Couldn't load "+c+". Status: "+S.status);F=void 0!==S.response?new Uint8Array(S.response||[]):jb(S.responseText||"",!0);Xa[D]=F}if("undefined"==typeof r.ob[D])throw Error("doXHR failed!");return r.ob[D]});if(q||!t)v=t=1,v=t=this.jc(0).length,oa("LazyFiles on gzip forces download of the whole file when length is accessed");this.sc=t;this.rc=v;this.Yb=!0};if("undefined"!=typeof XMLHttpRequest){if(!ha)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";
var g=new f;Object.defineProperties(g,{length:{get:function(){this.Yb||this.dc();return this.sc}},chunkSize:{get:function(){this.Yb||this.dc();return this.rc}}});var l=void 0}else l=c,g=void 0;var m=ic(a,b,d,e);g?m.ib=g:l&&(m.ib=null,m.url=l);Object.defineProperties(m,{lb:{get:function(){return this.ib.length}}});var n={};Object.keys(m.jb).forEach(q=>{var t=m.jb[q];n[q]=function(){jc(m);return t.apply(null,arguments)}});n.read=(q,t,w,k,v)=>{jc(m);q=q.node.ib;if(v>=q.length)t=0;else{k=Math.min(q.length-
v,k);if(q.slice)for(var r=0;r<k;r++)t[w+r]=q[v+r];else for(r=0;r<k;r++)t[w+r]=q.get(v+r);t=k}return t};n.Zb=()=>{jc(m);u();throw new I(48);};m.jb=n;return m}var P={},Tb,bc;
function lc(a,b){if(1===a.type&&a.nb)throw new I(53);var c=a.Jb.shift();if(!c){if(1===a.type){a=a.wb[a.yb+":"+a.zb];if(!a)throw new I(53);if(a.socket.readyState===a.socket.CLOSING||a.socket.readyState===a.socket.CLOSED)return null}throw new I(6);}var d=c.data.byteLength||c.data.length,e=c.data.byteOffset||0,f=c.data.buffer||c.data;b=Math.min(b,d);var g={buffer:new Uint8Array(f,e,b),mb:c.mb,port:c.port};1===a.type&&b<d&&(c.data=new Uint8Array(f,e+b,d-b),a.Jb.unshift(c));return g}
function mc(a,b,c,d,e,f){if(2===a.type){if(void 0===e||void 0===f)e=a.yb,f=a.zb;if(void 0===e||void 0===f)throw new I(17);}else e=a.yb,f=a.zb;var g=a.wb[e+":"+f];if(1===a.type){if(!g||g.socket.readyState===g.socket.CLOSING||g.socket.readyState===g.socket.CLOSED)throw new I(53);if(g.socket.readyState===g.socket.CONNECTING)throw new I(6);}ArrayBuffer.isView(b)&&(c+=b.byteOffset,b=b.buffer);b=b.slice(c,c+d);if(2===a.type&&(!g||g.socket.readyState!==g.socket.OPEN))return g&&g.socket.readyState!==g.socket.CLOSING&&
g.socket.readyState!==g.socket.CLOSED||(g=nc(a,e,f)),g.Qb.push(b),d;try{return g.socket.send(b),d}catch(l){throw new I(28);}}
function oc(a,b){function c(){h.websocket.emit("open",a.stream.fd);try{for(var f=b.Qb.shift();f;)b.socket.send(f),f=b.Qb.shift()}catch(g){b.socket.close()}}function d(f){if("string"==typeof f)f=(new TextEncoder).encode(f);else{void 0!==f.byteLength||u();if(0==f.byteLength)return;f=new Uint8Array(f)}var g=e;e=!1;g&&10===f.length&&255===f[0]&&255===f[1]&&255===f[2]&&255===f[3]&&112===f[4]&&111===f[5]&&114===f[6]&&116===f[7]?(f=f[8]<<8|f[9],delete a.wb[b.mb+":"+b.port],b.port=f,a.wb[b.mb+":"+b.port]=
b):(a.Jb.push({mb:b.mb,port:b.port,data:f}),h.websocket.emit("message",a.stream.fd))}var e=!0;ia?(b.socket.on("open",c),b.socket.on("message",function(f,g){g&&d((new Uint8Array(f)).buffer)}),b.socket.on("close",function(){h.websocket.emit("close",a.stream.fd)}),b.socket.on("error",function(){a.error=14;h.websocket.emit("error",[a.stream.fd,a.error,"ECONNREFUSED: Connection refused"])})):(b.socket.onopen=c,b.socket.onclose=function(){h.websocket.emit("close",a.stream.fd)},b.socket.onmessage=function(f){d(f.data)},
b.socket.onerror=function(){a.error=14;h.websocket.emit("error",[a.stream.fd,a.error,"ECONNREFUSED: Connection refused"])})}
function nc(a,b,c){if("object"==typeof b){var d=b;c=b=null}if(d)if(d._socket)b=d._socket.remoteAddress,c=d._socket.remotePort;else{c=/ws[s]?:\/\/([^:]+):(\d+)/.exec(d.url);if(!c)throw Error("WebSocket URL must be in the format ws(s)://address:port");b=c[1];c=parseInt(c[2],10)}else try{var e=h.websocket&&"object"===typeof h.websocket,f="ws://";e&&"string"===typeof h.websocket.url&&(f=h.websocket.url);if("ws://"===f||"wss://"===f){var g=b.split("/");f=f+g[0]+":"+c+"/"+g.slice(1).join("/")}g="binary";
e&&"string"===typeof h.websocket.subprotocol&&(g=h.websocket.subprotocol);var l=void 0;"null"!==g&&(l=g=g.replace(/^ +| +$/g,"").split(/ *, */));e&&null===h.websocket.subprotocol&&(l=void 0);d=new (ia?require("ws"):WebSocket)(f,l);d.binaryType="arraybuffer"}catch(m){throw new I(23);}b={mb:b,port:c,socket:d,Qb:[]};a.wb[b.mb+":"+b.port]=b;oc(a,b);2===a.type&&"undefined"!=typeof a.Lb&&b.Qb.push(new Uint8Array([255,255,255,255,112,111,114,116,(a.Lb&65280)>>8,a.Lb&255]));return b}
var Q={tb(){h.websocket=h.websocket&&"object"===typeof h.websocket?h.websocket:{};h.websocket.Xb={};h.websocket.on=function(a,b){"function"===typeof b&&(this.Xb[a]=b);return this};h.websocket.emit=function(a,b){"function"===typeof this.Xb[a]&&this.Xb[a].call(this,b)};return sb(null,"/",16895,0)},createSocket(a,b,c){b&=-526337;if(1==b&&c&&6!=c)throw new I(66);a={family:a,type:b,protocol:c,nb:null,error:null,wb:{},pending:[],Jb:[],Ob:Q.Pc};b=Q.Tb();c=sb(Q.root,b,49152,0);c.Kb=a;b=Sb({path:b,node:c,
flags:2,seekable:!1,jb:Q.jb});a.stream=b;return a},jb:{Ub(a){a=a.node.Kb;return a.Ob.Ub(a)},Rb(a,b,c){a=a.node.Kb;return a.Ob.Rb(a,b,c)},read(a,b,c,d){a=lc(a.node.Kb,d);if(!a)return 0;b.set(a.buffer,c);return a.buffer.length},write(a,b,c,d){return mc(a.node.Kb,b,c,d)},close(a){a=a.node.Kb;a.Ob.close(a)}},Tb(){Q.Tb.current||(Q.Tb.current=0);return"socket["+Q.Tb.current++ +"]"},Pc:{Ub(a){if(1===a.type&&a.nb)return a.pending.length?65:0;var b=0,c=1===a.type?a.wb[a.yb+":"+a.zb]:null;if(a.Jb.length||!c||
c&&c.socket.readyState===c.socket.CLOSING||c&&c.socket.readyState===c.socket.CLOSED)b|=65;if(!c||c&&c.socket.readyState===c.socket.OPEN)b|=4;if(c&&c.socket.readyState===c.socket.CLOSING||c&&c.socket.readyState===c.socket.CLOSED)b|=16;return b},Rb(a,b,c){switch(b){case 21531:return b=0,a.Jb.length&&(b=a.Jb[0].data.length),A[c>>2]=b,0;default:return 28}},close(a){if(a.nb){try{a.nb.close()}catch(e){}a.nb=null}for(var b=Object.keys(a.wb),c=0;c<b.length;c++){var d=a.wb[b[c]];try{d.socket.close()}catch(e){}delete a.wb[d.mb+
":"+d.port]}return 0},bind(a,b,c){if("undefined"!=typeof a.bc||"undefined"!=typeof a.Lb)throw new I(28);a.bc=b;a.Lb=c;if(2===a.type){a.nb&&(a.nb.close(),a.nb=null);try{a.Ob.listen(a,0)}catch(d){if("ErrnoError"!==d.name)throw d;if(138!==d.kb)throw d;}}},connect(a,b,c){if(a.nb)throw new I(138);if("undefined"!=typeof a.yb&&"undefined"!=typeof a.zb){var d=a.wb[a.yb+":"+a.zb];if(d){if(d.socket.readyState===d.socket.CONNECTING)throw new I(7);throw new I(30);}}b=nc(a,b,c);a.yb=b.mb;a.zb=b.port;throw new I(26);
},listen(a){if(!ia)throw new I(138);if(a.nb)throw new I(28);var b=require("ws").Server;a.nb=new b({host:a.bc,port:a.Lb});h.websocket.emit("listen",a.stream.fd);a.nb.on("connection",function(c){if(1===a.type){var d=Q.createSocket(a.family,a.type,a.protocol);c=nc(d,c);d.yb=c.mb;d.zb=c.port;a.pending.push(d);h.websocket.emit("connection",d.stream.fd)}else nc(a,c),h.websocket.emit("connection",a.stream.fd)});a.nb.on("close",function(){h.websocket.emit("close",a.stream.fd);a.nb=null});a.nb.on("error",
function(){a.error=23;h.websocket.emit("error",[a.stream.fd,a.error,"EHOSTUNREACH: Host is unreachable"])})},accept(a){if(!a.nb||!a.pending.length)throw new I(28);var b=a.pending.shift();b.stream.flags=a.stream.flags;return b},Wc(a,b){if(b){if(void 0===a.yb||void 0===a.zb)throw new I(53);b=a.yb;a=a.zb}else b=a.bc||0,a=a.Lb||0;return{mb:b,port:a}}}},pc=a=>{a=(a=Db[a])&&49152===(a.node.mode&49152)?a.node.Kb:null;if(!a)throw new I(8);return a},qc=a=>(a&255)+"."+(a>>8&255)+"."+(a>>16&255)+"."+(a>>24&
255),sc=(a,b)=>{var c=z[a>>1],d=rc(ta[a+2>>1]);switch(c){case 2:if(16!==b)return{kb:28};var e=A[a+4>>2];e=qc(e);break;case 10:if(28!==b)return{kb:28};e=[A[a+8>>2],A[a+12>>2],A[a+16>>2],A[a+20>>2]];a:{a="";var f,g=b=0,l=0,m=0;e=[e[0]&65535,e[0]>>16,e[1]&65535,e[1]>>16,e[2]&65535,e[2]>>16,e[3]&65535,e[3]>>16];var n=!0;for(f=0;5>f;f++)if(0!==e[f]){n=!1;break}if(n){f=qc(e[6]|e[7]<<16);if(-1===e[5]){e="::ffff:"+f;break a}if(0===e[5]){"0.0.0.0"===f&&(f="");"0.0.0.1"===f&&(f="1");e="::"+f;break a}}for(f=
0;8>f;f++)0===e[f]&&(1<f-g&&(m=0),g=f,m++),m>b&&(b=m,l=f-b+1);for(f=0;8>f;f++)1<b&&0===e[f]&&f>=l&&f<l+b?f===l&&(a+=":",0===l&&(a+=":")):(a+=Number(rc(e[f]&65535)).toString(16),a+=7>f?":":"");e=a}break;default:return{kb:5}}return{family:c,mb:e,port:d}},tc=a=>{a=a.split(".");for(var b=0;4>b;b++){var c=Number(a[b]);if(isNaN(c))return null;a[b]=c}return(a[0]|a[1]<<8|a[2]<<16|a[3]<<24)>>>0},vc=a=>{var b,c,d=[];if(!/^((?=.*::)(?!.*::.+::)(::)?([\dA-F]{1,4}:(:|\b)|){5}|([\dA-F]{1,4}:){6})((([\dA-F]{1,4}((?!\3)::|:\b|$))|(?!\2\3)){2}|(((2[0-4]|1\d|[1-9])?\d|25[0-5])\.?\b){4})$/i.test(a))return null;
if("::"===a)return[0,0,0,0,0,0,0,0];a=a.startsWith("::")?a.replace("::","Z:"):a.replace("::",":Z:");0<a.indexOf(".")?(a=a.replace(RegExp("[.]","g"),":"),a=a.split(":"),a[a.length-4]=parseInt(a[a.length-4])+256*parseInt(a[a.length-3]),a[a.length-3]=parseInt(a[a.length-2])+256*parseInt(a[a.length-1]),a=a.slice(0,a.length-2)):a=a.split(":");for(b=c=0;b<a.length;b++)if("string"==typeof a[b])if("Z"===a[b]){for(c=0;c<8-a.length+1;c++)d[b+c]=0;--c}else d[b+c]=uc(parseInt(a[b],16));else d[b+c]=a[b];return[d[1]<<
16|d[0],d[3]<<16|d[2],d[5]<<16|d[4],d[7]<<16|d[6]]},wc=1,xc={},yc={};function zc(a){var b=tc(a);if(null!==b)return a;b=vc(a);if(null!==b)return a;xc[a]?b=xc[a]:(b=wc++,65535>b||u("exceeded max address mappings of 65535"),b="172.29."+(b&255)+"."+(b&65280),yc[b]=a,xc[a]=b);return b}var Ac=(a,b,c)=>{if(c&&0===a)return null;a=sc(a,b);if(a.kb)throw new I(a.kb);b=a.mb;a.mb=(yc[b]?yc[b]:null)||a.mb;return a};
function Bc(a,b){if("/"===b.charAt(0))return b;a=-100===a?"/":Rb(a).path;if(0==b.length)throw new I(44);return G(a+"/"+b)}var Cc=void 0;function Dc(){var a=A[+Cc>>2];Cc+=4;return a}
var Ec,R=a=>{for(var b="";y[a];)b+=Ec[y[a++]];return b},Fc={},Gc={},Hc={},T,Ic=a=>{throw new T(a);},Jc,Lc=(a,b)=>{function c(l){l=b(l);if(l.length!==d.length)throw new Jc("Mismatched type converter count");for(var m=0;m<d.length;++m)Kc(d[m],l[m])}var d=[];d.forEach(function(l){Hc[l]=a});var e=Array(a.length),f=[],g=0;a.forEach((l,m)=>{Gc.hasOwnProperty(l)?e[m]=Gc[l]:(f.push(l),Fc.hasOwnProperty(l)||(Fc[l]=[]),Fc[l].push(()=>{e[m]=Gc[l];++g;g===f.length&&c(e)}))});0===f.length&&c(e)};
function Mc(a,b,c={}){var d=b.name;if(!a)throw new T(`type "${d}" must have a positive integer typeid pointer`);if(Gc.hasOwnProperty(a)){if(c.wc)return;throw new T(`Cannot register type '${d}' twice`);}Gc[a]=b;delete Hc[a];Fc.hasOwnProperty(a)&&(b=Fc[a],delete Fc[a],b.forEach(e=>e()))}function Kc(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");Mc(a,b,c)}function Nc(){this.rb=[void 0];this.hc=[]}
var U=new Nc,Oc=a=>{a>=U.ob&&0===--U.get(a).oc&&U.Gb(a)},Pc=a=>{if(!a)throw new T("Cannot use deleted val. handle = "+a);return U.get(a).value},Qc=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:return U.Pb({oc:1,value:a})}};function Rc(a){return this.fromWireType(A[a>>2])}
var Sc=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(ua[c>>2])};case 8:return function(c){return this.fromWireType(va[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Tc=a=>{if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a},Uc=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Vc(a,b){a=Tc(a);return{[a]:function(){return b.apply(this,arguments)}}[a]}
function Wc(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=Vc(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
var Xc=(a,b)=>{if(void 0===h[a].vb){var c=h[a];h[a]=function(){if(!h[a].vb.hasOwnProperty(arguments.length))throw new T(`Function '${b}' called with an invalid number of arguments (${arguments.length}) - expects one of (${h[a].vb})!`);return h[a].vb[arguments.length].apply(this,arguments)};h[a].vb=[];h[a].vb[c.tc]=c}},Yc=(a,b,c)=>{if(h.hasOwnProperty(a)){if(void 0===c||void 0!==h[a].vb&&void 0!==h[a].vb[c])throw new T(`Cannot register public name '${a}' twice`);Xc(a,a);if(h.hasOwnProperty(c))throw new T(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
h[a].vb[c]=b}else h[a]=b,void 0!==c&&(h[a].Zc=c)},Zc=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(B[b+4*d>>2]);return c},$c=[],ad,V=a=>{var b=$c[a];b||(a>=$c.length&&($c.length=a+1),$c[a]=b=ad.get(a));return b},bd=(a,b)=>{var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=h["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=V(b).apply(null,c);return d}},cd=(a,b)=>{a=R(a);var c=a.includes("j")?bd(a,b):V(b);if("function"!=typeof c)throw new T(`unknown function pointer with signature ${a}: ${b}`);
return c},dd,gd=a=>{a=ed(a);var b=R(a);fd(a);return b},hd=(a,b)=>{function c(f){e[f]||Gc[f]||(Hc[f]?Hc[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new dd(`${a}: `+d.map(gd).join([", "]));},jd=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?(")"==a[a.length-1]||u("Parentheses for argument names should match."),a.substr(0,b)):a},kd=(a,b,c)=>{switch(b){case 1:return c?d=>x[d>>0]:d=>y[d>>0];case 2:return c?d=>z[d>>1]:d=>ta[d>>1];case 4:return c?d=>A[d>>2]:d=>B[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);
}};function ld(a){return this.fromWireType(B[a>>2])}
var md="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,nd=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&ta[c];)++c;c<<=1;if(32<c-a&&md)return md.decode(y.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=z[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},od=(a,b,c)=>{void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)z[b>>1]=a.charCodeAt(e),b+=2;z[b>>1]=0;return b-d},pd=a=>2*a.length,qd=(a,b)=>{for(var c=0,d="";!(c>=b/
4);){var e=A[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},rd=(a,b,c)=>{void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var g=a.charCodeAt(++e);f=65536+((f&1023)<<10)|g&1023}A[b>>2]=f;b+=4;if(b+4>c)break}A[b>>2]=0;return b-d},sd=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},td={},
ud=a=>{var b=td[a];return void 0===b?R(a):b},vd=[],wd=()=>"object"==typeof globalThis?globalThis:Function("return this")(),xd=a=>{var b=vd.length;vd.push(a);return b},yd=(a,b)=>{var c=Gc[a];if(void 0===c)throw a=b+" has unknown type "+gd(a),new T(a);return c},zd=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=yd(B[b+4*d>>2],"parameter "+d);return c},Ad=a=>{for(var b="",c=0;c<a;++c)b+=(0!==c?", ":"")+"arg"+c;var d="return function emval_allocator_"+a+"(constructor, argTypes, args) {\n  var HEAPU32 = getMemory();\n";
for(c=0;c<a;++c)d+="var argType"+c+" = requireRegisteredType(HEAPU32[((argTypes)>>2)], 'parameter "+c+"');\nvar arg"+c+" = argType"+c+".readValueFromPointer(args);\nargs += argType"+c+"['argPackAdvance'];\nargTypes += 4;\n";return(new Function("requireRegisteredType","Module","valueToHandle","getMemory",d+("var obj = new constructor("+b+");\nreturn valueToHandle(obj);\n}\n")))(yd,h,Qc,()=>B)},Bd={},Cd={},Ed=()=>{if(!Dd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",
LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Cd)void 0===Cd[b]?delete a[b]:a[b]=Cd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Dd=c}return Dd},Dd,Fd=a=>0===a%4&&(0!==a%100||0===a%400),Gd=[31,29,31,30,31,30,31,31,30,31,30,31],Hd=[31,28,31,30,31,30,31,31,30,31,30,31],Id=(a,b,c,d)=>{function e(k,v,r){for(k="number"==typeof k?k.toString():k||"";k.length<v;)k=r[0]+k;return k}function f(k,v){return e(k,
v,"0")}function g(k,v){function r(F){return 0>F?-1:0<F?1:0}var D;0===(D=r(k.getFullYear()-v.getFullYear()))&&0===(D=r(k.getMonth()-v.getMonth()))&&(D=r(k.getDate()-v.getDate()));return D}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-
1,11,30)}}function m(k){var v=k.Eb;for(k=new Date((new Date(k.Fb+1900,0,1)).getTime());0<v;){var r=k.getMonth(),D=(Fd(k.getFullYear())?Gd:Hd)[r];if(v>D-k.getDate())v-=D-k.getDate()+1,k.setDate(1),11>r?k.setMonth(r+1):(k.setMonth(0),k.setFullYear(k.getFullYear()+1));else{k.setDate(k.getDate()+v);break}}r=new Date(k.getFullYear()+1,0,4);v=l(new Date(k.getFullYear(),0,4));r=l(r);return 0>=g(v,k)?0>=g(r,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var n=B[d+40>>2];d={Mc:A[d>>2],Lc:A[d+4>>2],
Vb:A[d+8>>2],cc:A[d+12>>2],Wb:A[d+16>>2],Fb:A[d+20>>2],xb:A[d+24>>2],Eb:A[d+28>>2],ad:A[d+32>>2],Kc:A[d+36>>2],Nc:n?n?H(y,n):"":""};c=c?H(y,c):"";n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W",
"%Oy":"%y"};for(var q in n)c=c.replace(new RegExp(q,"g"),n[q]);var t="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),w="January February March April May June July August September October November December".split(" ");n={"%a":k=>t[k.xb].substring(0,3),"%A":k=>t[k.xb],"%b":k=>w[k.Wb].substring(0,3),"%B":k=>w[k.Wb],"%C":k=>f((k.Fb+1900)/100|0,2),"%d":k=>f(k.cc,2),"%e":k=>e(k.cc,2," "),"%g":k=>m(k).toString().substring(2),"%G":k=>m(k),"%H":k=>f(k.Vb,2),"%I":k=>{k=k.Vb;0==k?k=12:
12<k&&(k-=12);return f(k,2)},"%j":k=>{for(var v=0,r=0;r<=k.Wb-1;v+=(Fd(k.Fb+1900)?Gd:Hd)[r++]);return f(k.cc+v,3)},"%m":k=>f(k.Wb+1,2),"%M":k=>f(k.Lc,2),"%n":()=>"\n","%p":k=>0<=k.Vb&&12>k.Vb?"AM":"PM","%S":k=>f(k.Mc,2),"%t":()=>"\t","%u":k=>k.xb||7,"%U":k=>f(Math.floor((k.Eb+7-k.xb)/7),2),"%V":k=>{var v=Math.floor((k.Eb+7-(k.xb+6)%7)/7);2>=(k.xb+371-k.Eb-2)%7&&v++;if(v)53==v&&(r=(k.xb+371-k.Eb)%7,4==r||3==r&&Fd(k.Fb)||(v=1));else{v=52;var r=(k.xb+7-k.Eb-1)%7;(4==r||5==r&&Fd(k.Fb%400-1))&&v++}return f(v,
2)},"%w":k=>k.xb,"%W":k=>f(Math.floor((k.Eb+7-(k.xb+6)%7)/7),2),"%y":k=>(k.Fb+1900).toString().substring(2),"%Y":k=>k.Fb+1900,"%z":k=>{k=k.Kc;var v=0<=k;k=Math.abs(k)/60;return(v?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":k=>k.Nc,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");for(q in n)c.includes(q)&&(c=c.replace(new RegExp(q,"g"),n[q](d)));c=c.replace(/\0\0/g,"%");q=jb(c,!1);if(q.length>b)return 0;x.set(q,a);return q.length-1};
function Mb(a,b,c,d){a||(a=this);this.parent=a;this.tb=a.tb;this.Hb=null;this.id=Eb++;this.name=b;this.mode=c;this.hb={};this.jb={};this.rdev=d}Object.defineProperties(Mb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Bc:{get:function(){return K(this.mode)}},Ac:{get:function(){return 8192===(this.mode&61440)}}});fc();Fb=Array(4096);
Ub(J,"/");N("/tmp");N("/home");N("/home/web_user");(function(){N("/dev");mb(259,{read:()=>0,write:(d,e,f,g)=>g});Wb("/dev/null",259);lb(1280,ob);lb(1536,pb);Wb("/dev/tty",1280);Wb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=ab(a).byteLength);return a[--b]};O("/dev","random",c);O("/dev","urandom",c);N("/dev/shm");N("/dev/shm/tmp")})();
(function(){N("/proc");var a=N("/proc/self");N("/proc/self/fd");Ub({tb(){var b=sb(a,"fd",16895,73);b.hb={lookup(c,d){var e=Rb(+d);c={parent:null,tb:{mc:"fake"},hb:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();h.FS_createPath=hc;h.FS_createDataFile=yb;h.FS_createPreloadedFile=zb;h.FS_unlink=Zb;h.FS_createLazyFile=kc;h.FS_createDevice=O;for(var Jd=Array(256),Kd=0;256>Kd;++Kd)Jd[Kd]=String.fromCharCode(Kd);Ec=Jd;
T=h.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};Jc=h.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};Object.assign(Nc.prototype,{get(a){return this.rb[a]},has(a){return void 0!==this.rb[a]},Pb(a){var b=this.hc.pop()||this.rb.length;this.rb[b]=a;return b},Gb(a){this.rb[a]=void 0;this.hc.push(a)}});U.rb.push({value:void 0},{value:null},{value:!0},{value:!1});U.ob=U.rb.length;
h.count_emval_handles=()=>{for(var a=0,b=U.ob;b<U.rb.length;++b)void 0!==U.rb[b]&&++a;return a};dd=h.UnboundTypeError=((a,b)=>{var c=Vc(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
var me={o:a=>{a=new Ua(a);a.Ec()||(a.pc(!0),Sa--);a.qc(!1);Ra.push(a);Ld(a.Mb);return a.Fc()},q:()=>{W(0,0);var a=Ra.pop();Md(a.Mb);Ta=0},a:()=>Za([]),g:a=>Za([a]),H:()=>{var a=Ra.pop();a||u("no exception to throw");var b=a.Mb;a.vc()||(Ra.push(a),a.qc(!0),a.pc(!1),Sa++);Ta=b;throw Ta;},c:(a,b,c)=>{(new Ua(a)).kc(b,c);Ta=a;Sa++;throw Ta;},x:()=>Sa,e:a=>{Ta||(Ta=a);throw Ta;},aa:function(a,b,c){try{var d=pc(a),e=Ac(b,c);d.Ob.connect(d,e.mb,e.port);return 0}catch(f){if("undefined"==typeof P||"ErrnoError"!==
f.name)throw f;return-f.kb}},r:function(a,b,c){Cc=c;try{var d=Rb(a);switch(b){case 0:var e=Dc();if(0>e)return-28;for(;Db[e];)e++;return Sb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Dc(),d.flags|=e,0;case 5:return e=Dc(),z[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return A[Nd()>>2]=28,-1;default:return-28}}catch(f){if("undefined"==typeof P||"ErrnoError"!==f.name)throw f;return-f.kb}},ka:function(a,b){try{if(0===b)return-28;var c=hb("/")+1;if(b<c)return-68;
ib("/",y,a,b);return c}catch(d){if("undefined"==typeof P||"ErrnoError"!==d.name)throw d;return-d.kb}},fa:function(a,b,c){try{var d=Rb(a);if(!d.Cb){var e=M(d.path,{Nb:!0}).node;if(!e.hb.readdir)throw new I(54);var f=e.hb.readdir(e);d.Cb=f}a=0;for(var g=dc(d,0,1),l=Math.floor(g/280);l<d.Cb.length&&a+280<=c;){var m=d.Cb[l];if("."===m){var n=d.node.id;var q=4}else if(".."===m)n=M(d.path,{parent:!0}).node.id,q=4;else{var t=ub(d.node,m);n=t.id;q=8192===(t.mode&61440)?2:K(t.mode)?4:40960===(t.mode&61440)?
10:8}E=[n>>>0,(C=n,1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];A[b+a>>2]=E[0];A[b+a+4>>2]=E[1];E=[280*(l+1)>>>0,(C=280*(l+1),1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];A[b+a+8>>2]=E[0];A[b+a+12>>2]=E[1];z[b+a+16>>1]=280;x[b+a+18>>0]=q;ib(m,y,b+a+19,256);a+=280;l+=1}dc(d,280*l,0);return a}catch(w){if("undefined"==typeof P||"ErrnoError"!==w.name)throw w;return-w.kb}},$:function(a,b,c,d,e){try{var f=
pc(a);return 1===b&&4===c?(A[d>>2]=f.error,A[e>>2]=4,f.error=null,0):-50}catch(g){if("undefined"==typeof P||"ErrnoError"!==g.name)throw g;return-g.kb}},la:function(a,b,c){Cc=c;try{var d=Rb(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.Ab.xc){b=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Dc();A[e>>2]=25856;A[e+4>>2]=5;A[e+8>>2]=191;A[e+12>>2]=35387;for(var f=0;32>f;f++)x[e+f+17>>0]=b[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?
0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Ab.yc)for(e=Dc(),b=[],f=0;32>f;f++)b.push(x[e+f+17>>0]);return 0;case 21519:if(!d.tty)return-59;e=Dc();return A[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:e=Dc();if(!d.jb.Rb)throw new I(59);return d.jb.Rb(d,b,e);case 21523:if(!d.tty)return-59;d.tty.Ab.zc&&(f=[24,80],e=Dc(),z[e>>1]=f[0],z[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if("undefined"==typeof P||
"ErrnoError"!==g.name)throw g;return-g.kb}},ha:function(a,b,c){try{return b=b?H(y,b):"",b=Bc(a,b),b=G(b),"/"===b[b.length-1]&&(b=b.substr(0,b.length-1)),N(b,c),0}catch(d){if("undefined"==typeof P||"ErrnoError"!==d.name)throw d;return-d.kb}},L:function(a,b,c,d){Cc=d;try{b=b?H(y,b):"";b=Bc(a,b);var e=d?Dc():0;return ac(b,c,e).fd}catch(f){if("undefined"==typeof P||"ErrnoError"!==f.name)throw f;return-f.kb}},ga:function(a,b){try{for(var c=0,d=0;d<b;d++){var e=a+8*d,f=z[e+4>>1],g=32,l=Db[A[e>>2]];l&&(g=
5,l.jb.Ub&&(g=l.jb.Ub(l,-1)));(g&=f|24)&&c++;z[e+6>>1]=g}return c}catch(m){if("undefined"==typeof P||"ErrnoError"!==m.name)throw m;return-m.kb}},_:function(a,b,c,d,e,f){try{var g=pc(a),l=lc(g,c);if(!l)return 0;if(e){var m=g.family,n=zc(l.mb),q=l.port;switch(m){case 2:n=tc(n);y.fill(0,e,e+16);f&&(A[f>>2]=16);z[e>>1]=m;A[e+4>>2]=n;z[e+2>>1]=uc(q);break;case 10:n=vc(n),y.fill(0,e,e+28),f&&(A[f>>2]=28),A[e>>2]=m,A[e+8>>2]=n[0],A[e+12>>2]=n[1],A[e+16>>2]=n[2],A[e+20>>2]=n[3],z[e+2>>1]=uc(q)}}y.set(l.buffer,
b);return l.buffer.byteLength}catch(t){if("undefined"==typeof P||"ErrnoError"!==t.name)throw t;return-t.kb}},I:function(a){try{return a=a?H(y,a):"",Yb(a),0}catch(b){if("undefined"==typeof P||"ErrnoError"!==b.name)throw b;return-b.kb}},Z:function(a,b,c,d,e,f){try{var g=pc(a),l=Ac(e,f,!0);return l?mc(g,x,b,c,l.mb,l.port):ec(g.stream,x,b,c)}catch(m){if("undefined"==typeof P||"ErrnoError"!==m.name)throw m;return-m.kb}},Y:function(a,b,c){try{return Q.createSocket(a,b,c).stream.fd}catch(d){if("undefined"==
typeof P||"ErrnoError"!==d.name)throw d;return-d.kb}},da:function(a,b){try{a=a?H(y,a):"";a:{try{var c=M(a,{Nb:!0}).node;if(!c)throw new I(44);if(!c.hb.sb)throw new I(63);var d=c.hb.sb(c)}catch(m){if(m&&m.node&&G(a)!==G(Ib(m.node))){var e=-54;break a}throw m;}A[b>>2]=d.dev;A[b+4>>2]=d.mode;B[b+8>>2]=d.nlink;A[b+12>>2]=d.uid;A[b+16>>2]=d.gid;A[b+20>>2]=d.rdev;E=[d.size>>>0,(C=d.size,1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];A[b+24>>2]=E[0];A[b+
28>>2]=E[1];A[b+32>>2]=4096;A[b+36>>2]=d.blocks;var f=d.atime.getTime(),g=d.mtime.getTime(),l=d.ctime.getTime();E=[Math.floor(f/1E3)>>>0,(C=Math.floor(f/1E3),1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];A[b+40>>2]=E[0];A[b+44>>2]=E[1];B[b+48>>2]=f%1E3*1E3;E=[Math.floor(g/1E3)>>>0,(C=Math.floor(g/1E3),1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];A[b+56>>2]=E[0];A[b+60>>2]=E[1];B[b+64>>2]=g%1E3*
1E3;E=[Math.floor(l/1E3)>>>0,(C=Math.floor(l/1E3),1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];A[b+72>>2]=E[0];A[b+76>>2]=E[1];B[b+80>>2]=l%1E3*1E3;E=[d.ino>>>0,(C=d.ino,1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];A[b+88>>2]=E[0];A[b+92>>2]=E[1];e=0}return e}catch(m){if("undefined"==typeof P||"ErrnoError"!==m.name)throw m;return-m.kb}},ea:function(a,b,c){try{return b=b?H(y,b):"",b=Bc(a,b),0===
c?Zb(b):512===c?Yb(b):u("Invalid flags passed to unlinkat"),0}catch(d){if("undefined"==typeof P||"ErrnoError"!==d.name)throw d;return-d.kb}},X:()=>{},oa:(a,b,c,d)=>{b=R(b);Kc(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,f){return f?c:d},argPackAdvance:8,readValueFromPointer:function(e){return this.fromWireType(y[e])},Bb:null})},na:(a,b)=>{b=R(b);Kc(a,{name:b,fromWireType:c=>{var d=Pc(c);Oc(c);return d},toWireType:(c,d)=>Qc(d),argPackAdvance:8,readValueFromPointer:Rc,Bb:null})},
P:(a,b,c)=>{b=R(b);Kc(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,argPackAdvance:8,readValueFromPointer:Sc(b,c),Bb:null})},u:(a,b,c,d,e,f,g)=>{var l=Zc(b,c);a=R(a);a=jd(a);e=cd(d,e);Yc(a,function(){hd(`Cannot call ${a} due to unbound types`,l)},b-1);Lc(l,function(m){var n=[m[0],null].concat(m.slice(1)),q=m=a,t=e,w=n.length;if(2>w)throw new T("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var k=null!==n[1]&&!1,v=!1,r=1;r<n.length;++r)if(null!==n[r]&&void 0===
n[r].Bb){v=!0;break}var D="void"!==n[0].name,F="",L="";for(r=0;r<w-2;++r)F+=(0!==r?", ":"")+"arg"+r,L+=(0!==r?", ":"")+"arg"+r+"Wired";q=`\n        return function ${Tc(q)}(${F}) {\n        if (arguments.length !== ${w-2}) {\n          throwBindingError('function ${q} called with ' + arguments.length + ' arguments, expected ${w-2}');\n        }`;v&&(q+="var destructors = [];\n");var Xa=v?"destructors":"null";F="throwBindingError invoker fn runDestructors retType classParam".split(" ");t=[Ic,t,f,Uc,
n[0],n[1]];k&&(q+="var thisWired = classParam.toWireType("+Xa+", this);\n");for(r=0;r<w-2;++r)q+="var arg"+r+"Wired = argType"+r+".toWireType("+Xa+", arg"+r+"); // "+n[r+2].name+"\n",F.push("argType"+r),t.push(n[r+2]);k&&(L="thisWired"+(0<L.length?", ":"")+L);q+=(D||g?"var rv = ":"")+"invoker(fn"+(0<L.length?", ":"")+L+");\n";if(v)q+="runDestructors(destructors);\n";else for(r=k?1:2;r<n.length;++r)w=1===r?"thisWired":"arg"+(r-2)+"Wired",null!==n[r].Bb&&(q+=w+"_dtor("+w+"); // "+n[r].name+"\n",F.push(w+
"_dtor"),t.push(n[r].Bb));D&&(q+="var ret = retType.fromWireType(rv);\nreturn ret;\n");F.push(q+"}\n");n=Wc(F).apply(null,t);r=b-1;if(!h.hasOwnProperty(m))throw new Jc("Replacing nonexistant public symbol");void 0!==h[m].vb&&void 0!==r?h[m].vb[r]=n:(h[m]=n,h[m].tc=r);return[]})},s:(a,b,c,d,e)=>{b=R(b);-1===e&&(e=4294967295);e=l=>l;if(0===d){var f=32-8*c;e=l=>l<<f>>>f}var g=b.includes("unsigned")?function(l,m){return m>>>0}:function(l,m){return m};Kc(a,{name:b,fromWireType:e,toWireType:g,argPackAdvance:8,
readValueFromPointer:kd(b,c,0!==d),Bb:null})},n:(a,b,c)=>{function d(f){return new e(x.buffer,B[f+4>>2],B[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=R(c);Kc(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{wc:!0})},O:(a,b)=>{b=R(b);var c="std::string"===b;Kc(a,{name:b,fromWireType:function(d){var e=B[d>>2],f=d+4;if(c)for(var g=f,l=0;l<=e;++l){var m=f+l;if(l==e||0==y[m]){g=g?H(y,g,m-g):"";if(void 0===n)var n=g;
else n+=String.fromCharCode(0),n+=g;g=m+1}}else{n=Array(e);for(l=0;l<e;++l)n[l]=String.fromCharCode(y[f+l]);n=n.join("")}fd(d);return n},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"==typeof e;if(!(f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array))throw new T("Cannot pass non-string to std::string");var g=c&&f?hb(e):e.length;var l=Od(4+g+1),m=l+4;B[l>>2]=g;if(c&&f)ib(e,y,m,g+1);else if(f)for(f=0;f<g;++f){var n=e.charCodeAt(f);
if(255<n)throw fd(m),new T("String has UTF-16 code units that do not fit in 8 bits");y[m+f]=n}else for(f=0;f<g;++f)y[m+f]=e[f];null!==d&&d.push(fd,l);return l},argPackAdvance:8,readValueFromPointer:ld,Bb(d){fd(d)}})},D:(a,b,c)=>{c=R(c);if(2===b){var d=nd;var e=od;var f=pd;var g=()=>ta;var l=1}else 4===b&&(d=qd,e=rd,f=sd,g=()=>B,l=2);Kc(a,{name:c,fromWireType:m=>{for(var n=B[m>>2],q=g(),t,w=m+4,k=0;k<=n;++k){var v=m+4+k*b;if(k==n||0==q[v>>l])w=d(w,v-w),void 0===t?t=w:(t+=String.fromCharCode(0),t+=
w),w=v+b}fd(m);return t},toWireType:(m,n)=>{if("string"!=typeof n)throw new T(`Cannot pass non-string to C++ string type ${c}`);var q=f(n),t=Od(4+q+b);B[t>>2]=q>>l;e(n,t+4,q+b);null!==m&&m.push(fd,t);return t},argPackAdvance:8,readValueFromPointer:Rc,Bb(m){fd(m)}})},pa:(a,b)=>{b=R(b);Kc(a,{Cc:!0,name:b,argPackAdvance:0,fromWireType:()=>{},toWireType:()=>{}})},ya:(a,b,c,d,e)=>{a=vd[a];b=Pc(b);c=ud(c);var f=[];a=a(b,c,f,e);f.length&&(B[d>>2]=Qc(f));return a},va:Oc,T:a=>{if(0===a)return Qc(wd());a=ud(a);
return Qc(wd()[a])},za:(a,b)=>{b=zd(a,b);var c=b.shift();a--;for(var d=["retType"],e=[c],f="",g=0;g<a;++g)f+=(0!==g?", ":"")+"arg"+g,d.push("argType"+g),e.push(b[g]);g=c.name+"_$"+b.map(n=>n.name).join("_")+"$";var l="return function "+Tc("methodCaller_"+g)+"(handle, name, destructors, args) {\n",m=0;for(g=0;g<a;++g)l+="    var arg"+g+" = argType"+g+".readValueFromPointer(args"+(m?"+"+m:"")+");\n",m+=b[g].argPackAdvance;l+="    var rv = handle[name]("+f+");\n";for(g=0;g<a;++g)b[g].deleteObject&&(l+=
"    argType"+g+".deleteObject(arg"+g+");\n");c.Cc||(l+="    return retType.toWireType(destructors, rv);\n");d.push(l+"};\n");a=Wc(d).apply(null,e);return xd(a)},sa:a=>{4<a&&(U.get(a).oc+=1)},S:(a,b,c,d)=>{a=Pc(a);var e=Bd[b];e||(e=Ad(b),Bd[b]=e);return e(a,c,d)},Q:a=>Qc(ud(a)),R:()=>Qc({}),wa:a=>{var b=Pc(a);Uc(b);Oc(a)},ua:(a,b,c)=>{a=Pc(a);b=Pc(b);c=Pc(c);a[b]=c},ta:(a,b)=>{a=yd(a,"_emval_take_value");a=a.readValueFromPointer(b);return Qc(a)},C:()=>{u("")},N:()=>Date.now(),M:()=>performance.now(),
ma:(a,b,c)=>y.copyWithin(a,b,b+c),ca:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-ra.buffer.byteLength+65535)/65536;try{ra.grow(e);wa();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},ia:(a,b)=>{var c=0;Ed().forEach((d,e)=>{var f=b+c;e=B[a+4*e>>2]=f;for(f=0;f<d.length;++f)x[e++>>0]=d.charCodeAt(f);x[e>>0]=0;c+=d.length+1});return 0},ja:(a,
b)=>{var c=Ed();B[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);B[b>>2]=d;return 0},qa:a=>{if(!Qa){Pd();Pa(za);gc=!1;Qd(0);for(var b=0;b<Db.length;b++){var c=Db[b];c&&cc(c)}}if(!Qa){if(h.onExit)h.onExit(a);sa=!0}ea(a,new Oa(a))},y:function(a){try{var b=Rb(a);cc(b);return 0}catch(c){if("undefined"==typeof P||"ErrnoError"!==c.name)throw c;return c.kb}},J:function(a,b,c,d){try{a:{var e=Rb(a);a=b;for(var f,g=b=0;g<c;g++){var l=B[a>>2],m=B[a+4>>2];a+=8;var n=e,q=l,t=m,w=f,k=x;if(0>t||0>w)throw new I(28);
if(null===n.fd)throw new I(8);if(1===(n.flags&2097155))throw new I(8);if(K(n.node.mode))throw new I(31);if(!n.jb.read)throw new I(28);var v="undefined"!=typeof w;if(!v)w=n.position;else if(!n.seekable)throw new I(70);var r=n.jb.read(n,k,q,t,w);v||(n.position+=r);var D=r;if(0>D){var F=-1;break a}b+=D;if(D<m)break;"undefined"!==typeof f&&(f+=D)}F=b}B[d>>2]=F;return 0}catch(L){if("undefined"==typeof P||"ErrnoError"!==L.name)throw L;return L.kb}},W:function(a,b,c,d,e){b=c+2097152>>>0<4194305-!!b?(b>>>
0)+4294967296*c:NaN;try{if(isNaN(b))return 61;var f=Rb(a);dc(f,b,d);E=[f.position>>>0,(C=f.position,1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];A[e>>2]=E[0];A[e+4>>2]=E[1];f.Cb&&0===b&&0===d&&(f.Cb=null);return 0}catch(g){if("undefined"==typeof P||"ErrnoError"!==g.name)throw g;return g.kb}},K:function(a,b,c,d){try{a:{var e=Rb(a);a=b;for(var f,g=b=0;g<c;g++){var l=B[a>>2],m=B[a+4>>2];a+=8;var n=ec(e,x,l,m,f);if(0>n){var q=-1;break a}b+=n;"undefined"!==
typeof f&&(f+=n)}q=b}B[d>>2]=q;return 0}catch(t){if("undefined"==typeof P||"ErrnoError"!==t.name)throw t;return t.kb}},ra:a=>{a=a?H(y,a):"";var b=Od(20),c=hb(a)+1,d=Od(c);d&&ib(a,y,d,c);B[b>>2]=d;c=Od(4);B[c>>2]=0;B[b+4>>2]=c;A[b+8>>2]=2;A[b+12>>2]=4;c=Od(12);B[c>>2]=c+8;B[c+4>>2]=0;A[c+8>>2]=tc(zc(a));B[b+16>>2]=c;return b},E:Rd,xa:Sd,F:Td,m:Ud,b:Vd,f:Wd,l:Xd,j:Yd,z:Zd,t:$d,G:ae,B:be,U:ce,h:de,i:ee,d:fe,k:ge,w:he,p:ie,v:je,A:ke,V:le,ba:(a,b,c,d)=>Id(a,b,c,d)},X=function(){function a(c){X=c.exports;
ra=X.Aa;wa();ad=X.Ca;ya.unshift(X.Ba);Ga("wasm-instantiate");return X}var b={a:me};Fa("wasm-instantiate");if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){pa(`Module.instantiateWasm callback failed with error: ${c}`),ba(c)}Na(b,function(c){a(c.instance)}).catch(ba);return{}}(),fd=a=>(fd=X.Da)(a),Od=a=>(Od=X.Ea)(a),Nd=()=>(Nd=X.Fa)(),Qd=h._fflush=a=>(Qd=h._fflush=X.Ga)(a),uc=a=>(uc=X.Ha)(a),ed=a=>(ed=X.Ia)(a);h.__embind_initialize_bindings=()=>(h.__embind_initialize_bindings=X.Ja)();
var Pd=()=>(Pd=X.Ka)(),rc=a=>(rc=X.La)(a),W=(a,b)=>(W=X.Ma)(a,b),Wa=a=>(Wa=X.Na)(a),Y=()=>(Y=X.Oa)(),Z=a=>(Z=X.Pa)(a),Md=a=>(Md=X.Qa)(a),Ld=a=>(Ld=X.Ra)(a),Ya=(a,b,c)=>(Ya=X.Sa)(a,b,c),Va=a=>(Va=X.Ta)(a);h.dynCall_ji=(a,b)=>(h.dynCall_ji=X.Ua)(a,b);h.dynCall_jij=(a,b,c,d)=>(h.dynCall_jij=X.Va)(a,b,c,d);h.dynCall_iiiijii=(a,b,c,d,e,f,g,l)=>(h.dynCall_iiiijii=X.Wa)(a,b,c,d,e,f,g,l);h.dynCall_viiij=(a,b,c,d,e,f)=>(h.dynCall_viiij=X.Xa)(a,b,c,d,e,f);
h.dynCall_vij=(a,b,c,d)=>(h.dynCall_vij=X.Ya)(a,b,c,d);h.dynCall_iiiji=(a,b,c,d,e,f)=>(h.dynCall_iiiji=X.Za)(a,b,c,d,e,f);h.dynCall_jii=(a,b,c)=>(h.dynCall_jii=X._a)(a,b,c);h.dynCall_jiji=(a,b,c,d,e)=>(h.dynCall_jiji=X.$a)(a,b,c,d,e);h.dynCall_jiij=(a,b,c,d,e)=>(h.dynCall_jiij=X.ab)(a,b,c,d,e);h.dynCall_viij=(a,b,c,d,e)=>(h.dynCall_viij=X.bb)(a,b,c,d,e);
var ne=h.dynCall_viijii=(a,b,c,d,e,f,g)=>(ne=h.dynCall_viijii=X.cb)(a,b,c,d,e,f,g),oe=h.dynCall_jiiii=(a,b,c,d,e)=>(oe=h.dynCall_jiiii=X.db)(a,b,c,d,e);h.dynCall_iiiiij=(a,b,c,d,e,f,g)=>(h.dynCall_iiiiij=X.eb)(a,b,c,d,e,f,g);h.dynCall_iiiiijj=(a,b,c,d,e,f,g,l,m)=>(h.dynCall_iiiiijj=X.fb)(a,b,c,d,e,f,g,l,m);h.dynCall_iiiiiijj=(a,b,c,d,e,f,g,l,m,n)=>(h.dynCall_iiiiiijj=X.gb)(a,b,c,d,e,f,g,l,m,n);function Wd(a,b,c){var d=Y();try{return V(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;W(1,0)}}
function Zd(a,b,c,d,e,f){var g=Y();try{return V(a)(b,c,d,e,f)}catch(l){Z(g);if(l!==l+0)throw l;W(1,0)}}function Xd(a,b,c,d){var e=Y();try{return V(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}function Vd(a,b){var c=Y();try{return V(a)(b)}catch(d){Z(c);if(d!==d+0)throw d;W(1,0)}}function Yd(a,b,c,d,e){var f=Y();try{return V(a)(b,c,d,e)}catch(g){Z(f);if(g!==g+0)throw g;W(1,0)}}function ee(a,b){var c=Y();try{V(a)(b)}catch(d){Z(c);if(d!==d+0)throw d;W(1,0)}}
function Sd(a,b,c,d,e,f){var g=Y();try{return V(a)(b,c,d,e,f)}catch(l){Z(g);if(l!==l+0)throw l;W(1,0)}}function fe(a,b,c){var d=Y();try{V(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;W(1,0)}}function ge(a,b,c,d){var e=Y();try{V(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}function de(a){var b=Y();try{V(a)()}catch(c){Z(b);if(c!==c+0)throw c;W(1,0)}}function he(a,b,c,d,e){var f=Y();try{V(a)(b,c,d,e)}catch(g){Z(f);if(g!==g+0)throw g;W(1,0)}}
function $d(a,b,c,d,e,f,g){var l=Y();try{return V(a)(b,c,d,e,f,g)}catch(m){Z(l);if(m!==m+0)throw m;W(1,0)}}function ae(a,b,c,d,e,f,g,l){var m=Y();try{return V(a)(b,c,d,e,f,g,l)}catch(n){Z(m);if(n!==n+0)throw n;W(1,0)}}function Td(a,b,c,d){var e=Y();try{return V(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}function Rd(a,b,c,d){var e=Y();try{return V(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}function Ud(a){var b=Y();try{return V(a)()}catch(c){Z(b);if(c!==c+0)throw c;W(1,0)}}
function ie(a,b,c,d,e,f,g,l){var m=Y();try{V(a)(b,c,d,e,f,g,l)}catch(n){Z(m);if(n!==n+0)throw n;W(1,0)}}function be(a,b,c,d,e,f,g,l,m,n,q,t){var w=Y();try{return V(a)(b,c,d,e,f,g,l,m,n,q,t)}catch(k){Z(w);if(k!==k+0)throw k;W(1,0)}}function je(a,b,c,d,e,f,g,l,m,n,q){var t=Y();try{V(a)(b,c,d,e,f,g,l,m,n,q)}catch(w){Z(t);if(w!==w+0)throw w;W(1,0)}}function ke(a,b,c,d,e,f,g,l,m,n,q,t,w,k,v,r){var D=Y();try{V(a)(b,c,d,e,f,g,l,m,n,q,t,w,k,v,r)}catch(F){Z(D);if(F!==F+0)throw F;W(1,0)}}
function le(a,b,c,d,e,f,g){var l=Y();try{ne(a,b,c,d,e,f,g)}catch(m){Z(l);if(m!==m+0)throw m;W(1,0)}}function ce(a,b,c,d,e){var f=Y();try{return oe(a,b,c,d,e)}catch(g){Z(f);if(g!==g+0)throw g;W(1,0)}}h.addRunDependency=Fa;h.removeRunDependency=Ga;h.FS_createPath=hc;h.FS_createLazyFile=kc;h.FS_createDevice=O;h.FS_createPreloadedFile=zb;h.FS_createDataFile=yb;h.FS_unlink=Zb;var pe;Ea=function qe(){pe||re();pe||(Ea=qe)};
function re(){function a(){if(!pe&&(pe=!0,h.calledRun=!0,!sa)){Q.root=Ub(Q,null);h.noFSInit||gc||(gc=!0,fc(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?O("/dev","stdin",h.stdin):Xb("/dev/tty","/dev/stdin"),h.stdout?O("/dev","stdout",null,h.stdout):Xb("/dev/tty","/dev/stdout"),h.stderr?O("/dev","stderr",null,h.stderr):Xb("/dev/tty1","/dev/stderr"),ac("/dev/stdin",0),ac("/dev/stdout",1),ac("/dev/stderr",1));Gb=!1;Pa(ya);aa(h);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(h.postRun)for("function"==
typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var b=h.postRun.shift();Aa.unshift(b)}Pa(Aa)}}if(!(0<Ca)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ba();Pa(xa);0<Ca||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);a()},1)):a())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();re();


  return moduleArg.ready
}

);
})();
export default Module;