
var Module = (() => {
  var _scriptDir = import.meta.url;
  
  return (
async function(moduleArg = {}) {

var h=moduleArg,aa,ba;h.ready=new Promise((a,b)=>{aa=a;ba=b});h.Yb=!0;h.Zb=!0;
"object"!==typeof WebAssembly&&"undefined"!==typeof WXWebAssembly&&(WXWebAssembly.RuntimeError=WXWebAssembly.RuntimeError||function(){class a extends Error{constructor(b){super(b);this instanceof a||(b=Object.setPrototypeOf,"function"===typeof b?b.call(Object,this,a.prototype):this.__proto__=a.prototype,"function"===typeof Error.captureStackTrace&&Error.captureStackTrace(this,a))}}Object.defineProperty(a.prototype,"name",{configurable:!0,writable:!0,value:"RuntimeError"});return a}(),function(){if("undefined"!==
typeof globalThis)return globalThis;var a=function(){return this}(),b=function(){try{var c=new Function}catch(d){return!1}return"function"===typeof c}();if(!a&&b)try{a=(new Function("return this"))()}catch(c){}if(!a){if("undefined"===typeof __webpack_public_path__&&"undefined"!==typeof global)return global;if("undefined"!==typeof window)return window;if("undefined"!==typeof self)return self}return a}().WebAssembly=WXWebAssembly);
var ca=Object.assign({},h),da="./this.program",ea="object"==typeof window,fa="function"==typeof importScripts,ha="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,r="",ia,ja,ka;
if(ha){const {createRequire:a}=await import("module");var require=a(import.meta.url),fs=require("fs"),la=require("path");fa?r=la.dirname(r)+"/":r=require("url").fileURLToPath(new URL("./",import.meta.url));ia=(b,c)=>{b=ma(b)?new URL(b):la.normalize(b);return fs.readFileSync(b,c?void 0:"utf8")};ka=b=>{b=ia(b,!0);b.buffer||(b=new Uint8Array(b));return b};ja=(b,c,d,e=!0)=>{b=ma(b)?new URL(b):la.normalize(b);fs.readFile(b,e?void 0:"utf8",(f,k)=>{f?d(f):c(e?k.buffer:k)})};
!h.thisProgram&&1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);h.inspect=()=>"[Emscripten Module object]"}else if(ea||fa)fa?r=self.location.href:"undefined"!=typeof document&&document.currentScript&&(r=document.currentScript.src),_scriptDir&&(r=_scriptDir),0!==r.indexOf("blob:")?r=r.substr(0,r.replace(/[?#].*/,"").lastIndexOf("/")+1):r="",ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},fa&&(ka=a=>{var b=new XMLHttpRequest;
b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ja=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var na=h.print||console.log.bind(console),w=h.printErr||console.error.bind(console);Object.assign(h,ca);ca=null;h.thisProgram&&(da=h.thisProgram);var oa;h.wasmBinary&&(oa=h.wasmBinary);"object"!=typeof WebAssembly&&x("no native wasm support detected");
var pa,qa=!1,y,z,ra,sa,A,B,ta,ua;function va(){var a=pa.buffer;h.HEAP8=y=new Int8Array(a);h.HEAP16=ra=new Int16Array(a);h.HEAPU8=z=new Uint8Array(a);h.HEAPU16=sa=new Uint16Array(a);h.HEAP32=A=new Int32Array(a);h.HEAPU32=B=new Uint32Array(a);h.HEAPF32=ta=new Float32Array(a);h.HEAPF64=ua=new Float64Array(a)}var wa=[],xa=[],ya=[];function za(){var a=h.preRun.shift();wa.unshift(a)}var C=0,Aa=null,Ba=null;function Ca(){C++;h.monitorRunDependencies&&h.monitorRunDependencies(C)}
function Da(){C--;h.monitorRunDependencies&&h.monitorRunDependencies(C);if(0==C&&(null!==Aa&&(clearInterval(Aa),Aa=null),Ba)){var a=Ba;Ba=null;a()}}function x(a){if(h.onAbort)h.onAbort(a);a="Aborted("+a+")";w(a);qa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}var Ea=a=>a.startsWith("data:application/octet-stream;base64,"),ma=a=>a.startsWith("file://"),F;
if(h.locateFile){if(F="vml2dml.wasm?version=1.0.0",!Ea(F)){var Fa=F;F=h.locateFile?h.locateFile(Fa,r):r+Fa}}else F=(new URL("vml2dml.wasm?version=1.0.0",import.meta.url)).href;function Ga(a){if(a==F&&oa)return new Uint8Array(oa);if(ka)return ka(a);throw"both async and sync fetching of the wasm failed";}
function Ha(a){if(!oa&&(ea||fa)){if("function"==typeof fetch&&!ma(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Ga(a));if(ja)return new Promise((b,c)=>{ja(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Ga(a))}function Ia(a,b,c){return Ha(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{w(`failed to asynchronously prepare wasm: ${d}`);x(d)})}
function Ka(a,b){var c=F;return oa||"function"!=typeof WebAssembly.instantiateStreaming||Ea(c)||ma(c)||ha||"function"!=typeof fetch?Ia(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){w(`wasm streaming compile failed: ${e}`);w("falling back to ArrayBuffer instantiation");return Ia(c,a,b)}))}var La=a=>{for(;0<a.length;)a.shift()(h)},Ma=[],Na=0,G=0;
function Oa(a){this.Ta=a;this.Fa=a-24;this.wb=function(b){B[this.Fa+4>>2]=b};this.Da=function(){return B[this.Fa+4>>2]};this.vb=function(b){B[this.Fa+8>>2]=b};this.qb=function(b){y[this.Fa+12>>0]=b?1:0};this.tb=function(){return 0!=y[this.Fa+12>>0]};this.rb=function(b){y[this.Fa+13>>0]=b?1:0};this.Cb=function(){return 0!=y[this.Fa+13>>0]};this.lb=function(b,c){this.Qa(0);this.wb(b);this.vb(c)};this.Qa=function(b){B[this.Fa+16>>2]=b};this.sb=function(){return B[this.Fa+16>>2]};this.ub=function(){if(Pa(this.Da()))return B[this.Ta>>
2];var b=this.sb();return 0!==b?b:this.Ta}}
var Sa=a=>{var b=G;if(!b)return Qa(0),0;var c=new Oa(b);c.Qa(b);var d=c.Da();if(!d)return Qa(0),b;for(var e in a){var f=a[e];if(0===f||f===d)break;if(Ra(f,d,c.Fa+16))return Qa(f),b}Qa(d);return b},Ta,H=a=>{for(var b="";z[a];)b+=Ta[z[a++]];return b},Ua={},Va={},Wa={},I,Xa=a=>{throw new I(a);},Ya,Za=(a,b)=>{function c(l){l=b(l);if(l.length!==d.length)throw new Ya("Mismatched type converter count");for(var m=0;m<d.length;++m)J(d[m],l[m])}var d=[];d.forEach(function(l){Wa[l]=a});var e=Array(a.length),
f=[],k=0;a.forEach((l,m)=>{Va.hasOwnProperty(l)?e[m]=Va[l]:(f.push(l),Ua.hasOwnProperty(l)||(Ua[l]=[]),Ua[l].push(()=>{e[m]=Va[l];++k;k===f.length&&c(e)}))});0===f.length&&c(e)};function $a(a,b,c={}){var d=b.name;if(!a)throw new I(`type "${d}" must have a positive integer typeid pointer`);if(Va.hasOwnProperty(a)){if(c.Eb)return;throw new I(`Cannot register type '${d}' twice`);}Va[a]=b;delete Wa[a];Ua.hasOwnProperty(a)&&(b=Ua[a],delete Ua[a],b.forEach(e=>e()))}
function J(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");$a(a,b,c)}function ab(){this.Ga=[void 0];this.ib=[]}var M=new ab,bb=a=>{a>=M.Da&&0===--M.get(a).pb&&M.Qa(a)},cb=a=>{if(!a)throw new I("Cannot use deleted val. handle = "+a);return M.get(a).value},db=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:return M.Va({pb:1,value:a})}};
function eb(a){return this.fromWireType(A[a>>2])}var fb=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(ta[c>>2])};case 8:return function(c){return this.fromWireType(ua[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},gb=a=>{if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a},hb=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};
function ib(a,b){a=gb(a);return{[a]:function(){return b.apply(this,arguments)}}[a]}function jb(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=ib(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
var kb=(a,b)=>{if(void 0===h[a].Ia){var c=h[a];h[a]=function(){if(!h[a].Ia.hasOwnProperty(arguments.length))throw new I(`Function '${b}' called with an invalid number of arguments (${arguments.length}) - expects one of (${h[a].Ia})!`);return h[a].Ia[arguments.length].apply(this,arguments)};h[a].Ia=[];h[a].Ia[c.zb]=c}},lb=(a,b,c)=>{if(h.hasOwnProperty(a)){if(void 0===c||void 0!==h[a].Ia&&void 0!==h[a].Ia[c])throw new I(`Cannot register public name '${a}' twice`);kb(a,a);if(h.hasOwnProperty(c))throw new I(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
h[a].Ia[c]=b}else h[a]=b,void 0!==c&&(h[a].$b=c)},mb=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(B[b+4*d>>2]);return c},N,nb=(a,b)=>{var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=h["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=N.get(b).apply(null,c);return d}},ob=(a,b)=>{a=H(a);var c=a.includes("j")?nb(a,b):N.get(b);if("function"!=typeof c)throw new I(`unknown function pointer with signature ${a}: ${b}`);return c},pb,rb=a=>{a=
qb(a);var b=H(a);O(a);return b},sb=(a,b)=>{function c(f){e[f]||Va[f]||(Wa[f]?Wa[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new pb(`${a}: `+d.map(rb).join([", "]));},tb=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?(")"==a[a.length-1]||x("Parentheses for argument names should match."),a.substr(0,b)):a},ub=(a,b,c)=>{switch(b){case 1:return c?d=>y[d>>0]:d=>z[d>>0];case 2:return c?d=>ra[d>>1]:d=>sa[d>>1];case 4:return c?d=>A[d>>2]:d=>B[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);
}};function vb(a){return this.fromWireType(B[a>>2])}
var wb=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var l=a.charCodeAt(++f);k=65536+((k&1023)<<10)|l&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e},xb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=
d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},yb="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,zb=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&yb)return yb.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|
e&1023))}}else d+=String.fromCharCode(e)}return d},Ab="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Bb=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&sa[c];)++c;c<<=1;if(32<c-a&&Ab)return Ab.decode(z.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=ra[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},Cb=(a,b,c)=>{void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)ra[b>>1]=a.charCodeAt(e),b+=2;ra[b>>1]=0;return b-d},Db=
a=>2*a.length,Eb=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=A[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},Fb=(a,b,c)=>{void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var k=a.charCodeAt(++e);f=65536+((f&1023)<<10)|k&1023}A[b>>2]=f;b+=4;if(b+4>c)break}A[b>>2]=0;return b-d},Gb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);
55296<=d&&57343>=d&&++c;b+=4}return b},Hb={},Ib={},Kb=()=>{if(!Jb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Ib)void 0===Ib[b]?delete a[b]:a[b]=Ib[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Jb=c}return Jb},Jb,Lb=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):
c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},P=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Lb(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Mb=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},Nb=a=>{if("/"===a)return"/";a=P(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Ob=()=>
{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(ha)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}x("initRandomDevice")},Pb=a=>(Pb=Ob())(a);
function Qb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Lb(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}var Rb=[];function Sb(a,b){var c=Array(xb(a)+1);a=wb(a,c,0,c.length);b&&(c.length=a);return c}var Tb=[];function Ub(a,b){Tb[a]={input:[],output:[],Sa:b};Vb(a,Wb)}
var Wb={open(a){var b=Tb[a.node.rdev];if(!b)throw new Q(43);a.tty=b;a.seekable=!1},close(a){a.tty.Sa.fsync(a.tty)},fsync(a){a.tty.Sa.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Sa.jb)throw new Q(60);for(var e=0,f=0;f<d;f++){try{var k=a.tty.Sa.jb(a.tty)}catch(l){throw new Q(29);}if(void 0===k&&0===e)throw new Q(6);if(null===k||void 0===k)break;e++;b[c+f]=k}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Sa.bb)throw new Q(60);try{for(var e=0;e<d;e++)a.tty.Sa.bb(a.tty,b[c+
e])}catch(f){throw new Q(29);}d&&(a.node.timestamp=Date.now());return e}},Xb={jb(){a:{if(!Rb.length){var a=null;if(ha){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c?a=b.slice(0,c).toString("utf-8"):a=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}Rb=Sb(a,!0)}a=
Rb.shift()}return a},bb(a,b){null===b||10===b?(na(zb(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(na(zb(a.output,0)),a.output=[])},Ub(){return{Qb:25856,Sb:5,Pb:191,Rb:35387,Ob:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Vb(){return 0},Wb(){return[24,80]}},Yb={bb(a,b){null===b||10===b?(w(zb(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(w(zb(a.output,0)),a.output=[])}};
function Zb(a,b){var c=a.za?a.za.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.za,a.za=new Uint8Array(b),0<a.Ca&&a.za.set(c.subarray(0,a.Ca),0))}
var R={Ha:null,Ka(){return R.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new Q(63);R.Ha||(R.Ha={dir:{node:{Ma:R.Aa.Ma,Ea:R.Aa.Ea,lookup:R.Aa.lookup,Wa:R.Aa.Wa,rename:R.Aa.rename,unlink:R.Aa.unlink,rmdir:R.Aa.rmdir,readdir:R.Aa.readdir,symlink:R.Aa.symlink},stream:{Na:R.Ba.Na}},file:{node:{Ma:R.Aa.Ma,Ea:R.Aa.Ea},stream:{Na:R.Ba.Na,read:R.Ba.read,write:R.Ba.write,Va:R.Ba.Va,ab:R.Ba.ab,ob:R.Ba.ob}},link:{node:{Ma:R.Aa.Ma,Ea:R.Aa.Ea,readlink:R.Aa.readlink},
stream:{}},gb:{node:{Ma:R.Aa.Ma,Ea:R.Aa.Ea},stream:$b}});c=ac(a,b,c,d);16384===(c.mode&61440)?(c.Aa=R.Ha.dir.node,c.Ba=R.Ha.dir.stream,c.za={}):32768===(c.mode&61440)?(c.Aa=R.Ha.file.node,c.Ba=R.Ha.file.stream,c.Ca=0,c.za=null):40960===(c.mode&61440)?(c.Aa=R.Ha.link.node,c.Ba=R.Ha.link.stream):8192===(c.mode&61440)&&(c.Aa=R.Ha.gb.node,c.Ba=R.Ha.gb.stream);c.timestamp=Date.now();a&&(a.za[b]=c,a.timestamp=c.timestamp);return c},Tb(a){return a.za?a.za.subarray?a.za.subarray(0,a.Ca):new Uint8Array(a.za):
new Uint8Array(0)},Aa:{Ma(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.Ca:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Ab=4096;b.blocks=Math.ceil(b.size/b.Ab);return b},Ea(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==
b.size&&(b=b.size,a.Ca!=b))if(0==b)a.za=null,a.Ca=0;else{var c=a.za;a.za=new Uint8Array(b);c&&a.za.set(c.subarray(0,Math.min(b,a.Ca)));a.Ca=b}},lookup(){throw bc[44];},Wa(a,b,c,d){return R.createNode(a,b,c,d)},rename(a,b,c){if(16384===(a.mode&61440)){try{var d=cc(b,c)}catch(f){}if(d)for(var e in d.za)throw new Q(55);}delete a.parent.za[a.name];a.parent.timestamp=Date.now();a.name=c;b.za[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink(a,b){delete a.za[b];a.timestamp=Date.now()},rmdir(a,b){var c=
cc(a,b),d;for(d in c.za)throw new Q(55);delete a.za[b];a.timestamp=Date.now()},readdir(a){var b=[".",".."],c;for(c in a.za)a.za.hasOwnProperty(c)&&b.push(c);return b},symlink(a,b,c){a=R.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new Q(28);return a.link}},Ba:{read(a,b,c,d,e){var f=a.node.za;if(e>=a.node.Ca)return 0;a=Math.min(a.node.Ca-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===
y.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.za||a.za.subarray)){if(f)return a.za=b.subarray(c,c+d),a.Ca=d;if(0===a.Ca&&0===e)return a.za=b.slice(c,c+d),a.Ca=d;if(e+d<=a.Ca)return a.za.set(b.subarray(c,c+d),e),d}Zb(a,e+d);if(a.za.subarray&&b.subarray)a.za.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.za[e+f]=b[c+f];a.Ca=Math.max(a.Ca,e+d);return d},Na(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Ca);if(0>b)throw new Q(28);return b},
Va(a,b,c){Zb(a.node,b+c);a.node.Ca=Math.max(a.node.Ca,b+c)},ab(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new Q(43);a=a.node.za;if(e&2||a.buffer!==y.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;x();b=void 0;if(!b)throw new Q(48);y.set(a,b)}else c=!1,b=a.byteOffset;return{Fa:b,Ga:c}},ob(a,b,c,d){R.Ba.write(a,b,0,d,c,!1);return 0}}},dc=(a,b,c)=>{var d=`al ${a}`;ja(a,e=>{e||x(`Loading data file "${a}" failed (no arrayBuffer).`);b(new Uint8Array(e));
d&&Da(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&Ca(d)},ec=h.preloadPlugins||[],fc=(a,b,c,d)=>{"undefined"!=typeof Browser&&Browser.lb();var e=!1;ec.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},hc=(a,b,c,d,e,f,k,l,m,n)=>{function q(g){function t(p){n&&n();l||gc(a,b,p,d,e,m);f&&f();Da(v)}fc(g,u,t,()=>{k&&k();Da(v)})||t(g)}var u=b?Qb(P(a+"/"+b)):a,v=`cp ${u}`;Ca(v);"string"==typeof c?dc(c,g=>q(g),k):q(c)},ic=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},
jc=null,kc={},lc=[],mc=1,S=null,nc=!0,Q=null,bc={};function T(a,b={}){a=Qb(a);if(!a)return{path:"",node:null};b=Object.assign({hb:!0,cb:0},b);if(8<b.cb)throw new Q(32);a=a.split("/").filter(k=>!!k);for(var c=jc,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=cc(c,a[e]);d=P(d+"/"+a[e]);c.Ua&&(!f||f&&b.hb)&&(c=c.Ua.root);if(!f||b.Za)for(f=0;40960===(c.mode&61440);)if(c=oc(d),d=Qb(Mb(d),c),c=T(d,{cb:b.cb+1}).node,40<f++)throw new Q(32);}return{path:d,node:c}}
function pc(a){for(var b;;){if(a===a.parent)return a=a.Ka.nb,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function qc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%S.length}function cc(a,b){var c;if(c=(c=rc(a,"x"))?c:a.Aa.lookup?0:2)throw new Q(c,a);for(c=S[qc(a.id,b)];c;c=c.Ra){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Aa.lookup(a,b)}
function ac(a,b,c,d){a=new sc(a,b,c,d);b=qc(a.parent.id,a.name);a.Ra=S[b];return S[b]=a}function tc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function rc(a,b){if(nc)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function uc(a,b){try{return cc(a,b),20}catch(c){}return rc(a,"wx")}function vc(){for(var a=0;4096>=a;a++)if(!lc[a])return a;throw new Q(33);}
function wc(a){a=lc[a];if(!a)throw new Q(8);return a}function xc(a){var b=-1;yc||(yc=function(){this.Da={}},yc.prototype={},Object.defineProperties(yc.prototype,{object:{get(){return this.node},set(c){this.node=c}},flags:{get(){return this.Da.flags},set(c){this.Da.flags=c}},position:{get(){return this.Da.position},set(c){this.Da.position=c}}}));a=Object.assign(new yc,a);-1==b&&(b=vc());a.fd=b;return lc[b]=a}var $b={open(a){a.Ba=kc[a.node.rdev].Ba;a.Ba.open&&a.Ba.open(a)},Na(){throw new Q(70);}};
function Vb(a,b){kc[a]={Ba:b}}function zc(a,b){var c="/"===b,d=!b;if(c&&jc)throw new Q(10);if(!c&&!d){var e=T(b,{hb:!1});b=e.path;e=e.node;if(e.Ua)throw new Q(10);if(16384!==(e.mode&61440))throw new Q(54);}b={type:a,ac:{},nb:b,Hb:[]};a=a.Ka(b);a.Ka=b;b.root=a;c?jc=a:e&&(e.Ua=b,e.Ka&&e.Ka.Hb.push(b))}function Ac(a,b,c){var d=T(a,{parent:!0}).node;a=Nb(a);if(!a||"."===a||".."===a)throw new Q(28);var e=uc(d,a);if(e)throw new Q(e);if(!d.Aa.Wa)throw new Q(63);return d.Aa.Wa(d,a,b,c)}
function U(a){return Ac(a,16895,0)}function Bc(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Ac(a,b|8192,c)}function Cc(a,b){if(!Qb(a))throw new Q(44);var c=T(b,{parent:!0}).node;if(!c)throw new Q(44);b=Nb(b);var d=uc(c,b);if(d)throw new Q(d);if(!c.Aa.symlink)throw new Q(63);c.Aa.symlink(c,b,a)}
function Dc(a){var b=T(a,{parent:!0}).node;if(!b)throw new Q(44);var c=Nb(a);a=cc(b,c);a:{try{var d=cc(b,c)}catch(f){d=f.Bb;break a}var e=rc(b,"wx");d=e?e:16384===(d.mode&61440)?31:0}if(d)throw new Q(d);if(!b.Aa.unlink)throw new Q(63);if(a.Ua)throw new Q(10);b.Aa.unlink(b,c);b=qc(a.parent.id,a.name);if(S[b]===a)S[b]=a.Ra;else for(b=S[b];b;){if(b.Ra===a){b.Ra=a.Ra;break}b=b.Ra}}
function oc(a){a=T(a).node;if(!a)throw new Q(44);if(!a.Aa.readlink)throw new Q(28);return Qb(pc(a.parent),a.Aa.readlink(a))}function Ec(a,b){a="string"==typeof a?T(a,{Za:!0}).node:a;if(!a.Aa.Ea)throw new Q(63);a.Aa.Ea(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Fc(a,b){if(""===a)throw new Q(44);if("string"==typeof b){var c={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof c)throw Error(`Unknown file open mode: ${b}`);b=c}var d=b&64?("undefined"==typeof d?438:d)&4095|32768:0;if("object"==typeof a)var e=a;else{a=P(a);try{e=T(a,{Za:!(b&131072)}).node}catch(f){}}c=!1;if(b&64)if(e){if(b&128)throw new Q(20);}else e=Ac(a,d,0),c=!0;if(!e)throw new Q(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new Q(54);
if(!c&&(d=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==tc(b)||b&512)?31:rc(e,tc(b)):44))throw new Q(d);if(b&512&&!c){d=e;d="string"==typeof d?T(d,{Za:!0}).node:d;if(!d.Aa.Ea)throw new Q(63);if(16384===(d.mode&61440))throw new Q(31);if(32768!==(d.mode&61440))throw new Q(28);if(c=rc(d,"w"))throw new Q(c);d.Aa.Ea(d,{size:0,timestamp:Date.now()})}b&=-131713;e=xc({node:e,path:pc(e),flags:b,seekable:!0,position:0,Ba:e.Ba,Nb:[],error:!1});e.Ba.open&&e.Ba.open(e);!h.logReadFiles||b&1||(Gc||
(Gc={}),a in Gc||(Gc[a]=1));return e}function Hc(){Q||(Q=function(a,b){this.name="ErrnoError";this.node=b;this.Ib=function(c){this.Bb=c};this.Ib(a);this.message="FS error"},Q.prototype=Error(),Q.prototype.constructor=Q,[44].forEach(a=>{bc[a]=new Q(a);bc[a].stack="<generic error, no stack>"}))}var Ic;function Jc(a,b){a="string"==typeof a?a:pc(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=P(a+"/"+c);try{U(d)}catch(e){}a=d}}return d}
function Kc(a,b,c,d){a=P(("string"==typeof a?a:pc(a))+"/"+b);c=ic(c,d);return Ac(a,(void 0!==c?c:438)&4095|32768,0)}
function gc(a,b,c,d,e,f){var k=b;a&&(a="string"==typeof a?a:pc(a),k=b?P(a+"/"+b):a);a=ic(d,e);k=Ac(k,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Ec(k,a|146);b=Fc(k,577);d=c;e=c.length;var l=0;if(0>e||0>l)throw new Q(28);if(null===b.fd)throw new Q(8);if(0===(b.flags&2097155))throw new Q(8);if(16384===(b.node.mode&61440))throw new Q(31);if(!b.Ba.write)throw new Q(28);if(b.seekable&&b.flags&1024){if(null===b.fd)throw new Q(8);
if(!b.seekable||!b.Ba.Na)throw new Q(70);b.position=b.Ba.Na(b,0,2);b.Nb=[]}c="undefined"!=typeof l;if(!c)l=b.position;else if(!b.seekable)throw new Q(70);f=b.Ba.write(b,d,0,e,l,f);c||(b.position+=f);if(null===b.fd)throw new Q(8);b.Db&&(b.Db=null);try{b.Ba.close&&b.Ba.close(b)}catch(m){throw m;}finally{lc[b.fd]=null}b.fd=null;Ec(k,a)}return k}
function V(a,b,c,d){a=P(("string"==typeof a?a:pc(a))+"/"+b);b=ic(!!c,!!d);V.mb||(V.mb=64);var e=V.mb++<<8|0;Vb(e,{open(f){f.seekable=!1},close(){d&&d.buffer&&d.buffer.length&&d(10)},read(f,k,l,m){for(var n=0,q=0;q<m;q++){try{var u=c()}catch(v){throw new Q(29);}if(void 0===u&&0===n)throw new Q(6);if(null===u||void 0===u)break;n++;k[l+q]=u}n&&(f.node.timestamp=Date.now());return n},write(f,k,l,m){for(var n=0;n<m;n++)try{d(k[l+n])}catch(q){throw new Q(29);}m&&(f.node.timestamp=Date.now());return n}});
return Bc(a,b,e)}function Lc(a){if(!(a.Fb||a.Gb||a.link||a.za)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ia)try{a.za=Sb(ia(a.url),!0),a.Ca=a.za.length}catch(b){throw new Q(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function Mc(a,b,c,d,e){function f(){this.$a=!1;this.Da=[]}f.prototype.get=function(q){if(!(q>this.length-1||0>q)){var u=q%this.chunkSize;return this.kb(q/this.chunkSize|0)[u]}};f.prototype.Qa=function(q){this.kb=q};f.prototype.fb=function(){var q=new XMLHttpRequest;q.open("HEAD",c,!1);q.send(null);if(!(200<=q.status&&300>q.status||304===q.status))throw Error("Couldn't load "+c+". Status: "+q.status);var u=Number(q.getResponseHeader("Content-length")),v,g=(v=q.getResponseHeader("Accept-Ranges"))&&
"bytes"===v;q=(v=q.getResponseHeader("Content-Encoding"))&&"gzip"===v;var t=1048576;g||(t=u);var p=this;p.Qa(E=>{var D=E*t,K=(E+1)*t-1;K=Math.min(K,u-1);if("undefined"==typeof p.Da[E]){var Ja=p.Da;if(D>K)throw Error("invalid range ("+D+", "+K+") or no bytes requested!");if(K>u-1)throw Error("only "+u+" bytes available! programmer error!");var L=new XMLHttpRequest;L.open("GET",c,!1);u!==t&&L.setRequestHeader("Range","bytes="+D+"-"+K);L.responseType="arraybuffer";L.overrideMimeType&&L.overrideMimeType("text/plain; charset=x-user-defined");
L.send(null);if(!(200<=L.status&&300>L.status||304===L.status))throw Error("Couldn't load "+c+". Status: "+L.status);D=void 0!==L.response?new Uint8Array(L.response||[]):Sb(L.responseText||"",!0);Ja[E]=D}if("undefined"==typeof p.Da[E])throw Error("doXHR failed!");return p.Da[E]});if(q||!u)t=u=1,t=u=this.kb(0).length,na("LazyFiles on gzip forces download of the whole file when length is accessed");this.yb=u;this.xb=t;this.$a=!0};if("undefined"!=typeof XMLHttpRequest){if(!fa)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";
var k=new f;Object.defineProperties(k,{length:{get:function(){this.$a||this.fb();return this.yb}},chunkSize:{get:function(){this.$a||this.fb();return this.xb}}});var l=void 0}else l=c,k=void 0;var m=Kc(a,b,d,e);k?m.za=k:l&&(m.za=null,m.url=l);Object.defineProperties(m,{Ca:{get:function(){return this.za.length}}});var n={};Object.keys(m.Ba).forEach(q=>{var u=m.Ba[q];n[q]=function(){Lc(m);return u.apply(null,arguments)}});n.read=(q,u,v,g,t)=>{Lc(m);q=q.node.za;if(t>=q.length)u=0;else{g=Math.min(q.length-
t,g);if(q.slice)for(var p=0;p<g;p++)u[v+p]=q[t+p];else for(p=0;p<g;p++)u[v+p]=q.get(t+p);u=g}return u};n.ab=()=>{Lc(m);x();throw new Q(48);};m.Ba=n;return m}
for(var yc,Gc,Nc=a=>0===a%4&&(0!==a%100||0===a%400),Oc=[31,29,31,30,31,30,31,31,30,31,30,31],Pc=[31,28,31,30,31,30,31,31,30,31,30,31],Qc=(a,b,c,d)=>{function e(g,t,p){for(g="number"==typeof g?g.toString():g||"";g.length<t;)g=p[0]+g;return g}function f(g,t){return e(g,t,"0")}function k(g,t){function p(D){return 0>D?-1:0<D?1:0}var E;0===(E=p(g.getFullYear()-t.getFullYear()))&&0===(E=p(g.getMonth()-t.getMonth()))&&(E=p(g.getDate()-t.getDate()));return E}function l(g){switch(g.getDay()){case 0:return new Date(g.getFullYear()-
1,11,29);case 1:return g;case 2:return new Date(g.getFullYear(),0,3);case 3:return new Date(g.getFullYear(),0,2);case 4:return new Date(g.getFullYear(),0,1);case 5:return new Date(g.getFullYear()-1,11,31);case 6:return new Date(g.getFullYear()-1,11,30)}}function m(g){var t=g.Oa;for(g=new Date((new Date(g.Pa+1900,0,1)).getTime());0<t;){var p=g.getMonth(),E=(Nc(g.getFullYear())?Oc:Pc)[p];if(t>E-g.getDate())t-=E-g.getDate()+1,g.setDate(1),11>p?g.setMonth(p+1):(g.setMonth(0),g.setFullYear(g.getFullYear()+
1));else{g.setDate(g.getDate()+t);break}}p=new Date(g.getFullYear()+1,0,4);t=l(new Date(g.getFullYear(),0,4));p=l(p);return 0>=k(t,g)?0>=k(p,g)?g.getFullYear()+1:g.getFullYear():g.getFullYear()-1}var n=B[d+40>>2];d={Lb:A[d>>2],Kb:A[d+4>>2],Xa:A[d+8>>2],eb:A[d+12>>2],Ya:A[d+16>>2],Pa:A[d+20>>2],Ja:A[d+24>>2],Oa:A[d+28>>2],bc:A[d+32>>2],Jb:A[d+36>>2],Mb:n?n?zb(z,n):"":""};c=c?zb(z,c):"";n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S",
"%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in n)c=c.replace(new RegExp(q,"g"),n[q]);var u="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),v="January February March April May June July August September October November December".split(" ");n={"%a":g=>u[g.Ja].substring(0,
3),"%A":g=>u[g.Ja],"%b":g=>v[g.Ya].substring(0,3),"%B":g=>v[g.Ya],"%C":g=>f((g.Pa+1900)/100|0,2),"%d":g=>f(g.eb,2),"%e":g=>e(g.eb,2," "),"%g":g=>m(g).toString().substring(2),"%G":g=>m(g),"%H":g=>f(g.Xa,2),"%I":g=>{g=g.Xa;0==g?g=12:12<g&&(g-=12);return f(g,2)},"%j":g=>{for(var t=0,p=0;p<=g.Ya-1;t+=(Nc(g.Pa+1900)?Oc:Pc)[p++]);return f(g.eb+t,3)},"%m":g=>f(g.Ya+1,2),"%M":g=>f(g.Kb,2),"%n":()=>"\n","%p":g=>0<=g.Xa&&12>g.Xa?"AM":"PM","%S":g=>f(g.Lb,2),"%t":()=>"\t","%u":g=>g.Ja||7,"%U":g=>f(Math.floor((g.Oa+
7-g.Ja)/7),2),"%V":g=>{var t=Math.floor((g.Oa+7-(g.Ja+6)%7)/7);2>=(g.Ja+371-g.Oa-2)%7&&t++;if(t)53==t&&(p=(g.Ja+371-g.Oa)%7,4==p||3==p&&Nc(g.Pa)||(t=1));else{t=52;var p=(g.Ja+7-g.Oa-1)%7;(4==p||5==p&&Nc(g.Pa%400-1))&&t++}return f(t,2)},"%w":g=>g.Ja,"%W":g=>f(Math.floor((g.Oa+7-(g.Ja+6)%7)/7),2),"%y":g=>(g.Pa+1900).toString().substring(2),"%Y":g=>g.Pa+1900,"%z":g=>{g=g.Jb;var t=0<=g;g=Math.abs(g)/60;return(t?"+":"-")+String("0000"+(g/60*100+g%60)).slice(-4)},"%Z":g=>g.Mb,"%%":()=>"%"};c=c.replace(/%%/g,
"\x00\x00");for(q in n)c.includes(q)&&(c=c.replace(new RegExp(q,"g"),n[q](d)));c=c.replace(/\0\0/g,"%");q=Sb(c,!1);if(q.length>b)return 0;y.set(q,a);return q.length-1},Rc=Array(256),Sc=0;256>Sc;++Sc)Rc[Sc]=String.fromCharCode(Sc);Ta=Rc;I=h.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};Ya=h.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};
Object.assign(ab.prototype,{get(a){return this.Ga[a]},has(a){return void 0!==this.Ga[a]},Va(a){var b=this.ib.pop()||this.Ga.length;this.Ga[b]=a;return b},Qa(a){this.Ga[a]=void 0;this.ib.push(a)}});M.Ga.push({value:void 0},{value:null},{value:!0},{value:!1});M.Da=M.Ga.length;h.count_emval_handles=()=>{for(var a=0,b=M.Da;b<M.Ga.length;++b)void 0!==M.Ga[b]&&++a;return a};
pb=h.UnboundTypeError=((a,b)=>{var c=ib(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
function sc(a,b,c,d){a||(a=this);this.parent=a;this.Ka=a.Ka;this.Ua=null;this.id=mc++;this.name=b;this.mode=c;this.Aa={};this.Ba={};this.rdev=d}Object.defineProperties(sc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Gb:{get:function(){return 16384===(this.mode&61440)}},Fb:{get:function(){return 8192===(this.mode&61440)}}});Hc();
S=Array(4096);zc(R,"/");U("/tmp");U("/home");U("/home/web_user");(function(){U("/dev");Vb(259,{read:()=>0,write:(d,e,f,k)=>k});Bc("/dev/null",259);Ub(1280,Xb);Ub(1536,Yb);Bc("/dev/tty",1280);Bc("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Pb(a).byteLength);return a[--b]};V("/dev","random",c);V("/dev","urandom",c);U("/dev/shm");U("/dev/shm/tmp")})();
(function(){U("/proc");var a=U("/proc/self");U("/proc/self/fd");zc({Ka(){var b=ac(a,"fd",16895,73);b.Aa={lookup(c,d){var e=wc(+d);c={parent:null,Ka:{nb:"fake"},Aa:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();h.FS_createPath=Jc;h.FS_createDataFile=gc;h.FS_createPreloadedFile=hc;h.FS_unlink=Dc;h.FS_createLazyFile=Mc;h.FS_createDevice=V;
var td={o:a=>{a=new Oa(a);a.tb()||(a.qb(!0),Na--);a.rb(!1);Ma.push(a);Tc(a.Ta);return a.ub()},s:()=>{W(0,0);var a=Ma.pop();Uc(a.Ta);G=0},a:()=>Sa([]),f:a=>Sa([a]),z:()=>{var a=Ma.pop();a||x("no exception to throw");var b=a.Ta;a.Cb()||(Ma.push(a),a.rb(!0),a.qb(!1),Na++);G=b;throw G;},j:(a,b,c)=>{(new Oa(a)).lb(b,c);G=a;Na++;throw G;},S:()=>Na,c:a=>{G||(G=a);throw G;},L:()=>{},X:(a,b,c,d)=>{b=H(b);J(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,f){return f?c:d},argPackAdvance:8,
readValueFromPointer:function(e){return this.fromWireType(z[e])},La:null})},W:(a,b)=>{b=H(b);J(a,{name:b,fromWireType:c=>{var d=cb(c);bb(c);return d},toWireType:(c,d)=>db(d),argPackAdvance:8,readValueFromPointer:eb,La:null})},F:(a,b,c)=>{b=H(b);J(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,argPackAdvance:8,readValueFromPointer:fb(b,c),La:null})},G:(a,b,c,d,e,f,k)=>{var l=mb(b,c);a=H(a);a=tb(a);e=ob(d,e);lb(a,function(){sb(`Cannot call ${a} due to unbound types`,l)},b-1);Za(l,function(m){var n=
[m[0],null].concat(m.slice(1)),q=m=a,u=e,v=n.length;if(2>v)throw new I("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var g=null!==n[1]&&!1,t=!1,p=1;p<n.length;++p)if(null!==n[p]&&void 0===n[p].La){t=!0;break}var E="void"!==n[0].name,D="",K="";for(p=0;p<v-2;++p)D+=(0!==p?", ":"")+"arg"+p,K+=(0!==p?", ":"")+"arg"+p+"Wired";q=`\n        return function ${gb(q)}(${D}) {\n        if (arguments.length !== ${v-2}) {\n          throwBindingError('function ${q} called with ' + arguments.length + ' arguments, expected ${v-
2}');\n        }`;t&&(q+="var destructors = [];\n");var Ja=t?"destructors":"null";D="throwBindingError invoker fn runDestructors retType classParam".split(" ");u=[Xa,u,f,hb,n[0],n[1]];g&&(q+="var thisWired = classParam.toWireType("+Ja+", this);\n");for(p=0;p<v-2;++p)q+="var arg"+p+"Wired = argType"+p+".toWireType("+Ja+", arg"+p+"); // "+n[p+2].name+"\n",D.push("argType"+p),u.push(n[p+2]);g&&(K="thisWired"+(0<K.length?", ":"")+K);q+=(E||k?"var rv = ":"")+"invoker(fn"+(0<K.length?", ":"")+K+");\n";
if(t)q+="runDestructors(destructors);\n";else for(p=g?1:2;p<n.length;++p)v=1===p?"thisWired":"arg"+(p-2)+"Wired",null!==n[p].La&&(q+=v+"_dtor("+v+"); // "+n[p].name+"\n",D.push(v+"_dtor"),u.push(n[p].La));E&&(q+="var ret = retType.fromWireType(rv);\nreturn ret;\n");D.push(q+"}\n");n=jb(D).apply(null,u);p=b-1;if(!h.hasOwnProperty(m))throw new Ya("Replacing nonexistant public symbol");void 0!==h[m].Ia&&void 0!==p?h[m].Ia[p]=n:(h[m]=n,h[m].zb=p);return[]})},q:(a,b,c,d,e)=>{b=H(b);-1===e&&(e=4294967295);
e=l=>l;if(0===d){var f=32-8*c;e=l=>l<<f>>>f}var k=b.includes("unsigned")?function(l,m){return m>>>0}:function(l,m){return m};J(a,{name:b,fromWireType:e,toWireType:k,argPackAdvance:8,readValueFromPointer:ub(b,c,0!==d),La:null})},m:(a,b,c)=>{function d(f){return new e(y.buffer,B[f+4>>2],B[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=H(c);J(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Eb:!0})},E:(a,b)=>{b=H(b);
var c="std::string"===b;J(a,{name:b,fromWireType:function(d){var e=B[d>>2],f=d+4;if(c)for(var k=f,l=0;l<=e;++l){var m=f+l;if(l==e||0==z[m]){k=k?zb(z,k,m-k):"";if(void 0===n)var n=k;else n+=String.fromCharCode(0),n+=k;k=m+1}}else{n=Array(e);for(l=0;l<e;++l)n[l]=String.fromCharCode(z[f+l]);n=n.join("")}O(d);return n},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"==typeof e;if(!(f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array))throw new I("Cannot pass non-string to std::string");
var k=c&&f?xb(e):e.length;var l=Vc(4+k+1),m=l+4;B[l>>2]=k;if(c&&f)wb(e,z,m,k+1);else if(f)for(f=0;f<k;++f){var n=e.charCodeAt(f);if(255<n)throw O(m),new I("String has UTF-16 code units that do not fit in 8 bits");z[m+f]=n}else for(f=0;f<k;++f)z[m+f]=e[f];null!==d&&d.push(O,l);return l},argPackAdvance:8,readValueFromPointer:vb,La(d){O(d)}})},A:(a,b,c)=>{c=H(c);if(2===b){var d=Bb;var e=Cb;var f=Db;var k=()=>sa;var l=1}else 4===b&&(d=Eb,e=Fb,f=Gb,k=()=>B,l=2);J(a,{name:c,fromWireType:m=>{for(var n=B[m>>
2],q=k(),u,v=m+4,g=0;g<=n;++g){var t=m+4+g*b;if(g==n||0==q[t>>l])v=d(v,t-v),void 0===u?u=v:(u+=String.fromCharCode(0),u+=v),v=t+b}O(m);return u},toWireType:(m,n)=>{if("string"!=typeof n)throw new I(`Cannot pass non-string to C++ string type ${c}`);var q=f(n),u=Vc(4+q+b);B[u>>2]=q>>l;e(n,u+4,q+b);null!==m&&m.push(O,u);return u},argPackAdvance:8,readValueFromPointer:eb,La(m){O(m)}})},Y:(a,b)=>{b=H(b);J(a,{Xb:!0,name:b,argPackAdvance:0,fromWireType:()=>{},toWireType:()=>{}})},H:bb,Z:a=>{4<a&&(M.get(a).pb+=
1)},B:a=>{var b=Hb[a];return db(void 0===b?H(a):b)},_:()=>db({}),I:(a,b,c)=>{a=cb(a);b=cb(b);c=cb(c);a[b]=c},J:(a,b)=>{var c=Va[a];if(void 0===c)throw a="_emval_take_value has unknown type "+rb(a),new I(a);a=c;a=a.readValueFromPointer(b);return db(a)},w:()=>{x("")},T:a=>{var b=z.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-pa.buffer.byteLength+65535)/65536;
try{pa.grow(e);va();var f=1;break a}catch(k){}f=void 0}if(f)return!0}return!1},U:(a,b)=>{var c=0;Kb().forEach((d,e)=>{var f=b+c;e=B[a+4*e>>2]=f;for(f=0;f<d.length;++f)y[e++>>0]=d.charCodeAt(f);y[e>>0]=0;c+=d.length+1});return 0},V:(a,b)=>{var c=Kb();B[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);B[b>>2]=d;return 0},O:(a,b)=>{Pb(z.subarray(a,a+b));return 0},x:Wc,y:Xc,k:Yc,b:Zc,e:$c,n:ad,g:bd,Q:cd,R:dd,p:ed,C:fd,v:gd,K:hd,h:jd,l:kd,d:ld,M:md,N:nd,i:od,D:pd,r:qd,t:rd,u:sd,P:(a,b,c,d)=>Qc(a,b,c,
d)},X=function(){function a(c){X=c.exports;pa=X.$;va();N=X.ca;xa.unshift(X.aa);Da("wasm-instantiate");return X}var b={a:td};Ca("wasm-instantiate");if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){w(`Module.instantiateWasm callback failed with error: ${c}`),ba(c)}Ka(b,function(c){a(c.instance)}).catch(ba);return{}}(),Vc=a=>(Vc=X.ba)(a),O=a=>(O=X.da)(a),qb=a=>(qb=X.ea)(a);h.__embind_initialize_bindings=()=>(h.__embind_initialize_bindings=X.fa)();h._fflush=a=>(h._fflush=X.ga)(a);
var W=(a,b)=>(W=X.ha)(a,b),Qa=a=>(Qa=X.ia)(a),Y=()=>(Y=X.ja)(),Z=a=>(Z=X.ka)(a),Uc=a=>(Uc=X.la)(a),Tc=a=>(Tc=X.ma)(a),Ra=(a,b,c)=>(Ra=X.na)(a,b,c),Pa=a=>(Pa=X.oa)(a);h.dynCall_jij=(a,b,c,d)=>(h.dynCall_jij=X.pa)(a,b,c,d);h.dynCall_ji=(a,b)=>(h.dynCall_ji=X.qa)(a,b);h.dynCall_jiij=(a,b,c,d,e)=>(h.dynCall_jiij=X.ra)(a,b,c,d,e);h.dynCall_jiijj=(a,b,c,d,e,f,k)=>(h.dynCall_jiijj=X.sa)(a,b,c,d,e,f,k);h.dynCall_iiij=(a,b,c,d,e)=>(h.dynCall_iiij=X.ta)(a,b,c,d,e);
h.dynCall_viijii=(a,b,c,d,e,f,k)=>(h.dynCall_viijii=X.ua)(a,b,c,d,e,f,k);var ud=h.dynCall_jiiii=(a,b,c,d,e)=>(ud=h.dynCall_jiiii=X.va)(a,b,c,d,e);h.dynCall_iiiiij=(a,b,c,d,e,f,k)=>(h.dynCall_iiiiij=X.wa)(a,b,c,d,e,f,k);h.dynCall_iiiiijj=(a,b,c,d,e,f,k,l,m)=>(h.dynCall_iiiiijj=X.xa)(a,b,c,d,e,f,k,l,m);h.dynCall_iiiiiijj=(a,b,c,d,e,f,k,l,m,n)=>(h.dynCall_iiiiiijj=X.ya)(a,b,c,d,e,f,k,l,m,n);function od(a,b,c,d){var e=Y();try{N.get(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}
function bd(a,b,c,d,e){var f=Y();try{return N.get(a)(b,c,d,e)}catch(k){Z(f);if(k!==k+0)throw k;W(1,0)}}function $c(a,b,c){var d=Y();try{return N.get(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;W(1,0)}}function kd(a,b){var c=Y();try{N.get(a)(b)}catch(d){Z(c);if(d!==d+0)throw d;W(1,0)}}function ad(a,b,c,d){var e=Y();try{return N.get(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}function Zc(a,b){var c=Y();try{return N.get(a)(b)}catch(d){Z(c);if(d!==d+0)throw d;W(1,0)}}
function ld(a,b,c){var d=Y();try{N.get(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;W(1,0)}}function jd(a){var b=Y();try{N.get(a)()}catch(c){Z(b);if(c!==c+0)throw c;W(1,0)}}function ed(a,b,c,d,e,f,k){var l=Y();try{return N.get(a)(b,c,d,e,f,k)}catch(m){Z(l);if(m!==m+0)throw m;W(1,0)}}function pd(a,b,c,d,e){var f=Y();try{N.get(a)(b,c,d,e)}catch(k){Z(f);if(k!==k+0)throw k;W(1,0)}}function dd(a,b,c,d,e,f){var k=Y();try{return N.get(a)(b,c,d,e,f)}catch(l){Z(k);if(l!==l+0)throw l;W(1,0)}}
function cd(a,b,c,d,e,f){var k=Y();try{return N.get(a)(b,c,d,e,f)}catch(l){Z(k);if(l!==l+0)throw l;W(1,0)}}function fd(a,b,c,d,e,f,k,l){var m=Y();try{return N.get(a)(b,c,d,e,f,k,l)}catch(n){Z(m);if(n!==n+0)throw n;W(1,0)}}function Xc(a,b,c,d){var e=Y();try{return N.get(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}function Wc(a,b,c,d){var e=Y();try{return N.get(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}
function Yc(a){var b=Y();try{return N.get(a)()}catch(c){Z(b);if(c!==c+0)throw c;W(1,0)}}function qd(a,b,c,d,e,f,k,l){var m=Y();try{N.get(a)(b,c,d,e,f,k,l)}catch(n){Z(m);if(n!==n+0)throw n;W(1,0)}}function gd(a,b,c,d,e,f,k,l,m,n,q,u){var v=Y();try{return N.get(a)(b,c,d,e,f,k,l,m,n,q,u)}catch(g){Z(v);if(g!==g+0)throw g;W(1,0)}}function rd(a,b,c,d,e,f,k,l,m,n,q){var u=Y();try{N.get(a)(b,c,d,e,f,k,l,m,n,q)}catch(v){Z(u);if(v!==v+0)throw v;W(1,0)}}
function sd(a,b,c,d,e,f,k,l,m,n,q,u,v,g,t,p){var E=Y();try{N.get(a)(b,c,d,e,f,k,l,m,n,q,u,v,g,t,p)}catch(D){Z(E);if(D!==D+0)throw D;W(1,0)}}function nd(a,b,c,d){var e=Y();try{N.get(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}function md(a,b,c,d){var e=Y();try{N.get(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}function hd(a,b,c,d,e){var f=Y();try{return ud(a,b,c,d,e)}catch(k){Z(f);if(k!==k+0)throw k;W(1,0)}}h.addRunDependency=Ca;h.removeRunDependency=Da;h.FS_createPath=Jc;
h.FS_createLazyFile=Mc;h.FS_createDevice=V;h.FS_createPreloadedFile=hc;h.FS_createDataFile=gc;h.FS_unlink=Dc;var vd;Ba=function wd(){vd||xd();vd||(Ba=wd)};
function xd(){function a(){if(!vd&&(vd=!0,h.calledRun=!0,!qa)){h.noFSInit||Ic||(Ic=!0,Hc(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?V("/dev","stdin",h.stdin):Cc("/dev/tty","/dev/stdin"),h.stdout?V("/dev","stdout",null,h.stdout):Cc("/dev/tty","/dev/stdout"),h.stderr?V("/dev","stderr",null,h.stderr):Cc("/dev/tty1","/dev/stderr"),Fc("/dev/stdin",0),Fc("/dev/stdout",1),Fc("/dev/stderr",1));nc=!1;La(xa);aa(h);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(h.postRun)for("function"==
typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var b=h.postRun.shift();ya.unshift(b)}La(ya)}}if(!(0<C)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)za();La(wa);0<C||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);a()},1)):a())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();xd();


  return moduleArg.ready
}

);
})();
export default Module;