
var Module = (() => {
  var _scriptDir = import.meta.url;
  
  return (
async function(moduleArg = {}) {

var k=moduleArg,ba,ca;k.ready=new Promise((a,b)=>{ba=a;ca=b});k.kc=!0;k.lc=!0;
"object"!==typeof WebAssembly&&"undefined"!==typeof WXWebAssembly&&(WXWebAssembly.RuntimeError=WXWebAssembly.RuntimeError||function(){class a extends Error{constructor(b){super(b);this instanceof a||(b=Object.setPrototypeOf,"function"===typeof b?b.call(Object,this,a.prototype):this.__proto__=a.prototype,"function"===typeof Error.captureStackTrace&&Error.captureStackTrace(this,a))}}Object.defineProperty(a.prototype,"name",{configurable:!0,writable:!0,value:"RuntimeError"});return a}(),function(){if("undefined"!==
typeof globalThis)return globalThis;var a=function(){return this}(),b=function(){try{var c=new Function}catch(d){return!1}return"function"===typeof c}();if(!a&&b)try{a=(new Function("return this"))()}catch(c){}if(!a){if("undefined"===typeof __webpack_public_path__&&"undefined"!==typeof global)return global;if("undefined"!==typeof window)return window;if("undefined"!==typeof self)return self}return a}().WebAssembly=WXWebAssembly);
var da=Object.assign({},k),ea="./this.program",fa="object"==typeof window,ha="function"==typeof importScripts,ia="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,q="",ja,ka,la;
if(ia){const {createRequire:a}=await import("module");var require=a(import.meta.url),fs=require("fs"),ma=require("path");ha?q=ma.dirname(q)+"/":q=require("url").fileURLToPath(new URL("./",import.meta.url));ja=(b,c)=>{b=na(b)?new URL(b):ma.normalize(b);return fs.readFileSync(b,c?void 0:"utf8")};la=b=>{b=ja(b,!0);b.buffer||(b=new Uint8Array(b));return b};ka=(b,c,d,e=!0)=>{b=na(b)?new URL(b):ma.normalize(b);fs.readFile(b,e?void 0:"utf8",(f,h)=>{f?d(f):c(e?h.buffer:h)})};
!k.thisProgram&&1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);k.inspect=()=>"[Emscripten Module object]"}else if(fa||ha)ha?q=self.location.href:"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src),_scriptDir&&(q=_scriptDir),0!==q.indexOf("blob:")?q=q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):q="",ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(la=a=>{var b=new XMLHttpRequest;
b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ka=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var oa=k.print||console.log.bind(console),pa=k.printErr||console.error.bind(console);Object.assign(k,da);da=null;k.thisProgram&&(ea=k.thisProgram);var qa;k.wasmBinary&&(qa=k.wasmBinary);"object"!=typeof WebAssembly&&ra("no native wasm support detected");
var sa,ta=!1,w,x,y,ua,A,B,va,wa;function xa(){var a=sa.buffer;k.HEAP8=w=new Int8Array(a);k.HEAP16=y=new Int16Array(a);k.HEAPU8=x=new Uint8Array(a);k.HEAPU16=ua=new Uint16Array(a);k.HEAP32=A=new Int32Array(a);k.HEAPU32=B=new Uint32Array(a);k.HEAPF32=va=new Float32Array(a);k.HEAPF64=wa=new Float64Array(a)}var ya=[],za=[],Aa=[];function Ba(){var a=k.preRun.shift();ya.unshift(a)}var Ca=0,Da=null,Ea=null;function Fa(){Ca++;k.monitorRunDependencies&&k.monitorRunDependencies(Ca)}
function Ga(){Ca--;k.monitorRunDependencies&&k.monitorRunDependencies(Ca);if(0==Ca&&(null!==Da&&(clearInterval(Da),Da=null),Ea)){var a=Ea;Ea=null;a()}}function ra(a){if(k.onAbort)k.onAbort(a);a="Aborted("+a+")";pa(a);ta=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ca(a);throw a;}var Ha=a=>a.startsWith("data:application/octet-stream;base64,"),na=a=>a.startsWith("file://"),Ia;
if(k.locateFile){if(Ia="wordart_generate.wasm?version=1.0.0",!Ha(Ia)){var Ja=Ia;Ia=k.locateFile?k.locateFile(Ja,q):q+Ja}}else Ia=(new URL("wordart_generate.wasm?version=1.0.0",import.meta.url)).href;function Ka(a){if(a==Ia&&qa)return new Uint8Array(qa);if(la)return la(a);throw"both async and sync fetching of the wasm failed";}
function La(a){if(!qa&&(fa||ha)){if("function"==typeof fetch&&!na(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Ka(a));if(ka)return new Promise((b,c)=>{ka(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Ka(a))}function Ma(a,b,c){return La(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{pa(`failed to asynchronously prepare wasm: ${d}`);ra(d)})}
function Na(a,b){var c=Ia;return qa||"function"!=typeof WebAssembly.instantiateStreaming||Ha(c)||na(c)||ia||"function"!=typeof fetch?Ma(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){pa(`wasm streaming compile failed: ${e}`);pa("falling back to ArrayBuffer instantiation");return Ma(c,a,b)}))}var C,E,Oa=a=>{for(;0<a.length;)a.shift()(k)},Pa=[],Qa=0,F=0;
function Ra(a){this.gb=a;this.Qa=a-24;this.Jb=function(b){B[this.Qa+4>>2]=b};this.Oa=function(){return B[this.Qa+4>>2]};this.Ib=function(b){B[this.Qa+8>>2]=b};this.Db=function(b){w[this.Qa+12>>0]=b?1:0};this.Gb=function(){return 0!=w[this.Qa+12>>0]};this.Eb=function(b){w[this.Qa+13>>0]=b?1:0};this.Ob=function(){return 0!=w[this.Qa+13>>0]};this.zb=function(b,c){this.eb(0);this.Jb(b);this.Ib(c)};this.eb=function(b){B[this.Qa+16>>2]=b};this.Fb=function(){return B[this.Qa+16>>2]};this.Hb=function(){if(Sa(this.Oa()))return B[this.gb>>
2];var b=this.Fb();return 0!==b?b:this.gb}}
var Va=a=>{var b=F;if(!b)return Ta(0),0;var c=new Ra(b);c.eb(b);var d=c.Oa();if(!d)return Ta(0),b;for(var e in a){var f=a[e];if(0===f||f===d)break;if(Ua(f,d,c.Qa+16))return Ta(f),b}Ta(d);return b},Wa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},G=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Wa(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?
"/":"")+a},Xa=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},Ya=a=>{if("/"===a)return"/";a=G(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Za=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(ia)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;
return c=>(c.set(b(c.byteLength)),c)}catch(c){}ra("initRandomDevice")},$a=a=>($a=Za())(a);function ab(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Wa(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}
var bb="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,H=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&bb)return bb.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
cb=[],db=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},eb=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var m=a.charCodeAt(++f);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&
63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e};function fb(a,b){var c=Array(db(a)+1);a=eb(a,c,0,c.length);b&&(c.length=a);return c}var gb=[];function hb(a,b){gb[a]={input:[],output:[],Ya:b};ib(a,jb)}
var jb={open(a){var b=gb[a.node.rdev];if(!b)throw new I(43);a.tty=b;a.seekable=!1},close(a){a.tty.Ya.fsync(a.tty)},fsync(a){a.tty.Ya.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Ya.xb)throw new I(60);for(var e=0,f=0;f<d;f++){try{var h=a.tty.Ya.xb(a.tty)}catch(m){throw new I(29);}if(void 0===h&&0===e)throw new I(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Ya.qb)throw new I(60);try{for(var e=0;e<d;e++)a.tty.Ya.qb(a.tty,b[c+
e])}catch(f){throw new I(29);}d&&(a.node.timestamp=Date.now());return e}},kb={xb(){a:{if(!cb.length){var a=null;if(ia){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c?a=b.slice(0,c).toString("utf-8"):a=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}cb=fb(a,!0)}a=
cb.shift()}return a},qb(a,b){null===b||10===b?(oa(H(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(oa(H(a.output,0)),a.output=[])},Rb(){return{ec:25856,hc:5,dc:191,fc:35387,cc:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Sb(){return 0},Tb(){return[24,80]}},lb={qb(a,b){null===b||10===b?(pa(H(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(pa(H(a.output,0)),a.output=[])}},nb=a=>{a=65536*
Math.ceil(a/65536);var b=mb(65536,a);b?(x.fill(0,b,b+a),a=b):a=0;return a};function ob(a,b){var c=a.La?a.La.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.La,a.La=new Uint8Array(b),0<a.Na&&a.La.set(c.subarray(0,a.Na),0))}
var J={Ua:null,Xa(){return J.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new I(63);J.Ua||(J.Ua={dir:{node:{Ta:J.Ka.Ta,Sa:J.Ka.Sa,lookup:J.Ka.lookup,lb:J.Ka.lb,rename:J.Ka.rename,unlink:J.Ka.unlink,rmdir:J.Ka.rmdir,readdir:J.Ka.readdir,symlink:J.Ka.symlink},stream:{ab:J.Ma.ab}},file:{node:{Ta:J.Ka.Ta,Sa:J.Ka.Sa},stream:{ab:J.Ma.ab,read:J.Ma.read,write:J.Ma.write,kb:J.Ma.kb,ib:J.Ma.ib,mb:J.Ma.mb}},link:{node:{Ta:J.Ka.Ta,Sa:J.Ka.Sa,readlink:J.Ka.readlink},
stream:{}},ub:{node:{Ta:J.Ka.Ta,Sa:J.Ka.Sa},stream:pb}});c=qb(a,b,c,d);L(c.mode)?(c.Ka=J.Ua.dir.node,c.Ma=J.Ua.dir.stream,c.La={}):32768===(c.mode&61440)?(c.Ka=J.Ua.file.node,c.Ma=J.Ua.file.stream,c.Na=0,c.La=null):40960===(c.mode&61440)?(c.Ka=J.Ua.link.node,c.Ma=J.Ua.link.stream):8192===(c.mode&61440)&&(c.Ka=J.Ua.ub.node,c.Ma=J.Ua.ub.stream);c.timestamp=Date.now();a&&(a.La[b]=c,a.timestamp=c.timestamp);return c},ic(a){return a.La?a.La.subarray?a.La.subarray(0,a.Na):new Uint8Array(a.La):new Uint8Array(0)},
Ka:{Ta(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;L(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.Na:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Nb=4096;b.blocks=Math.ceil(b.size/b.Nb);return b},Sa(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.Na!=b))if(0==
b)a.La=null,a.Na=0;else{var c=a.La;a.La=new Uint8Array(b);c&&a.La.set(c.subarray(0,Math.min(b,a.Na)));a.Na=b}},lookup(){throw rb[44];},lb(a,b,c,d){return J.createNode(a,b,c,d)},rename(a,b,c){if(L(a.mode)){try{var d=sb(b,c)}catch(f){}if(d)for(var e in d.La)throw new I(55);}delete a.parent.La[a.name];a.parent.timestamp=Date.now();a.name=c;b.La[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink(a,b){delete a.La[b];a.timestamp=Date.now()},rmdir(a,b){var c=sb(a,b),d;for(d in c.La)throw new I(55);delete a.La[b];
a.timestamp=Date.now()},readdir(a){var b=[".",".."],c;for(c in a.La)a.La.hasOwnProperty(c)&&b.push(c);return b},symlink(a,b,c){a=J.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new I(28);return a.link}},Ma:{read(a,b,c,d,e){var f=a.node.La;if(e>=a.node.Na)return 0;a=Math.min(a.node.Na-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===w.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=
Date.now();if(b.subarray&&(!a.La||a.La.subarray)){if(f)return a.La=b.subarray(c,c+d),a.Na=d;if(0===a.Na&&0===e)return a.La=b.slice(c,c+d),a.Na=d;if(e+d<=a.Na)return a.La.set(b.subarray(c,c+d),e),d}ob(a,e+d);if(a.La.subarray&&b.subarray)a.La.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.La[e+f]=b[c+f];a.Na=Math.max(a.Na,e+d);return d},ab(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Na);if(0>b)throw new I(28);return b},kb(a,b,c){ob(a.node,b+c);a.node.Na=Math.max(a.node.Na,
b+c)},ib(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new I(43);a=a.node.La;if(e&2||a.buffer!==w.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;b=nb(b);if(!b)throw new I(48);w.set(a,b)}else c=!1,b=a.byteOffset;return{Qa:b,Ra:c}},mb(a,b,c,d){J.Ma.write(a,b,0,d,c,!1);return 0}}},tb=(a,b,c)=>{var d=`al ${a}`;ka(a,e=>{e||ra(`Loading data file "${a}" failed (no arrayBuffer).`);b(new Uint8Array(e));d&&Ga(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;
});d&&Fa(d)},ub=k.preloadPlugins||[],vb=(a,b,c,d)=>{"undefined"!=typeof Browser&&Browser.zb();var e=!1;ub.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},xb=(a,b,c,d,e,f,h,m,n,l)=>{function u(g){function v(r){l&&l();m||wb(a,b,r,d,e,n);f&&f();Ga(t)}vb(g,p,v,()=>{h&&h();Ga(t)})||v(g)}var p=b?ab(G(a+"/"+b)):a,t=`cp ${p}`;Fa(t);"string"==typeof c?tb(c,g=>u(g),h):u(c)},yb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},zb=null,Ab={},Bb=[],Cb=1,Db=null,Eb=!0,I=null,rb={};
function M(a,b={}){a=ab(a);if(!a)return{path:"",node:null};b=Object.assign({vb:!0,rb:0},b);if(8<b.rb)throw new I(32);a=a.split("/").filter(h=>!!h);for(var c=zb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=sb(c,a[e]);d=G(d+"/"+a[e]);c.jb&&(!f||f&&b.vb)&&(c=c.jb.root);if(!f||b.hb)for(f=0;40960===(c.mode&61440);)if(c=Fb(d),d=ab(Xa(d),c),c=M(d,{rb:b.rb+1}).node,40<f++)throw new I(32);}return{path:d,node:c}}
function Gb(a){for(var b;;){if(a===a.parent)return a=a.Xa.Bb,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Hb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Db.length}function sb(a,b){var c;if(c=(c=Ib(a,"x"))?c:a.Ka.lookup?0:2)throw new I(c,a);for(c=Db[Hb(a.id,b)];c;c=c.fb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Ka.lookup(a,b)}
function qb(a,b,c,d){a=new Jb(a,b,c,d);b=Hb(a.parent.id,a.name);a.fb=Db[b];return Db[b]=a}function L(a){return 16384===(a&61440)}function Kb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Ib(a,b){if(Eb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Lb(a,b){try{return sb(a,b),20}catch(c){}return Ib(a,"wx")}function Mb(){for(var a=0;4096>=a;a++)if(!Bb[a])return a;throw new I(33);}
function N(a){a=Bb[a];if(!a)throw new I(8);return a}function Nb(a,b=-1){Ob||(Ob=function(){this.Oa={}},Ob.prototype={},Object.defineProperties(Ob.prototype,{object:{get(){return this.node},set(c){this.node=c}},flags:{get(){return this.Oa.flags},set(c){this.Oa.flags=c}},position:{get(){return this.Oa.position},set(c){this.Oa.position=c}}}));a=Object.assign(new Ob,a);-1==b&&(b=Mb());a.fd=b;return Bb[b]=a}var pb={open(a){a.Ma=Ab[a.node.rdev].Ma;a.Ma.open&&a.Ma.open(a)},ab(){throw new I(70);}};
function ib(a,b){Ab[a]={Ma:b}}function Pb(a,b){var c="/"===b,d=!b;if(c&&zb)throw new I(10);if(!c&&!d){var e=M(b,{vb:!1});b=e.path;e=e.node;if(e.jb)throw new I(10);if(!L(e.mode))throw new I(54);}b={type:a,nc:{},Bb:b,Wb:[]};a=a.Xa(b);a.Xa=b;b.root=a;c?zb=a:e&&(e.jb=b,e.Xa&&e.Xa.Wb.push(b))}function Qb(a,b,c){var d=M(a,{parent:!0}).node;a=Ya(a);if(!a||"."===a||".."===a)throw new I(28);var e=Lb(d,a);if(e)throw new I(e);if(!d.Ka.lb)throw new I(63);return d.Ka.lb(d,a,b,c)}
function P(a){return Qb(a,16895,0)}function Rb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Qb(a,b|8192,c)}function Sb(a,b){if(!ab(a))throw new I(44);var c=M(b,{parent:!0}).node;if(!c)throw new I(44);b=Ya(b);var d=Lb(c,b);if(d)throw new I(d);if(!c.Ka.symlink)throw new I(63);c.Ka.symlink(c,b,a)}
function Tb(a){var b=M(a,{parent:!0}).node;if(!b)throw new I(44);var c=Ya(a);a=sb(b,c);a:{try{var d=sb(b,c)}catch(f){d=f.Pa;break a}var e=Ib(b,"wx");d=e?e:L(d.mode)?31:0}if(d)throw new I(d);if(!b.Ka.unlink)throw new I(63);if(a.jb)throw new I(10);b.Ka.unlink(b,c);b=Hb(a.parent.id,a.name);if(Db[b]===a)Db[b]=a.fb;else for(b=Db[b];b;){if(b.fb===a){b.fb=a.fb;break}b=b.fb}}function Fb(a){a=M(a).node;if(!a)throw new I(44);if(!a.Ka.readlink)throw new I(28);return ab(Gb(a.parent),a.Ka.readlink(a))}
function Ub(a,b){a=M(a,{hb:!b}).node;if(!a)throw new I(44);if(!a.Ka.Ta)throw new I(63);return a.Ka.Ta(a)}function Vb(a){return Ub(a,!0)}function Wb(a,b){a="string"==typeof a?M(a,{hb:!0}).node:a;if(!a.Ka.Sa)throw new I(63);a.Ka.Sa(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Xb(a,b,c){if(""===a)throw new I(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=G(a);try{e=M(a,{hb:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new I(20);}else e=Qb(a,c,0),d=!0;if(!e)throw new I(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&!L(e.mode))throw new I(54);if(!d&&(c=
e?40960===(e.mode&61440)?32:L(e.mode)&&("r"!==Kb(b)||b&512)?31:Ib(e,Kb(b)):44))throw new I(c);if(b&512&&!d){c=e;c="string"==typeof c?M(c,{hb:!0}).node:c;if(!c.Ka.Sa)throw new I(63);if(L(c.mode))throw new I(31);if(32768!==(c.mode&61440))throw new I(28);if(d=Ib(c,"w"))throw new I(d);c.Ka.Sa(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Nb({node:e,path:Gb(e),flags:b,seekable:!0,position:0,Ma:e.Ma,bc:[],error:!1});e.Ma.open&&e.Ma.open(e);!k.logReadFiles||b&1||(Yb||(Yb={}),a in Yb||(Yb[a]=1));return e}
function Zb(a){if(null===a.fd)throw new I(8);a.$a&&(a.$a=null);try{a.Ma.close&&a.Ma.close(a)}catch(b){throw b;}finally{Bb[a.fd]=null}a.fd=null}function $b(a,b,c){if(null===a.fd)throw new I(8);if(!a.seekable||!a.Ma.ab)throw new I(70);if(0!=c&&1!=c&&2!=c)throw new I(28);a.position=a.Ma.ab(a,b,c);a.bc=[];return a.position}
function ac(a,b,c,d,e,f){if(0>d||0>e)throw new I(28);if(null===a.fd)throw new I(8);if(0===(a.flags&2097155))throw new I(8);if(L(a.node.mode))throw new I(31);if(!a.Ma.write)throw new I(28);a.seekable&&a.flags&1024&&$b(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new I(70);b=a.Ma.write(a,b,c,d,e,f);h||(a.position+=b);return b}
function bc(){I||(I=function(a,b){this.name="ErrnoError";this.node=b;this.Xb=function(c){this.Pa=c};this.Xb(a);this.message="FS error"},I.prototype=Error(),I.prototype.constructor=I,[44].forEach(a=>{rb[a]=new I(a);rb[a].stack="<generic error, no stack>"}))}var cc;function dc(a,b){a="string"==typeof a?a:Gb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=G(a+"/"+c);try{P(d)}catch(e){}a=d}}return d}
function ec(a,b,c,d){a=G(("string"==typeof a?a:Gb(a))+"/"+b);c=yb(c,d);return Qb(a,(void 0!==c?c:438)&4095|32768,0)}function wb(a,b,c,d,e,f){var h=b;a&&(a="string"==typeof a?a:Gb(a),h=b?G(a+"/"+b):a);a=yb(d,e);h=Qb(h,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Wb(h,a|146);b=Xb(h,577);ac(b,c,0,c.length,0,f);Zb(b);Wb(h,a)}return h}
function Q(a,b,c,d){a=G(("string"==typeof a?a:Gb(a))+"/"+b);b=yb(!!c,!!d);Q.Ab||(Q.Ab=64);var e=Q.Ab++<<8|0;ib(e,{open(f){f.seekable=!1},close(){d&&d.buffer&&d.buffer.length&&d(10)},read(f,h,m,n){for(var l=0,u=0;u<n;u++){try{var p=c()}catch(t){throw new I(29);}if(void 0===p&&0===l)throw new I(6);if(null===p||void 0===p)break;l++;h[m+u]=p}l&&(f.node.timestamp=Date.now());return l},write(f,h,m,n){for(var l=0;l<n;l++)try{d(h[m+l])}catch(u){throw new I(29);}n&&(f.node.timestamp=Date.now());return l}});
return Rb(a,b,e)}function fc(a){if(!(a.Ub||a.Vb||a.link||a.La)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ja)try{a.La=fb(ja(a.url),!0),a.Na=a.La.length}catch(b){throw new I(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function gc(a,b,c,d,e){function f(){this.pb=!1;this.Oa=[]}function h(p,t,g,v,r){p=p.node.La;if(r>=p.length)return 0;v=Math.min(p.length-r,v);if(p.slice)for(var z=0;z<v;z++)t[g+z]=p[r+z];else for(z=0;z<v;z++)t[g+z]=p.get(r+z);return v}f.prototype.get=function(p){if(!(p>this.length-1||0>p)){var t=p%this.chunkSize;return this.yb(p/this.chunkSize|0)[t]}};f.prototype.eb=function(p){this.yb=p};f.prototype.tb=function(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||
304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);var t=Number(p.getResponseHeader("Content-length")),g,v=(g=p.getResponseHeader("Accept-Ranges"))&&"bytes"===g;p=(g=p.getResponseHeader("Content-Encoding"))&&"gzip"===g;var r=1048576;v||(r=t);var z=this;z.eb(D=>{var K=D*r,aa=(D+1)*r-1;aa=Math.min(aa,t-1);if("undefined"==typeof z.Oa[D]){var Sc=z.Oa;if(K>aa)throw Error("invalid range ("+K+", "+aa+") or no bytes requested!");if(aa>t-1)throw Error("only "+t+" bytes available! programmer error!");
var O=new XMLHttpRequest;O.open("GET",c,!1);t!==r&&O.setRequestHeader("Range","bytes="+K+"-"+aa);O.responseType="arraybuffer";O.overrideMimeType&&O.overrideMimeType("text/plain; charset=x-user-defined");O.send(null);if(!(200<=O.status&&300>O.status||304===O.status))throw Error("Couldn't load "+c+". Status: "+O.status);K=void 0!==O.response?new Uint8Array(O.response||[]):fb(O.responseText||"",!0);Sc[D]=K}if("undefined"==typeof z.Oa[D])throw Error("doXHR failed!");return z.Oa[D]});if(p||!t)r=t=1,r=
t=this.yb(0).length,oa("LazyFiles on gzip forces download of the whole file when length is accessed");this.Lb=t;this.Kb=r;this.pb=!0};if("undefined"!=typeof XMLHttpRequest){if(!ha)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var m=new f;Object.defineProperties(m,{length:{get:function(){this.pb||this.tb();return this.Lb}},chunkSize:{get:function(){this.pb||this.tb();return this.Kb}}});var n=void 0}else n=c,m=void 0;var l=
ec(a,b,d,e);m?l.La=m:n&&(l.La=null,l.url=n);Object.defineProperties(l,{Na:{get:function(){return this.La.length}}});var u={};Object.keys(l.Ma).forEach(p=>{var t=l.Ma[p];u[p]=function(){fc(l);return t.apply(null,arguments)}});u.read=(p,t,g,v,r)=>{fc(l);return h(p,t,g,v,r)};u.ib=(p,t,g)=>{fc(l);var v=nb(t);if(!v)throw new I(48);h(p,w,v,t,g);return{Qa:v,Ra:!0}};l.Ma=u;return l}var R={},Ob,Yb;
function hc(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?"/":N(a).path;if(0==b.length){if(!c)throw new I(44);return a}return G(a+"/"+b)}
function ic(a,b,c){try{var d=a(b)}catch(f){if(f&&f.node&&G(b)!==G(Gb(f.node)))return-54;throw f;}A[c>>2]=d.dev;A[c+4>>2]=d.mode;B[c+8>>2]=d.nlink;A[c+12>>2]=d.uid;A[c+16>>2]=d.gid;A[c+20>>2]=d.rdev;E=[d.size>>>0,(C=d.size,1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];A[c+24>>2]=E[0];A[c+28>>2]=E[1];A[c+32>>2]=4096;A[c+36>>2]=d.blocks;a=d.atime.getTime();b=d.mtime.getTime();var e=d.ctime.getTime();E=[Math.floor(a/1E3)>>>0,(C=Math.floor(a/1E3),1<=
+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];A[c+40>>2]=E[0];A[c+44>>2]=E[1];B[c+48>>2]=a%1E3*1E3;E=[Math.floor(b/1E3)>>>0,(C=Math.floor(b/1E3),1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];A[c+56>>2]=E[0];A[c+60>>2]=E[1];B[c+64>>2]=b%1E3*1E3;E=[Math.floor(e/1E3)>>>0,(C=Math.floor(e/1E3),1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];A[c+72>>2]=E[0];
A[c+76>>2]=E[1];B[c+80>>2]=e%1E3*1E3;E=[d.ino>>>0,(C=d.ino,1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];A[c+88>>2]=E[0];A[c+92>>2]=E[1];return 0}var jc=void 0;function kc(){var a=A[+jc>>2];jc+=4;return a}
var lc,S=a=>{for(var b="";x[a];)b+=lc[x[a++]];return b},mc={},nc={},oc={},T,pc=a=>{throw new T(a);},qc,sc=(a,b)=>{function c(m){m=b(m);if(m.length!==d.length)throw new qc("Mismatched type converter count");for(var n=0;n<d.length;++n)rc(d[n],m[n])}var d=[];d.forEach(function(m){oc[m]=a});var e=Array(a.length),f=[],h=0;a.forEach((m,n)=>{nc.hasOwnProperty(m)?e[n]=nc[m]:(f.push(m),mc.hasOwnProperty(m)||(mc[m]=[]),mc[m].push(()=>{e[n]=nc[m];++h;h===f.length&&c(e)}))});0===f.length&&c(e)};
function tc(a,b,c={}){var d=b.name;if(!a)throw new T(`type "${d}" must have a positive integer typeid pointer`);if(nc.hasOwnProperty(a)){if(c.Pb)return;throw new T(`Cannot register type '${d}' twice`);}nc[a]=b;delete oc[a];mc.hasOwnProperty(a)&&(b=mc[a],delete mc[a],b.forEach(e=>e()))}function rc(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");tc(a,b,c)}function uc(){this.Ra=[void 0];this.wb=[]}
var U=new uc,vc=a=>{a>=U.Oa&&0===--U.get(a).Cb&&U.eb(a)},wc=a=>{if(!a)throw new T("Cannot use deleted val. handle = "+a);return U.get(a).value},xc=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:return U.kb({Cb:1,value:a})}};function yc(a){return this.fromWireType(A[a>>2])}
var zc=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(va[c>>2])};case 8:return function(c){return this.fromWireType(wa[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Ac=a=>{if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a},Bc=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Cc(a,b){a=Ac(a);return{[a]:function(){return b.apply(this,arguments)}}[a]}
function Dc(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=Cc(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
var Ec=(a,b)=>{if(void 0===k[a].Va){var c=k[a];k[a]=function(){if(!k[a].Va.hasOwnProperty(arguments.length))throw new T(`Function '${b}' called with an invalid number of arguments (${arguments.length}) - expects one of (${k[a].Va})!`);return k[a].Va[arguments.length].apply(this,arguments)};k[a].Va=[];k[a].Va[c.Mb]=c}},Fc=(a,b,c)=>{if(k.hasOwnProperty(a)){if(void 0===c||void 0!==k[a].Va&&void 0!==k[a].Va[c])throw new T(`Cannot register public name '${a}' twice`);Ec(a,a);if(k.hasOwnProperty(c))throw new T(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
k[a].Va[c]=b}else k[a]=b,void 0!==c&&(k[a].mc=c)},Gc=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(B[b+4*d>>2]);return c},V,Hc=(a,b)=>{var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=k["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=V.get(b).apply(null,c);return d}},Ic=(a,b)=>{a=S(a);var c=a.includes("j")?Hc(a,b):V.get(b);if("function"!=typeof c)throw new T(`unknown function pointer with signature ${a}: ${b}`);return c},Jc,Mc=a=>{a=
Kc(a);var b=S(a);Lc(a);return b},Nc=(a,b)=>{function c(f){e[f]||nc[f]||(oc[f]?oc[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Jc(`${a}: `+d.map(Mc).join([", "]));},Oc=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?(")"==a[a.length-1]||ra("Parentheses for argument names should match."),a.substr(0,b)):a},Pc=(a,b,c)=>{switch(b){case 1:return c?d=>w[d>>0]:d=>x[d>>0];case 2:return c?d=>y[d>>1]:d=>ua[d>>1];case 4:return c?d=>A[d>>2]:d=>B[d>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);
}};function Qc(a){return this.fromWireType(B[a>>2])}
var Rc="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Tc=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&ua[c];)++c;c<<=1;if(32<c-a&&Rc)return Rc.decode(x.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=y[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},Uc=(a,b,c)=>{void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)y[b>>1]=a.charCodeAt(e),b+=2;y[b>>1]=0;return b-d},Vc=a=>2*a.length,Wc=(a,b)=>{for(var c=0,d="";!(c>=b/
4);){var e=A[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},Xc=(a,b,c)=>{void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var h=a.charCodeAt(++e);f=65536+((f&1023)<<10)|h&1023}A[b>>2]=f;b+=4;if(b+4>c)break}A[b>>2]=0;return b-d},Yc=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},Zc={},
$c={},bd=()=>{if(!ad){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in $c)void 0===$c[b]?delete a[b]:a[b]=$c[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);ad=c}return ad},ad,cd=a=>0===a%4&&(0!==a%100||0===a%400),dd=[31,29,31,30,31,30,31,31,30,31,30,31],ed=[31,28,31,30,31,30,31,31,30,31,30,31],fd=(a,b,c,d)=>{function e(g,v,
r){for(g="number"==typeof g?g.toString():g||"";g.length<v;)g=r[0]+g;return g}function f(g,v){return e(g,v,"0")}function h(g,v){function r(D){return 0>D?-1:0<D?1:0}var z;0===(z=r(g.getFullYear()-v.getFullYear()))&&0===(z=r(g.getMonth()-v.getMonth()))&&(z=r(g.getDate()-v.getDate()));return z}function m(g){switch(g.getDay()){case 0:return new Date(g.getFullYear()-1,11,29);case 1:return g;case 2:return new Date(g.getFullYear(),0,3);case 3:return new Date(g.getFullYear(),0,2);case 4:return new Date(g.getFullYear(),
0,1);case 5:return new Date(g.getFullYear()-1,11,31);case 6:return new Date(g.getFullYear()-1,11,30)}}function n(g){var v=g.bb;for(g=new Date((new Date(g.cb+1900,0,1)).getTime());0<v;){var r=g.getMonth(),z=(cd(g.getFullYear())?dd:ed)[r];if(v>z-g.getDate())v-=z-g.getDate()+1,g.setDate(1),11>r?g.setMonth(r+1):(g.setMonth(0),g.setFullYear(g.getFullYear()+1));else{g.setDate(g.getDate()+v);break}}r=new Date(g.getFullYear()+1,0,4);v=m(new Date(g.getFullYear(),0,4));r=m(r);return 0>=h(v,g)?0>=h(r,g)?g.getFullYear()+
1:g.getFullYear():g.getFullYear()-1}var l=B[d+40>>2];d={$b:A[d>>2],Zb:A[d+4>>2],nb:A[d+8>>2],sb:A[d+12>>2],ob:A[d+16>>2],cb:A[d+20>>2],Wa:A[d+24>>2],bb:A[d+28>>2],oc:A[d+32>>2],Yb:A[d+36>>2],ac:l?l?H(x,l):"":""};c=c?H(x,c):"";l={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I",
"%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var u in l)c=c.replace(new RegExp(u,"g"),l[u]);var p="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),t="January February March April May June July August September October November December".split(" ");l={"%a":g=>p[g.Wa].substring(0,3),"%A":g=>p[g.Wa],"%b":g=>t[g.ob].substring(0,3),"%B":g=>t[g.ob],"%C":g=>f((g.cb+1900)/100|0,2),"%d":g=>f(g.sb,2),"%e":g=>e(g.sb,2," "),"%g":g=>
n(g).toString().substring(2),"%G":g=>n(g),"%H":g=>f(g.nb,2),"%I":g=>{g=g.nb;0==g?g=12:12<g&&(g-=12);return f(g,2)},"%j":g=>{for(var v=0,r=0;r<=g.ob-1;v+=(cd(g.cb+1900)?dd:ed)[r++]);return f(g.sb+v,3)},"%m":g=>f(g.ob+1,2),"%M":g=>f(g.Zb,2),"%n":()=>"\n","%p":g=>0<=g.nb&&12>g.nb?"AM":"PM","%S":g=>f(g.$b,2),"%t":()=>"\t","%u":g=>g.Wa||7,"%U":g=>f(Math.floor((g.bb+7-g.Wa)/7),2),"%V":g=>{var v=Math.floor((g.bb+7-(g.Wa+6)%7)/7);2>=(g.Wa+371-g.bb-2)%7&&v++;if(v)53==v&&(r=(g.Wa+371-g.bb)%7,4==r||3==r&&cd(g.cb)||
(v=1));else{v=52;var r=(g.Wa+7-g.bb-1)%7;(4==r||5==r&&cd(g.cb%400-1))&&v++}return f(v,2)},"%w":g=>g.Wa,"%W":g=>f(Math.floor((g.bb+7-(g.Wa+6)%7)/7),2),"%y":g=>(g.cb+1900).toString().substring(2),"%Y":g=>g.cb+1900,"%z":g=>{g=g.Yb;var v=0<=g;g=Math.abs(g)/60;return(v?"+":"-")+String("0000"+(g/60*100+g%60)).slice(-4)},"%Z":g=>g.ac,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");for(u in l)c.includes(u)&&(c=c.replace(new RegExp(u,"g"),l[u](d)));c=c.replace(/\0\0/g,"%");u=fb(c,!1);if(u.length>b)return 0;w.set(u,
a);return u.length-1};function Jb(a,b,c,d){a||(a=this);this.parent=a;this.Xa=a.Xa;this.jb=null;this.id=Cb++;this.name=b;this.mode=c;this.Ka={};this.Ma={};this.rdev=d}Object.defineProperties(Jb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Vb:{get:function(){return L(this.mode)}},Ub:{get:function(){return 8192===(this.mode&61440)}}});
bc();Db=Array(4096);Pb(J,"/");P("/tmp");P("/home");P("/home/web_user");(function(){P("/dev");ib(259,{read:()=>0,write:(d,e,f,h)=>h});Rb("/dev/null",259);hb(1280,kb);hb(1536,lb);Rb("/dev/tty",1280);Rb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=$a(a).byteLength);return a[--b]};Q("/dev","random",c);Q("/dev","urandom",c);P("/dev/shm");P("/dev/shm/tmp")})();
(function(){P("/proc");var a=P("/proc/self");P("/proc/self/fd");Pb({Xa(){var b=qb(a,"fd",16895,73);b.Ka={lookup(c,d){var e=N(+d);c={parent:null,Xa:{Bb:"fake"},Ka:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();k.FS_createPath=dc;k.FS_createDataFile=wb;k.FS_createPreloadedFile=xb;k.FS_unlink=Tb;k.FS_createLazyFile=gc;k.FS_createDevice=Q;for(var gd=Array(256),hd=0;256>hd;++hd)gd[hd]=String.fromCharCode(hd);lc=gd;
T=k.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};qc=k.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};Object.assign(uc.prototype,{get(a){return this.Ra[a]},has(a){return void 0!==this.Ra[a]},kb(a){var b=this.wb.pop()||this.Ra.length;this.Ra[b]=a;return b},eb(a){this.Ra[a]=void 0;this.wb.push(a)}});U.Ra.push({value:void 0},{value:null},{value:!0},{value:!1});U.Oa=U.Ra.length;
k.count_emval_handles=()=>{for(var a=0,b=U.Oa;b<U.Ra.length;++b)void 0!==U.Ra[b]&&++a;return a};Jc=k.UnboundTypeError=((a,b)=>{var c=Cc(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
var Jd={r:a=>{a=new Ra(a);a.Gb()||(a.Db(!0),Qa--);a.Eb(!1);Pa.push(a);jd(a.gb);return a.Hb()},v:()=>{W(0,0);var a=Pa.pop();kd(a.gb);F=0},a:()=>Va([]),f:a=>Va([a]),H:()=>{var a=Pa.pop();a||ra("no exception to throw");var b=a.gb;a.Ob()||(Pa.push(a),a.Eb(!0),a.Db(!1),Qa++);F=b;throw F;},p:(a,b,c)=>{(new Ra(a)).zb(b,c);F=a;Qa++;throw F;},V:()=>Qa,e:a=>{F||(F=a);throw F;},B:function(a,b,c){jc=c;try{var d=N(a);switch(b){case 0:var e=kc();if(0>e)return-28;for(;Bb[e];)e++;return Nb(d,e).fd;case 1:case 2:return 0;
case 3:return d.flags;case 4:return e=kc(),d.flags|=e,0;case 5:return e=kc(),y[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return A[ld()>>2]=28,-1;default:return-28}}catch(f){if("undefined"==typeof R||"ErrnoError"!==f.name)throw f;return-f.Pa}},ca:function(a,b){try{var c=N(a);return ic(Ub,c.path,b)}catch(d){if("undefined"==typeof R||"ErrnoError"!==d.name)throw d;return-d.Pa}},Y:function(a,b,c){try{var d=N(a);if(!d.$a){var e=M(d.path,{hb:!0}).node;if(!e.Ka.readdir)throw new I(54);
var f=e.Ka.readdir(e);d.$a=f}a=0;for(var h=$b(d,0,1),m=Math.floor(h/280);m<d.$a.length&&a+280<=c;){var n=d.$a[m];if("."===n){var l=d.node.id;var u=4}else if(".."===n)l=M(d.path,{parent:!0}).node.id,u=4;else{var p=sb(d.node,n);l=p.id;u=8192===(p.mode&61440)?2:L(p.mode)?4:40960===(p.mode&61440)?10:8}E=[l>>>0,(C=l,1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];A[b+a>>2]=E[0];A[b+a+4>>2]=E[1];E=[280*(m+1)>>>0,(C=280*(m+1),1<=+Math.abs(C)?0<C?+Math.floor(C/
4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];A[b+a+8>>2]=E[0];A[b+a+12>>2]=E[1];y[b+a+16>>1]=280;w[b+a+18>>0]=u;eb(n,x,b+a+19,256);a+=280;m+=1}$b(d,280*m,0);return a}catch(t){if("undefined"==typeof R||"ErrnoError"!==t.name)throw t;return-t.Pa}},da:function(a,b,c){jc=c;try{var d=N(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.Ya.Rb){b=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=kc();A[e>>2]=25856;A[e+4>>
2]=5;A[e+8>>2]=191;A[e+12>>2]=35387;for(var f=0;32>f;f++)w[e+f+17>>0]=b[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Ya.Sb)for(e=kc(),b=[],f=0;32>f;f++)b.push(w[e+f+17>>0]);return 0;case 21519:if(!d.tty)return-59;e=kc();return A[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:e=kc();if(!d.Ma.Qb)throw new I(59);return d.Ma.Qb(d,b,e);case 21523:if(!d.tty)return-59;d.tty.Ya.Tb&&(f=[24,80],e=kc(),y[e>>1]=f[0],y[e+2>>
1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(h){if("undefined"==typeof R||"ErrnoError"!==h.name)throw h;return-h.Pa}},$:function(a,b){try{return a=a?H(x,a):"",ic(Vb,a,b)}catch(c){if("undefined"==typeof R||"ErrnoError"!==c.name)throw c;return-c.Pa}},aa:function(a,b,c,d){try{b=b?H(x,b):"";var e=d&256;b=hc(a,b,d&4096);return ic(e?Vb:Ub,b,c)}catch(f){if("undefined"==typeof R||"ErrnoError"!==f.name)throw f;return-f.Pa}},K:function(a,b,c,d){jc=d;
try{b=b?H(x,b):"";b=hc(a,b);var e=d?kc():0;return Xb(b,c,e).fd}catch(f){if("undefined"==typeof R||"ErrnoError"!==f.name)throw f;return-f.Pa}},ba:function(a,b){try{return a=a?H(x,a):"",ic(Ub,a,b)}catch(c){if("undefined"==typeof R||"ErrnoError"!==c.name)throw c;return-c.Pa}},T:()=>{},fa:(a,b,c,d)=>{b=S(b);rc(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,f){return f?c:d},argPackAdvance:8,readValueFromPointer:function(e){return this.fromWireType(x[e])},Za:null})},ea:(a,b)=>{b=S(b);
rc(a,{name:b,fromWireType:c=>{var d=wc(c);vc(c);return d},toWireType:(c,d)=>xc(d),argPackAdvance:8,readValueFromPointer:yc,Za:null})},M:(a,b,c)=>{b=S(b);rc(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,argPackAdvance:8,readValueFromPointer:zc(b,c),Za:null})},N:(a,b,c,d,e,f,h)=>{var m=Gc(b,c);a=S(a);a=Oc(a);e=Ic(d,e);Fc(a,function(){Nc(`Cannot call ${a} due to unbound types`,m)},b-1);sc(m,function(n){var l=[n[0],null].concat(n.slice(1)),u=n=a,p=e,t=l.length;if(2>t)throw new T("argTypes array size mismatch! Must at least get return value and 'this' types!");
for(var g=null!==l[1]&&!1,v=!1,r=1;r<l.length;++r)if(null!==l[r]&&void 0===l[r].Za){v=!0;break}var z="void"!==l[0].name,D="",K="";for(r=0;r<t-2;++r)D+=(0!==r?", ":"")+"arg"+r,K+=(0!==r?", ":"")+"arg"+r+"Wired";u=`\n        return function ${Ac(u)}(${D}) {\n        if (arguments.length !== ${t-2}) {\n          throwBindingError('function ${u} called with ' + arguments.length + ' arguments, expected ${t-2}');\n        }`;v&&(u+="var destructors = [];\n");var aa=v?"destructors":"null";D="throwBindingError invoker fn runDestructors retType classParam".split(" ");
p=[pc,p,f,Bc,l[0],l[1]];g&&(u+="var thisWired = classParam.toWireType("+aa+", this);\n");for(r=0;r<t-2;++r)u+="var arg"+r+"Wired = argType"+r+".toWireType("+aa+", arg"+r+"); // "+l[r+2].name+"\n",D.push("argType"+r),p.push(l[r+2]);g&&(K="thisWired"+(0<K.length?", ":"")+K);u+=(z||h?"var rv = ":"")+"invoker(fn"+(0<K.length?", ":"")+K+");\n";if(v)u+="runDestructors(destructors);\n";else for(r=g?1:2;r<l.length;++r)t=1===r?"thisWired":"arg"+(r-2)+"Wired",null!==l[r].Za&&(u+=t+"_dtor("+t+"); // "+l[r].name+
"\n",D.push(t+"_dtor"),p.push(l[r].Za));z&&(u+="var ret = retType.fromWireType(rv);\nreturn ret;\n");D.push(u+"}\n");l=Dc(D).apply(null,p);r=b-1;if(!k.hasOwnProperty(n))throw new qc("Replacing nonexistant public symbol");void 0!==k[n].Va&&void 0!==r?k[n].Va[r]=l:(k[n]=l,k[n].Mb=r);return[]})},s:(a,b,c,d,e)=>{b=S(b);-1===e&&(e=4294967295);e=m=>m;if(0===d){var f=32-8*c;e=m=>m<<f>>>f}var h=b.includes("unsigned")?function(m,n){return n>>>0}:function(m,n){return n};rc(a,{name:b,fromWireType:e,toWireType:h,
argPackAdvance:8,readValueFromPointer:Pc(b,c,0!==d),Za:null})},o:(a,b,c)=>{function d(f){return new e(w.buffer,B[f+4>>2],B[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=S(c);rc(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Pb:!0})},L:(a,b)=>{b=S(b);var c="std::string"===b;rc(a,{name:b,fromWireType:function(d){var e=B[d>>2],f=d+4;if(c)for(var h=f,m=0;m<=e;++m){var n=f+m;if(m==e||0==x[n]){h=h?H(x,h,n-h):"";if(void 0===
l)var l=h;else l+=String.fromCharCode(0),l+=h;h=n+1}}else{l=Array(e);for(m=0;m<e;++m)l[m]=String.fromCharCode(x[f+m]);l=l.join("")}Lc(d);return l},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"==typeof e;if(!(f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array))throw new T("Cannot pass non-string to std::string");var h=c&&f?db(e):e.length;var m=md(4+h+1),n=m+4;B[m>>2]=h;if(c&&f)eb(e,x,n,h+1);else if(f)for(f=0;f<h;++f){var l=e.charCodeAt(f);
if(255<l)throw Lc(n),new T("String has UTF-16 code units that do not fit in 8 bits");x[n+f]=l}else for(f=0;f<h;++f)x[n+f]=e[f];null!==d&&d.push(Lc,m);return m},argPackAdvance:8,readValueFromPointer:Qc,Za(d){Lc(d)}})},C:(a,b,c)=>{c=S(c);if(2===b){var d=Tc;var e=Uc;var f=Vc;var h=()=>ua;var m=1}else 4===b&&(d=Wc,e=Xc,f=Yc,h=()=>B,m=2);rc(a,{name:c,fromWireType:n=>{for(var l=B[n>>2],u=h(),p,t=n+4,g=0;g<=l;++g){var v=n+4+g*b;if(g==l||0==u[v>>m])t=d(t,v-t),void 0===p?p=t:(p+=String.fromCharCode(0),p+=
t),t=v+b}Lc(n);return p},toWireType:(n,l)=>{if("string"!=typeof l)throw new T(`Cannot pass non-string to C++ string type ${c}`);var u=f(l),p=md(4+u+b);B[p>>2]=u>>m;e(l,p+4,u+b);null!==n&&n.push(Lc,p);return p},argPackAdvance:8,readValueFromPointer:yc,Za(n){Lc(n)}})},ga:(a,b)=>{b=S(b);rc(a,{jc:!0,name:b,argPackAdvance:0,fromWireType:()=>{},toWireType:()=>{}})},W:()=>{throw Infinity;},ia:vc,ha:a=>{4<a&&(U.get(a).Cb+=1)},O:a=>{var b=Zc[a];return xc(void 0===b?S(a):b)},la:()=>xc({}),ja:(a,b,c)=>{a=wc(a);
b=wc(b);c=wc(c);a[b]=c},ka:(a,b)=>{var c=nc[a];if(void 0===c)throw a="_emval_take_value has unknown type "+Mc(a),new T(a);a=c;a=a.readValueFromPointer(b);return xc(a)},Q:function(a,b,c,d,e,f,h,m){e=f+2097152>>>0<4194305-!!e?(e>>>0)+4294967296*f:NaN;try{if(isNaN(e))return 61;var n=N(d);if(0!==(b&2)&&0===(c&2)&&2!==(n.flags&2097155))throw new I(2);if(1===(n.flags&2097155))throw new I(2);if(!n.Ma.ib)throw new I(43);var l=n.Ma.ib(n,a,e,b,c);var u=l.Qa;A[h>>2]=l.Ra;B[m>>2]=u;return 0}catch(p){if("undefined"==
typeof R||"ErrnoError"!==p.name)throw p;return-p.Pa}},R:function(a,b,c,d,e,f,h){f=h+2097152>>>0<4194305-!!f?(f>>>0)+4294967296*h:NaN;try{if(isNaN(f))return 61;var m=N(e);if(c&2){if(32768!==(m.node.mode&61440))throw new I(43);if(!(d&2)){var n=x.slice(a,a+b);m.Ma.mb&&m.Ma.mb(m,n,f,b,d)}}}catch(l){if("undefined"==typeof R||"ErrnoError"!==l.name)throw l;return-l.Pa}},A:()=>{ra("")},X:a=>{var b=x.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=
Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-sa.buffer.byteLength+65535)/65536;try{sa.grow(e);xa();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},Z:(a,b)=>{var c=0;bd().forEach((d,e)=>{var f=b+c;e=B[a+4*e>>2]=f;for(f=0;f<d.length;++f)w[e++>>0]=d.charCodeAt(f);w[e>>0]=0;c+=d.length+1});return 0},_:(a,b)=>{var c=bd();B[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);B[b>>2]=d;return 0},z:function(a){try{var b=N(a);Zb(b);return 0}catch(c){if("undefined"==
typeof R||"ErrnoError"!==c.name)throw c;return c.Pa}},I:function(a,b,c,d){try{a:{var e=N(a);a=b;for(var f,h=b=0;h<c;h++){var m=B[a>>2],n=B[a+4>>2];a+=8;var l=e,u=m,p=n,t=f,g=w;if(0>p||0>t)throw new I(28);if(null===l.fd)throw new I(8);if(1===(l.flags&2097155))throw new I(8);if(L(l.node.mode))throw new I(31);if(!l.Ma.read)throw new I(28);var v="undefined"!=typeof t;if(!v)t=l.position;else if(!l.seekable)throw new I(70);var r=l.Ma.read(l,g,u,p,t);v||(l.position+=r);var z=r;if(0>z){var D=-1;break a}b+=
z;if(z<n)break;"undefined"!==typeof f&&(f+=z)}D=b}B[d>>2]=D;return 0}catch(K){if("undefined"==typeof R||"ErrnoError"!==K.name)throw K;return K.Pa}},S:function(a,b,c,d,e){b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;try{if(isNaN(b))return 61;var f=N(a);$b(f,b,d);E=[f.position>>>0,(C=f.position,1<=+Math.abs(C)?0<C?+Math.floor(C/4294967296)>>>0:~~+Math.ceil((C-+(~~C>>>0))/4294967296)>>>0:0)];A[e>>2]=E[0];A[e+4>>2]=E[1];f.$a&&0===b&&0===d&&(f.$a=null);return 0}catch(h){if("undefined"==typeof R||
"ErrnoError"!==h.name)throw h;return h.Pa}},J:function(a,b,c,d){try{a:{var e=N(a);a=b;for(var f,h=b=0;h<c;h++){var m=B[a>>2],n=B[a+4>>2];a+=8;var l=ac(e,w,m,n,f);if(0>l){var u=-1;break a}b+=l;"undefined"!==typeof f&&(f+=l)}u=b}B[d>>2]=u;return 0}catch(p){if("undefined"==typeof R||"ErrnoError"!==p.name)throw p;return p.Pa}},E:nd,F:od,n:pd,d:qd,c:rd,j:sd,h:td,D:ud,q:vd,G:wd,y:xd,P:yd,k:zd,m:Ad,b:Bd,g:Cd,i:Dd,l:Ed,u:Fd,t:Gd,w:Hd,x:Id,U:(a,b,c,d)=>fd(a,b,c,d)},X=function(){function a(c){X=c.exports;sa=
X.ma;xa();V=X.qa;za.unshift(X.na);Ga("wasm-instantiate");return X}var b={a:Jd};Fa("wasm-instantiate");if(k.instantiateWasm)try{return k.instantiateWasm(b,a)}catch(c){pa(`Module.instantiateWasm callback failed with error: ${c}`),ca(c)}Na(b,function(c){a(c.instance)}).catch(ca);return{}}(),md=a=>(md=X.oa)(a),Lc=a=>(Lc=X.pa)(a),ld=()=>(ld=X.ra)(),Ta=a=>(Ta=X.sa)(a),Kc=a=>(Kc=X.ta)(a);k.__embind_initialize_bindings=()=>(k.__embind_initialize_bindings=X.ua)();k._fflush=a=>(k._fflush=X.va)(a);
var mb=(a,b)=>(mb=X.wa)(a,b),W=(a,b)=>(W=X.xa)(a,b),Y=()=>(Y=X.ya)(),Z=a=>(Z=X.za)(a),kd=a=>(kd=X.Aa)(a),jd=a=>(jd=X.Ba)(a),Ua=(a,b,c)=>(Ua=X.Ca)(a,b,c),Sa=a=>(Sa=X.Da)(a);k.dynCall_jiji=(a,b,c,d,e)=>(k.dynCall_jiji=X.Ea)(a,b,c,d,e);k.dynCall_viijii=(a,b,c,d,e,f,h)=>(k.dynCall_viijii=X.Fa)(a,b,c,d,e,f,h);var Kd=k.dynCall_jiiii=(a,b,c,d,e)=>(Kd=k.dynCall_jiiii=X.Ga)(a,b,c,d,e);k.dynCall_iiiiij=(a,b,c,d,e,f,h)=>(k.dynCall_iiiiij=X.Ha)(a,b,c,d,e,f,h);
k.dynCall_iiiiijj=(a,b,c,d,e,f,h,m,n)=>(k.dynCall_iiiiijj=X.Ia)(a,b,c,d,e,f,h,m,n);k.dynCall_iiiiiijj=(a,b,c,d,e,f,h,m,n,l)=>(k.dynCall_iiiiiijj=X.Ja)(a,b,c,d,e,f,h,m,n,l);function rd(a,b,c){var d=Y();try{return V.get(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;W(1,0)}}function zd(a){var b=Y();try{V.get(a)()}catch(c){Z(b);if(c!==c+0)throw c;W(1,0)}}function Bd(a,b,c){var d=Y();try{V.get(a)(b,c)}catch(e){Z(d);if(e!==e+0)throw e;W(1,0)}}
function vd(a,b,c,d,e,f,h){var m=Y();try{return V.get(a)(b,c,d,e,f,h)}catch(n){Z(m);if(n!==n+0)throw n;W(1,0)}}function Ad(a,b){var c=Y();try{V.get(a)(b)}catch(d){Z(c);if(d!==d+0)throw d;W(1,0)}}function Cd(a,b,c,d){var e=Y();try{V.get(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}function qd(a,b){var c=Y();try{return V.get(a)(b)}catch(d){Z(c);if(d!==d+0)throw d;W(1,0)}}function sd(a,b,c,d){var e=Y();try{return V.get(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}
function ud(a,b,c,d,e,f){var h=Y();try{return V.get(a)(b,c,d,e,f)}catch(m){Z(h);if(m!==m+0)throw m;W(1,0)}}function Ed(a,b,c,d,e,f){var h=Y();try{V.get(a)(b,c,d,e,f)}catch(m){Z(h);if(m!==m+0)throw m;W(1,0)}}function Dd(a,b,c,d,e){var f=Y();try{V.get(a)(b,c,d,e)}catch(h){Z(f);if(h!==h+0)throw h;W(1,0)}}function td(a,b,c,d,e){var f=Y();try{return V.get(a)(b,c,d,e)}catch(h){Z(f);if(h!==h+0)throw h;W(1,0)}}function pd(a){var b=Y();try{return V.get(a)()}catch(c){Z(b);if(c!==c+0)throw c;W(1,0)}}
function Fd(a,b,c,d,e,f,h){var m=Y();try{V.get(a)(b,c,d,e,f,h)}catch(n){Z(m);if(n!==n+0)throw n;W(1,0)}}function Gd(a,b,c,d,e,f,h,m){var n=Y();try{V.get(a)(b,c,d,e,f,h,m)}catch(l){Z(n);if(l!==l+0)throw l;W(1,0)}}function wd(a,b,c,d,e,f,h,m){var n=Y();try{return V.get(a)(b,c,d,e,f,h,m)}catch(l){Z(n);if(l!==l+0)throw l;W(1,0)}}function od(a,b,c,d){var e=Y();try{return V.get(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}
function nd(a,b,c,d){var e=Y();try{return V.get(a)(b,c,d)}catch(f){Z(e);if(f!==f+0)throw f;W(1,0)}}function xd(a,b,c,d,e,f,h,m,n,l,u,p){var t=Y();try{return V.get(a)(b,c,d,e,f,h,m,n,l,u,p)}catch(g){Z(t);if(g!==g+0)throw g;W(1,0)}}function Hd(a,b,c,d,e,f,h,m,n,l,u){var p=Y();try{V.get(a)(b,c,d,e,f,h,m,n,l,u)}catch(t){Z(p);if(t!==t+0)throw t;W(1,0)}}function Id(a,b,c,d,e,f,h,m,n,l,u,p,t,g,v,r){var z=Y();try{V.get(a)(b,c,d,e,f,h,m,n,l,u,p,t,g,v,r)}catch(D){Z(z);if(D!==D+0)throw D;W(1,0)}}
function yd(a,b,c,d,e){var f=Y();try{return Kd(a,b,c,d,e)}catch(h){Z(f);if(h!==h+0)throw h;W(1,0)}}k.addRunDependency=Fa;k.removeRunDependency=Ga;k.FS_createPath=dc;k.FS_createLazyFile=gc;k.FS_createDevice=Q;k.FS_createPreloadedFile=xb;k.FS_createDataFile=wb;k.FS_unlink=Tb;var Ld;Ea=function Md(){Ld||Nd();Ld||(Ea=Md)};
function Nd(){function a(){if(!Ld&&(Ld=!0,k.calledRun=!0,!ta)){k.noFSInit||cc||(cc=!0,bc(),k.stdin=k.stdin,k.stdout=k.stdout,k.stderr=k.stderr,k.stdin?Q("/dev","stdin",k.stdin):Sb("/dev/tty","/dev/stdin"),k.stdout?Q("/dev","stdout",null,k.stdout):Sb("/dev/tty","/dev/stdout"),k.stderr?Q("/dev","stderr",null,k.stderr):Sb("/dev/tty1","/dev/stderr"),Xb("/dev/stdin",0),Xb("/dev/stdout",1),Xb("/dev/stderr",1));Eb=!1;Oa(za);ba(k);if(k.onRuntimeInitialized)k.onRuntimeInitialized();if(k.postRun)for("function"==
typeof k.postRun&&(k.postRun=[k.postRun]);k.postRun.length;){var b=k.postRun.shift();Aa.unshift(b)}Oa(Aa)}}if(!(0<Ca)){if(k.preRun)for("function"==typeof k.preRun&&(k.preRun=[k.preRun]);k.preRun.length;)Ba();Oa(ya);0<Ca||(k.setStatus?(k.setStatus("Running..."),setTimeout(function(){setTimeout(function(){k.setStatus("")},1);a()},1)):a())}}if(k.preInit)for("function"==typeof k.preInit&&(k.preInit=[k.preInit]);0<k.preInit.length;)k.preInit.pop()();Nd();


  return moduleArg.ready
}

);
})();
export default Module;